import { mc } from "./seed";
import type { QuestionSeed } from "./seed";

export const ENTERTAINMENT_SEEDS: QuestionSeed[] = [
  mc("easy", "Who played Iron Man in the Marvel Cinematic Universe?", "Robert Downey Jr.", ["Chris Evans", "Chris Hemsworth", "Mark Ruffalo"]),
  mc("easy", "What is the highest-grossing animated movie franchise featuring minions?", "Despicable Me", ["Shrek", "Toy Story", "Madagascar"]),
  mc("easy", "Which streaming service produced 'Stranger Things'?", "Netflix", ["Hulu", "Disney+", "Amazon Prime"]),
  mc("easy", "Who is known as the 'King of Pop'?", "Michael Jackson", ["Elvis Presley", "Prince", "Justin Timberlake"]),
  mc("easy", "What is the name of the wizard school in Harry Potter?", "Hogwarts", ["Beauxbatons", "Durmstrang", "Ilvermorny"]),
  mc("easy", "Which Disney movie features a snowman named Olaf?", "Frozen", ["Tangled", "Moana", "Encanto"]),
  mc("easy", "Who directed the movie 'Jaws'?", "Steven Spielberg", ["George Lucas", "Martin Scorsese", "James Cameron"]),
  mc("easy", "What is the name of the coffee shop in the show 'Friends'?", "Central Perk", ["The Grind", "Java Joe's", "Coffee Bean"]),
  mc("easy", "Which animated mouse is the mascot of Disney?", "Mickey Mouse", ["Jerry", "Stuart Little", "Mighty Mouse"]),
  mc("easy", "Who played Jack Dawson in the movie 'Titanic'?", "Leonardo DiCaprio", ["Brad Pitt", "Matt Damon", "Tom Cruise"]),
  mc("medium", "Which actor won a posthumous Oscar for playing the Joker in 'The Dark Knight'?", "Heath Ledger", ["Jared Leto", "Jack Nicholson", "Joaquin Phoenix"]),
  mc("medium", "What is the name of the fictional African country in 'Black Panther'?", "Wakanda", ["Zamunda", "Genovia", "Latveria"]),
  mc("medium", "Which band released the album 'Abbey Road'?", "The Beatles", ["The Rolling Stones", "Pink Floyd", "Led Zeppelin"]),
  mc("medium", "Who wrote the 'Harry Potter' book series?", "J.K. Rowling", ["Suzanne Collins", "Stephenie Meyer", "Rick Riordan"]),
  mc("medium", "What is the highest-grossing film of all time (unadjusted for inflation)?", "Avatar", ["Avengers: Endgame", "Titanic", "Star Wars: The Force Awakens"]),
  mc("medium", "Which TV show is set in the fictional town of Hawkins, Indiana?", "Stranger Things", ["Twin Peaks", "Riverdale", "Pretty Little Liars"]),
  mc("medium", "Who composed the music for 'Star Wars'?", "John Williams", ["Hans Zimmer", "Danny Elfman", "Howard Shore"]),
  mc("medium", "What award is given for excellence in film, presented annually by the Academy?", "Academy Award (Oscar)", ["Golden Globe", "Emmy", "Tony Award"]),
  mc("medium", "Which artist is known for the song 'Thriller'?", "Michael Jackson", ["Prince", "Stevie Wonder", "Lionel Richie"]),
  mc("medium", "What is the name of the ship in the Pirates of the Caribbean films captained by Jack Sparrow?", "Black Pearl", ["Flying Dutchman", "Queen Anne's Revenge", "Interceptor"]),
  mc("hard", "Who was the first actor to play James Bond on film?", "Sean Connery", ["Roger Moore", "Daniel Craig", "George Lazenby"]),
  mc("hard", "Which film won the first-ever Academy Award for Best Picture?", "Wings", ["Sunrise", "The Jazz Singer", "All Quiet on the Western Front"]),
  mc("hard", "What was the first feature-length animated film ever released?", "Snow White and the Seven Dwarfs", ["Pinocchio", "Fantasia", "Bambi"]),
  mc("hard", "Which musician was known as 'The Boss'?", "Bruce Springsteen", ["Bob Dylan", "Neil Young", "Tom Petty"]),
  mc("hard", "Who directed 'Pulp Fiction'?", "Quentin Tarantino", ["Martin Scorsese", "Coen Brothers", "David Fincher"]),
  mc("hard", "What was the name of the radio drama that caused panic in 1938 by simulating an alien invasion?", "The War of the Worlds", ["Invasion from Mars", "The Day the Earth Stood Still", "War of Worlds Live"]),
  mc("expert", "Who composed the opera 'The Magic Flute'?", "Wolfgang Amadeus Mozart", ["Ludwig van Beethoven", "Johann Sebastian Bach", "Franz Schubert"]),
  mc("expert", "Which silent film actor was famous for his 'Little Tramp' character?", "Charlie Chaplin", ["Buster Keaton", "Harold Lloyd", "Fatty Arbuckle"]),
  mc("expert", "What was the first feature film to use synchronized dialogue, released in 1927?", "The Jazz Singer", ["Wings", "Sunrise", "Metropolis"]),
  mc("expert", "Who won the most competitive Academy Awards for acting (4 total)?", "Katharine Hepburn", ["Meryl Streep", "Jack Nicholson", "Daniel Day-Lewis"]),
];
