import { mc } from "./seed";
import type { QuestionSeed } from "./seed";

export const ENTERTAINMENT_SEEDS: QuestionSeed[] = [
  mc("easy", "Who played Iron Man in the Marvel Cinematic Universe?", "Robert Downey Jr.", ["Chris Evans", "Chris Hemsworth", "Mark Ruffalo"]),
  mc("easy", "Which streaming service produced 'Stranger Things'?", "Netflix", ["Hulu", "Disney+", "Amazon Prime"]),
  mc("easy", "Who is known as the 'King of Pop'?", "Michael Jackson", ["Elvis Presley", "Prince", "Justin Timberlake"]),
  mc("easy", "What is the name of the wizard school in Harry Potter?", "Hogwarts", ["Beauxbatons", "Durmstrang", "Ilvermorny"]),
  mc("easy", "Which Disney movie features a snowman named Olaf?", "Frozen", ["Tangled", "Moana", "Encanto"]),
  mc("easy", "Who directed the movie 'Jaws'?", "Steven Spielberg", ["George Lucas", "Martin Scorsese", "James Cameron"]),
  mc("easy", "What is the name of the coffee shop in 'Friends'?", "Central Perk", ["The Grind", "Java Joe's", "Coffee Bean"]),
  mc("easy", "Which animated mouse is the mascot of Disney?", "Mickey Mouse", ["Jerry", "Stuart Little", "Mighty Mouse"]),
  mc("easy", "Who played Jack Dawson in 'Titanic'?", "Leonardo DiCaprio", ["Brad Pitt", "Matt Damon", "Tom Cruise"]),
  mc("easy", "Which band sang 'Bohemian Rhapsody'?", "Queen", ["The Beatles", "Led Zeppelin", "Pink Floyd"]),
  mc("easy", "What is the name of Harry Potter's owl?", "Hedwig", ["Errol", "Pigwidgeon", "Crookshanks"]),
  mc("easy", "Who voices Buzz Lightyear in Toy Story?", "Tim Allen", ["Tom Hanks", "Billy Crystal", "John Goodman"]),
  mc("easy", "Which show features the character Walter White?", "Breaking Bad", ["Better Call Saul", "Ozark", "Narcos"]),
  mc("easy", "What is the highest-grossing film franchise of all time?", "Marvel Cinematic Universe", ["Star Wars", "Harry Potter", "James Bond"]),
  mc("easy", "Who sang 'Shape of You'?", "Ed Sheeran", ["Justin Bieber", "Bruno Mars", "Sam Smith"]),
  mc("easy", "What country is the Netflix show 'Money Heist' (La Casa de Papel) from?", "Spain", ["Italy", "Mexico", "Brazil"]),
  mc("easy", "Which superhero is known as the Dark Knight?", "Batman", ["Superman", "Spider-Man", "Iron Man"]),
  mc("easy", "Who sang 'Rolling in the Deep'?", "Adele", ["Beyoncé", "Rihanna", "Amy Winehouse"]),
  mc("easy", "What is the name of the lion in 'The Lion King'?", "Simba", ["Mufasa", "Nala", "Scar"]),
  mc("easy", "Which film series features the character Katniss Everdeen?", "The Hunger Games", ["Divergent", "Maze Runner", "Twilight"]),
  mc("medium", "Which actor won a posthumous Oscar for playing the Joker in 'The Dark Knight'?", "Heath Ledger", ["Jared Leto", "Jack Nicholson", "Joaquin Phoenix"]),
  mc("medium", "What is the name of the fictional African country in 'Black Panther'?", "Wakanda", ["Zamunda", "Genovia", "Latveria"]),
  mc("medium", "Which band released the album 'Abbey Road'?", "The Beatles", ["The Rolling Stones", "Pink Floyd", "Led Zeppelin"]),
  mc("medium", "Who wrote the 'Harry Potter' book series?", "J.K. Rowling", ["Suzanne Collins", "Stephenie Meyer", "Rick Riordan"]),
  mc("medium", "What is the highest-grossing film of all time (unadjusted)?", "Avatar", ["Avengers: Endgame", "Titanic", "Star Wars: The Force Awakens"]),
  mc("medium", "Who composed the music for 'Star Wars'?", "John Williams", ["Hans Zimmer", "Danny Elfman", "Howard Shore"]),
  mc("medium", "What is the name of Tony Stark's AI assistant?", "JARVIS", ["FRIDAY", "VISION", "ULTRON"]),
  mc("medium", "Which TV show is set in the fictional town of Hawkins, Indiana?", "Stranger Things", ["Twin Peaks", "Riverdale", "Pretty Little Liars"]),
  mc("medium", "Who played Forrest Gump?", "Tom Hanks", ["Tom Cruise", "Kevin Costner", "Robin Williams"]),
  mc("medium", "Which film won Best Picture at the 2020 Oscars?", "Parasite", ["1917", "Joker", "Once Upon a Time in Hollywood"]),
  mc("medium", "Who played Hermione Granger in the Harry Potter films?", "Emma Watson", ["Emma Stone", "Keira Knightley", "Natalie Portman"]),
  mc("medium", "What is the name of the fictional island in 'Jurassic Park'?", "Isla Nublar", ["Isla Sorna", "Skull Island", "Nublar Island"]),
  mc("medium", "Which artist released the album 'Lemonade'?", "Beyoncé", ["Rihanna", "Taylor Swift", "Adele"]),
  mc("medium", "Who played the Joker in the 2019 film 'Joker'?", "Joaquin Phoenix", ["Heath Ledger", "Jared Leto", "Jack Nicholson"]),
  mc("medium", "What is the real name of the rapper known as Eminem?", "Marshall Mathers", ["Calvin Broadus", "Shawn Carter", "Curtis Jackson"]),
  mc("medium", "Which show features dragons and houses Stark, Lannister, and Targaryen?", "Game of Thrones", ["The Witcher", "House of the Dragon", "Vikings"]),
  mc("medium", "Who sang 'Uptown Funk'?", "Mark Ronson ft. Bruno Mars", ["Bruno Mars", "Justin Timberlake", "Pharrell Williams"]),
  mc("hard", "Who was the first actor to play James Bond on film?", "Sean Connery", ["Roger Moore", "Daniel Craig", "George Lazenby"]),
  mc("hard", "Which film won the first-ever Academy Award for Best Picture?", "Wings", ["Sunrise", "The Jazz Singer", "All Quiet on the Western Front"]),
  mc("hard", "What was the first feature-length animated film ever released?", "Snow White and the Seven Dwarfs", ["Pinocchio", "Fantasia", "Bambi"]),
  mc("hard", "Which musician was known as 'The Boss'?", "Bruce Springsteen", ["Bob Dylan", "Neil Young", "Tom Petty"]),
  mc("hard", "Who directed 'Pulp Fiction'?", "Quentin Tarantino", ["Martin Scorsese", "Coen Brothers", "David Fincher"]),
  mc("hard", "What was the name of the radio drama that caused panic in 1938 by simulating an alien invasion?", "The War of the Worlds", ["Invasion from Mars", "The Day the Earth Stood Still", "War of Worlds Live"]),
  mc("hard", "Which film director is known for the 'Dollars Trilogy' of westerns?", "Sergio Leone", ["Sam Peckinpah", "Howard Hawks", "John Ford"]),
  mc("hard", "Which band released 'The Dark Side of the Moon' in 1973?", "Pink Floyd", ["Led Zeppelin", "The Who", "Genesis"]),
  mc("hard", "What film features the quote 'Here's looking at you, kid'?", "Casablanca", ["Gone with the Wind", "The Maltese Falcon", "Sunset Boulevard"]),
  mc("hard", "Which actress has won the most Academy Awards for acting?", "Katharine Hepburn (4)", ["Meryl Streep (3)", "Frances McDormand (3)", "Ingrid Bergman (3)"]),
  mc("expert", "Who composed the opera 'The Magic Flute'?", "Wolfgang Amadeus Mozart", ["Ludwig van Beethoven", "Johann Sebastian Bach", "Franz Schubert"]),
  mc("expert", "Which silent film actor was famous for his 'Little Tramp' character?", "Charlie Chaplin", ["Buster Keaton", "Harold Lloyd", "Fatty Arbuckle"]),
  mc("expert", "What was the first feature film to use synchronized dialogue?", "The Jazz Singer (1927)", ["Wings", "Sunrise", "Metropolis"]),
  mc("expert", "Which Kubrick film was originally rated X in the US upon release?", "A Clockwork Orange", ["Full Metal Jacket", "The Shining", "2001: A Space Odyssey"]),
  mc("expert", "Who wrote the novel that the film 'The Godfather' is based on?", "Mario Puzo", ["Francis Ford Coppola", "Elmore Leonard", "James Ellroy"]),
  mc("expert", "What was Michael Jackson's best-selling album of all time?", "Thriller", ["Bad", "Off the Wall", "Dangerous"]),
  mc("expert", "Which film holds the record for the most Academy Award wins (tied at 11)?", "Ben-Hur, Titanic, and The Lord of the Rings: The Return of the King", ["Gone with the Wind", "Lawrence of Arabia", "Schindler's List"]),
  mc("expert", "Who directed '2001: A Space Odyssey'?", "Stanley Kubrick", ["Ridley Scott", "Steven Spielberg", "George Lucas"]),
  mc("expert", "Which artist's real name is Stefani Joanne Angelina Germanotta?", "Lady Gaga", ["Katy Perry", "Nicki Minaj", "Pink"]),
  mc("expert", "What year was the first episode of 'The Simpsons' aired?", "1989", ["1987", "1991", "1993"]),
  mc("easy", "Which actor played Iron Man in the Marvel Cinematic Universe?", "Robert Downey Jr.", ["Chris Evans", "Mark Ruffalo", "Tom Holland"]),
  mc("easy", "What is the name of the coffee shop in the TV series 'Friends'?", "Central Perk", ["The Daily Grind", "Common Grounds", "Brew Haven"]),
  mc("easy", "Who directed the film 'Titanic' (1997)?", "James Cameron", ["Steven Spielberg", "Christopher Nolan", "Martin Scorsese"]),
  mc("medium", "What year did the first episode of 'The Simpsons' air on Fox?", "1989", ["1987", "1991", "1993"]),
  mc("medium", "Which British rock band released the album 'Dark Side of the Moon'?", "Pink Floyd", ["Led Zeppelin", "The Who", "Black Sabbath"]),
  mc("medium", "In 'The Lord of the Rings,' what is the name of Frodo's home?", "The Shire", ["Rivendell", "Mirkwood", "Lothlórien"]),
  mc("medium", "How many strings does a standard violin have?", "4", ["5", "6", "8"]),
  mc("medium", "Which movie won the Academy Award for Best Picture in 2020?", "Parasite", ["1917", "Joker", "Once Upon a Time in Hollywood"]),
  mc("hard", "What is the real name of the superhero Black Panther in the MCU?", "T'Challa", ["Erik Killmonger", "N'Jadaka", "Ulysses Klaue"]),
  mc("hard", "Which horror film franchise features Ghostface as its primary killer?", "Scream", ["Halloween", "Friday the 13th", "A Nightmare on Elm Street"]),
  mc("hard", "In 'Breaking Bad,' what is the street name for Walter White's methamphetamine?", "Blue Sky", ["Crystal Blue", "Ice Blue", "Sky Blue"]),
  mc("hard", "Who composed the original score for 'The Lion King' (1994)?", "Elton John and Tim Rice", ["John Williams and Hans Zimmer", "Alan Menken and Stephen Schwartz", "Andrew Lloyd Webber and Don Black"]),
  mc("expert", "What was the working title of 'Star Wars: A New Hope' before its 1977 release?", "Blue Harvest", ["Black Squadron", "Operation Skyrise", "Code Red Leader"]),
  mc("expert", "Which actor voiced Darth Vader but was credited to another performer in 'The Empire Strikes Back'?", "James Earl Jones", ["David Prowse", "Sebastian Shaw", "Ian McDiarmid"]),
  mc("expert", "In 'Citizen Kane,' what is the name of the sled that becomes central to the film's mystery?", "Rosebud", ["Snowfall", "Winter's Child", "Childplay"]),
  mc("easy", "Which actor plays Iron Man in the Marvel Cinematic Universe?", "Robert Downey Jr.", ["Chris Evans", "Mark Ruffalo", "Tom Hiddleston"]),
  mc("easy", "Who won the Academy Award for Best Picture in 2020?", "Parasite", ["1917", "Once Upon a Time in Hollywood", "Joker"]),
  mc("medium", "Which horror film franchise features the character Pinhead?", "Hellraiser", ["A Nightmare on Elm Street", "Friday the 13th", "The Texas Chain Saw Massacre"]),
  mc("medium", "What was the first animated feature film produced by Pixar?", "Toy Story", ["A Bug's Life", "Monsters, Inc.", "Finding Nemo"]),
  mc("medium", "In 'The Office' (US version), what company does Michael Scott work for?", "Dunder Mifflin", ["Sabre", "Wernham Hogg", "Initech"]),
  mc("medium", "Which film won the Golden Globe for Best Motion Picture – Drama in 2022?", "Power of the Dog", ["Dune", "Belfast", "West Side Story"]),
  mc("medium", "What is the stage name of Marshall Bruce Mathers III?", "Eminem", ["Dr. Dre", "50 Cent", "Jay-Z"]),
  mc("hard", "In which year did 'The Simpsons' first air on television?", "1989", ["1987", "1991", "1985"]),
  mc("hard", "Which filmmaker directed both 'Inception' and 'Interstellar'?", "Christopher Nolan", ["Denis Villeneuve", "Steven Spielberg", "James Cameron"]),
  mc("hard", "What was the original working title for 'Star Wars: A New Hope'?", "Blue Harvest", ["Black Sun", "Red Squadron", "Death Star Rising"]),
  mc("hard", "Which anime series was created by Hajime Isayama?", "Attack on Titan", ["Death Note", "Demon Slayer", "Jujutsu Kaisen"]),
  mc("expert", "In 'Pulp Fiction', what is the combination to Marsellus Wallace's briefcase?", "It is never revealed in the film", ["666", "1234", "7734"]),
  mc("expert", "Which composer scored the original 'Blade Runner' film released in 1982?", "Vangelis", ["John Williams", "Hans Zimmer", "Jerry Goldsmith"]),
  mc("expert", "What is the name of the fictional town in 'Twin Peaks'?", "Twin Peaks", ["Deer Meadow", "Black Lodge", "White Pine Mountains"]),
  mc("easy", "What is the highest-grossing animated film of all time?", "Inside Out 2", ["Frozen II", "The Lion King", "Toy Story 4"]),
  mc("easy", "Which streaming service produces 'The Crown'?", "Netflix", ["Disney+", "HBO Max", "Amazon Prime Video"]),
  mc("medium", "What year did 'Breaking Bad' series finale air?", "2013", ["2012", "2014", "2011"]),
  mc("medium", "Which director won the Academy Award for Best Director for 'Oppenheimer'?", "Christopher Nolan", ["Denis Villeneuve", "Justine Triet", "Yorgos Lanthimos"]),
  mc("medium", "In 'The Office,' what is the name of the paper company where the show is set?", "Dunder Mifflin", ["Sabre", "Wernham Hogg", "Staples"]),
  mc("medium", "Which K-pop group released 'Dynamite' in 2020?", "BTS", ["BLACKPINK", "EXO", "Twice"]),
  mc("medium", "What is the real name of the character 'Elsa' in Disney's 'Frozen'?", "Elsa", ["Anna", "Elisa", "Elsie"]),
  mc("hard", "Which film won the Palme d'Or at the 2019 Cannes Film Festival?", "Parasite", ["The Farewell", "Once Upon a Time in Hollywood", "Portrait of a Lady on Fire"]),
  mc("hard", "In 'Game of Thrones,' what is the motto of House Stark?", "The North Remembers", ["Winter is Coming", "Ours is the Fury", "Fire and Blood"]),
  mc("hard", "How many Academy Awards did 'Titanic' win in 1998?", "11", ["10", "12", "9"]),
  mc("hard", "What was the original title of 'Star Wars: A New Hope' before 1981?", "Star Wars", ["Star Wars: Episode IV", "The Star Wars", "A New Beginning"]),
  mc("expert", "In 'Twin Peaks,' what is the full name of the character known as 'The Log Lady'?", "Margaret Lanterman", ["Margaret Leadbetter", "Margaret Lindstrom", "Margaret Longwood"]),
  mc("expert", "Which cinematographer shot all three films of the original 'Matrix' trilogy?", "Bill Pope", ["Roger Deakins", "Hoyte van Hoytema", "Janusz Kamiński"]),
  mc("expert", "In 'Mulholland Drive,' what is the name of the blue box?", "It is never named", ["The Dreambox", "Silencio", "The Blue Key"]),
  mc("easy", "What is the name of the main character in the 'Toy Story' franchise?", "Woody", ["Buzz", "Andy", "Jessie"]),
  mc("medium", "In 'The Office' (US version), what city does the show take place in?", "Scranton, Pennsylvania", ["Portland, Oregon", "Austin, Texas", "Dunder Mifflin, New Jersey"]),
  mc("medium", "Which director won the Academy Award for Best Director for 'Parasite'?", "Bong Joon-ho", ["Lee Chang-dong", "Park Chan-wook", "Yeon Sang-ho"]),
];
