import { mc } from "./seed";
import type { QuestionSeed } from "./seed";

export const GENERAL_SEEDS: QuestionSeed[] = [
  mc("easy", "How many sides does a hexagon have?", "6", ["5", "7", "8"]),
  mc("easy", "What colour is a ruby?", "Red", ["Blue", "Green", "Purple"]),
  mc("easy", "How many days are in a leap year?", "366", ["365", "367", "364"]),
  mc("easy", "What is the opposite of 'north' on a compass?", "South", ["East", "West", "Southwest"]),
  mc("easy", "How many months have 31 days?", "7", ["6", "8", "5"]),
  mc("easy", "What is the currency of the United Kingdom?", "Pound sterling", ["Euro", "Dollar", "Franc"]),
  mc("easy", "Approximately how many weeks are there in a standard calendar year?", "52", ["48", "50", "54"]),
  mc("easy", "Which language has the most native speakers in the world?", "Mandarin Chinese", ["English", "Spanish", "Hindi"]),
  mc("easy", "How many centimetres are in a metre?", "100", ["10", "1000", "50"]),
  mc("easy", "What gas do humans exhale when they breathe out?", "Carbon dioxide", ["Oxygen", "Nitrogen", "Hydrogen"]),
  mc("easy", "What colour are emeralds?", "Green", ["Blue", "Red", "Yellow"]),
  mc("easy", "How many hours are in a day?", "24", ["12", "48", "20"]),
  mc("easy", "What is 50% of 200?", "100", ["50", "150", "25"]),
  mc("easy", "How many strings does a standard guitar have?", "6", ["4", "8", "5"]),
  mc("easy", "What is the boiling point of water in Fahrenheit?", "212°F", ["100°F", "180°F", "250°F"]),
  mc("easy", "Which planet in our solar system is known for its distinctive blue color caused by methane in its atmosphere?", "Neptune", ["Saturn", "Jupiter", "Mercury"]),
  mc("easy", "How many faces does a cube have?", "6", ["4", "8", "5"]),
  mc("easy", "What is the largest organ in the human body?", "Skin", ["Liver", "Brain", "Lungs"]),
  mc("easy", "What material is a pencil's writing core made of?", "Graphite", ["Lead", "Carbon", "Charcoal"]),
  mc("easy", "How many zeros are in one million?", "6", ["5", "7", "8"]),
  mc("medium", "As of 2024, what is the longest-running Broadway musical currently in production?", "Chicago", ["The Lion King", "Wicked", "Hamilton"]),
  mc("medium", "What is the name of the phobia of spiders?", "Arachnophobia", ["Agoraphobia", "Claustrophobia", "Entomophobia"]),
  mc("medium", "Which language has the most native speakers across South America?", "Spanish", ["Portuguese", "Quechua", "Guaraní"]),
  mc("medium", "What is the name of the tallest building in the world?", "Burj Khalifa", ["Shanghai Tower", "Abraj Al-Bait", "Taipei 101"]),
  mc("medium", "What is the chemical symbol for silver?", "Ag", ["Si", "Sl", "Sv"]),
  mc("medium", "How many vertebrae does an adult human spine contain?", "24", ["33", "26", "31"]),
  mc("medium", "What is the name of the fear of confined spaces?", "Claustrophobia", ["Agoraphobia", "Acrophobia", "Xenophobia"]),
  mc("medium", "Which country produces the most coffee in the world?", "Brazil", ["Colombia", "Ethiopia", "Vietnam"]),
  mc("medium", "What is the name of the longest river in Europe?", "Volga", ["Rhine", "Danube", "Thames"]),
  mc("medium", "Which European institution is widely recognized as the oldest university in continuous operation?", "University of Bologna", ["University of Oxford", "University of Cambridge", "University of Padua"]),
  mc("medium", "How many official languages does Switzerland have?", "4", ["2", "3", "5"]),
  mc("medium", "What is the most expensive spice in the world by weight?", "Saffron", ["Vanilla", "Cardamom", "Black truffle"]),
  mc("medium", "What is the name of the fear of heights?", "Acrophobia", ["Vertigo", "Agoraphobia", "Bathophobia"]),
  mc("medium", "Which country consumes the most chocolate per person?", "Switzerland", ["Belgium", "Germany", "UK"]),
  mc("medium", "What is the name of the largest library in the world?", "Library of Congress", ["British Library", "New York Public Library", "Bibliothèque nationale de France"]),
  mc("hard", "What is the name of the longest wall ever built?", "Great Wall of China", ["Hadrian's Wall", "Aurelian Wall", "Berlin Wall"]),
  mc("hard", "What is the name of the world's oldest living tree species?", "Bristlecone pine", ["Redwood", "Baobab", "Olive"]),
  mc("hard", "How many bones does an adult shark have?", "0 (cartilage only)", ["50", "100", "200"]),
  mc("hard", "What is the most translated book in history?", "The Bible", ["The Quran", "Don Quixote", "The Little Prince"]),
  mc("hard", "What is the name of the world's largest democracy?", "India", ["USA", "Indonesia", "Brazil"]),
  mc("hard", "Which country drinks the most tea per person?", "Turkey", ["China", "India", "UK"]),
  mc("hard", "What is the world's most visited museum?", "The Louvre", ["British Museum", "Metropolitan Museum", "Vatican Museums"]),
  mc("hard", "Which of these words is the longest commonly used non-technical word in the English language?", "Antidisestablishmentarianism", ["Floccinaucinihilipilification", "Incomprehensibility", "Honorificabilitudinitatibus"]),
  mc("hard", "Which country is the world's largest producer of diamonds?", "Russia", ["Botswana", "Canada", "South Africa"]),
  mc("hard", "What is the official language of Brazil?", "Portuguese", ["Spanish", "English", "French"]),
  mc("expert", "What is the name of the international treaty banning biological weapons?", "Biological Weapons Convention (1972)", ["Geneva Protocol", "Chemical Weapons Convention", "Ottawa Treaty"]),
  mc("expert", "What is the name of the most widely spoken constructed language?", "Esperanto", ["Ido", "Interlingua", "Volapük"]),
  mc("expert", "In which city is the headquarters of the International Court of Justice?", "The Hague", ["Geneva", "New York", "Brussels"]),
  mc("expert", "Which blood type is considered the rarest in the world?", "Rh-null", ["AB negative", "O negative", "A negative"]),
  mc("expert", "How many countries are members of the United Nations?", "193", ["180", "200", "175"]),
  mc("expert", "What is the name of the only country with a non-rectangular flag?", "Nepal", ["Switzerland", "Vatican City", "Cambodia"]),
  mc("expert", "In what year was the United Nations founded?", "1945", ["1944", "1948", "1919"]),
  mc("expert", "What is the name of the monetary unit used in ancient Rome?", "Denarius", ["Sesterce", "Aureus", "Obolus"]),
  mc("expert", "Which African country recognizes the most official languages at the national level?", "South Africa", ["Nigeria", "Kenya", "Ethiopia"]),
  mc("expert", "Which of these cities has the longest documented continuous settlement history?", "Jericho", ["Damascus", "Athens", "Aleppo"]),
  mc("easy", "Who wrote 'Romeo and Juliet'?", "William Shakespeare", ["Jane Austen", "Charles Dickens", "Mark Twain"]),
  mc("medium", "Which element has the chemical symbol 'Au'?", "Gold", ["Silver", "Aluminum", "Argon"]),
  mc("medium", "What is the deepest ocean trench?", "Mariana Trench", ["Tonga Trench", "Philippine Trench", "Kuril-Kamchatka Trench"]),
  mc("medium", "What year did the Berlin Wall fall?", "1989", ["1987", "1991", "1985"]),
  mc("hard", "In what century was the printing press invented by Johannes Gutenberg?", "15th century", ["14th century", "16th century", "13th century"]),
  mc("expert", "Which ancient wonder of the world is still standing today?", "Great Pyramid of Giza", ["Hanging Gardens of Babylon", "Colossus of Rhodes", "Lighthouse of Alexandria"]),
  mc("easy", "What color do you get when you mix red and blue?", "Purple", ["Orange", "Green", "Brown"]),
  mc("medium", "Who wrote 'One Hundred Years of Solitude'?", "Gabriel García Márquez", ["Jorge Luis Borges", "Isabel Allende", "Julio Cortázar"]),
  mc("medium", "What is the most spoken language in the world by native speakers?", "Mandarin Chinese", ["Spanish", "English", "Hindi"]),
  mc("hard", "Which scientist won Nobel Prizes in two different scientific fields?", "Marie Curie", ["Linus Pauling", "Albert Einstein", "Richard Feynman"]),
  mc("hard", "What is the currency of Thailand?", "Thai Baht", ["Thai Ringgit", "Thai Won", "Thai Rupee"]),
  mc("expert", "In what year was the first transatlantic telegraph cable successfully laid?", "1858", ["1845", "1872", "1881"]),
  mc("medium", "What is the smallest country in the world by land area?", "Vatican City", ["Monaco", "San Marino", "Liechtenstein"]),
  mc("hard", "In which year was the first modern Olympic Games held?", "1896", ["1900", "1892", "1888"]),
  mc("hard", "Which scientist proposed the theory of general relativity?", "Albert Einstein", ["Niels Bohr", "Max Planck", "Werner Heisenberg"]),
  mc("medium", "What is the main ingredient in traditional Japanese miso?", "Soybeans", ["Rice", "Barley", "Lentils"]),
  mc("medium", "In what country is the ancient city of Petra located?", "Jordan", ["Egypt", "Saudi Arabia", "Israel"]),
  mc("hard", "What is the only mammal capable of true powered flight?", "Bat", ["Flying squirrel", "Flying fish", "Flying lemur"]),
  mc("hard", "Who was the first person to win a Nobel Prize twice?", "Marie Curie", ["Albert Einstein", "Linus Pauling", "Frederick Sanger"]),
  mc("hard", "What is the second-most spoken language in the world by native speakers?", "Spanish", ["Hindi", "English", "Arabic"]),
  mc("expert", "In music, what term describes the simultaneous use of two or more conflicting keys or tonalities?", "Polytonality", ["Modulation", "Enharmonic", "Atonality"]),
  mc("expert", "What is the name of the small membrane-covered opening that allows sound vibrations to pass from the middle ear to the inner ear?", "Oval window", ["Eustachian tube", "Tympanum", "Stapes"]),
  mc("easy", "What color is the sky on a clear day?", "Blue", ["Green", "Yellow", "Purple"]),
  mc("medium", "What is the largest ocean on Earth?", "Pacific Ocean", ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean"]),
  mc("medium", "In which century was the Renaissance primarily centered?", "14th-17th centuries", ["10th-12th centuries", "18th-20th centuries", "11th-13th centuries"]),
  mc("hard", "Which scientist proposed the theory of continental drift?", "Alfred Wegener", ["Charles Darwin", "Marie Curie", "Isaac Newton"]),
  mc("expert", "Besides bats, which mammal is known to use echolocation for navigation and hunting?", "Dolphin", ["Hedgehog", "Manatee", "Platypus"]),
  mc("expert", "Which British mathematician is the Turing Test named after?", "Alan Turing", ["Andrew Wiles", "G.H. Hardy", "Bertrand Russell"]),
  mc("easy", "Who wrote Romeo and Juliet?", "William Shakespeare", ["Christopher Marlowe", "Ben Jonson", "John Webster"]),
  mc("medium", "Which element has the chemical symbol Au?", "Gold", ["Silver", "Aluminum", "Argon"]),
  mc("medium", "In what country is the Great Wall located?", "China", ["Japan", "Mongolia", "Korea"]),
  mc("hard", "Who was the first President of Brazil?", "Deodoro da Fonseca", ["Getúlio Vargas", "Juscelino Kubitschek", "Café Filho"]),
  mc("hard", "In physics, what does the 'G' in 'G-force' stand for?", "Gravitational", ["Galileo", "Gradient", "Gauge"]),
];
