import { mc } from "./seed";
import type { QuestionSeed } from "./seed";

export const GENERAL_SEEDS: QuestionSeed[] = [
  mc("easy", "How many sides does a hexagon have?", "6", ["5", "7", "8"]),
  mc("easy", "What colour is a ruby?", "Red", ["Blue", "Green", "Purple"]),
  mc("easy", "How many days are in a leap year?", "366", ["365", "367", "364"]),
  mc("easy", "What is the opposite of 'north' on a compass?", "South", ["East", "West", "Southwest"]),
  mc("easy", "How many months have 31 days?", "7", ["6", "8", "5"]),
  mc("easy", "What is the currency of the United Kingdom?", "Pound sterling", ["Euro", "Dollar", "Franc"]),
  mc("easy", "How many weeks are in a year?", "52", ["48", "50", "54"]),
  mc("easy", "What is the most widely spoken language in the world?", "Mandarin Chinese", ["English", "Spanish", "Hindi"]),
  mc("easy", "How many centimetres are in a metre?", "100", ["10", "1000", "50"]),
  mc("easy", "What is the capital of the world's most populous country?", "Beijing", ["New Delhi", "Jakarta", "Washington D.C."]),
  mc("easy", "What colour are emeralds?", "Green", ["Blue", "Red", "Yellow"]),
  mc("easy", "How many hours are in a day?", "24", ["12", "48", "20"]),
  mc("easy", "What is 50% of 200?", "100", ["50", "150", "25"]),
  mc("easy", "How many strings does a standard guitar have?", "6", ["4", "8", "5"]),
  mc("easy", "What is the boiling point of water in Fahrenheit?", "212°F", ["100°F", "180°F", "250°F"]),
  mc("easy", "Which planet appears as a blue dot in our solar system?", "Neptune", ["Uranus", "Earth", "Venus"]),
  mc("easy", "How many faces does a cube have?", "6", ["4", "8", "5"]),
  mc("easy", "What is the largest organ in the human body?", "Skin", ["Liver", "Brain", "Lungs"]),
  mc("easy", "What material is a pencil's writing core made of?", "Graphite", ["Lead", "Carbon", "Charcoal"]),
  mc("easy", "How many zeros are in one million?", "6", ["5", "7", "8"]),
  mc("medium", "What is the name of the longest-running Broadway show?", "The Phantom of the Opera", ["Chicago", "Cats", "Les Misérables"]),
  mc("medium", "What is the name of the phobia of spiders?", "Arachnophobia", ["Agoraphobia", "Claustrophobia", "Entomophobia"]),
  mc("medium", "Which language has the most native speakers in South America?", "Portuguese", ["Spanish", "Quechua", "Guaraní"]),
  mc("medium", "What is the name of the tallest building in the world?", "Burj Khalifa", ["Shanghai Tower", "Abraj Al-Bait", "Taipei 101"]),
  mc("medium", "What is the chemical symbol for silver?", "Ag", ["Si", "Sl", "Sv"]),
  mc("medium", "How many bones are in the human spine?", "33", ["24", "26", "31"]),
  mc("medium", "What is the name of the fear of confined spaces?", "Claustrophobia", ["Agoraphobia", "Acrophobia", "Xenophobia"]),
  mc("medium", "Which country produces the most coffee in the world?", "Brazil", ["Colombia", "Ethiopia", "Vietnam"]),
  mc("medium", "What is the name of the longest river in Europe?", "Volga", ["Rhine", "Danube", "Thames"]),
  mc("medium", "What is the name of the world's oldest university?", "University of Bologna (1088)", ["Oxford", "Harvard", "Cambridge"]),
  mc("medium", "How many official languages does Switzerland have?", "4", ["2", "3", "5"]),
  mc("medium", "What is the most expensive spice in the world by weight?", "Saffron", ["Vanilla", "Cardamom", "Black truffle"]),
  mc("medium", "What is the name of the fear of heights?", "Acrophobia", ["Vertigo", "Agoraphobia", "Bathophobia"]),
  mc("medium", "Which country consumes the most chocolate per person?", "Switzerland", ["Belgium", "Germany", "UK"]),
  mc("medium", "What is the name of the largest library in the world?", "Library of Congress", ["British Library", "New York Public Library", "Bibliothèque nationale de France"]),
  mc("hard", "What is the name of the longest wall ever built?", "Great Wall of China", ["Hadrian's Wall", "Aurelian Wall", "Berlin Wall"]),
  mc("hard", "What is the name of the world's oldest living tree species?", "Bristlecone pine", ["Redwood", "Baobab", "Olive"]),
  mc("hard", "How many bones does an adult shark have?", "0 (cartilage only)", ["50", "100", "200"]),
  mc("hard", "What is the most translated book in history?", "The Bible", ["The Quran", "Don Quixote", "The Little Prince"]),
  mc("hard", "What is the name of the world's largest democracy?", "India", ["USA", "Indonesia", "Brazil"]),
  mc("hard", "Which country drinks the most tea per person?", "Turkey", ["China", "India", "UK"]),
  mc("hard", "What is the world's most visited museum?", "The Louvre", ["British Museum", "Metropolitan Museum", "Vatican Museums"]),
  mc("hard", "What is the longest word in the English language (non-technical)?", "Pneumonoultramicroscopicsilicovolcanoconiosis", ["Antidisestablishmentarianism", "Floccinaucinihilipilification", "Supercalifragilisticexpialidocious"]),
  mc("hard", "Which country is the world's largest producer of diamonds?", "Russia", ["Botswana", "Canada", "South Africa"]),
  mc("hard", "What is the official language of Brazil?", "Portuguese", ["Spanish", "English", "French"]),
  mc("expert", "What is the name of the international treaty banning biological weapons?", "Biological Weapons Convention (1972)", ["Geneva Protocol", "Chemical Weapons Convention", "Ottawa Treaty"]),
  mc("expert", "What is the name of the most widely spoken constructed language?", "Esperanto", ["Ido", "Interlingua", "Volapük"]),
  mc("expert", "In which city is the headquarters of the International Court of Justice?", "The Hague", ["Geneva", "New York", "Brussels"]),
  mc("expert", "What is the name of the rarest blood type?", "AB negative", ["O negative", "B negative", "A negative"]),
  mc("expert", "How many countries are members of the United Nations?", "193", ["180", "200", "175"]),
  mc("expert", "What is the name of the only country with a non-rectangular flag?", "Nepal", ["Switzerland", "Vatican City", "Cambodia"]),
  mc("expert", "In what year was the United Nations founded?", "1945", ["1944", "1948", "1919"]),
  mc("expert", "What is the name of the monetary unit used in ancient Rome?", "Denarius", ["Sesterce", "Aureus", "Obolus"]),
  mc("expert", "Which country has the most official languages?", "Zimbabwe (16)", ["South Africa (11)", "Switzerland (4)", "India (22 scheduled)"]),
  mc("expert", "What is the oldest continuously inhabited city in the world?", "Damascus", ["Jericho", "Aleppo", "Athens"]),
];
