import { mc } from "./seed";
import type { QuestionSeed } from "./seed";

export const GEOGRAPHY_SEEDS: QuestionSeed[] = [
  mc("easy", "What is the capital of France?", "Paris", ["Rome", "Berlin", "Madrid"]),
  mc("easy", "What is the largest country in the world by area?", "Russia", ["Canada", "China", "USA"]),
  mc("easy", "What is the capital of Japan?", "Tokyo", ["Osaka", "Kyoto", "Hiroshima"]),
  mc("easy", "On which continent is Egypt located?", "Africa", ["Asia", "Europe", "Middle East"]),
  mc("easy", "What is the longest river in the world?", "Nile", ["Amazon", "Yangtze", "Mississippi"]),
  mc("easy", "What is the smallest country in the world?", "Vatican City", ["Monaco", "San Marino", "Liechtenstein"]),
  mc("easy", "Which ocean is the largest?", "Pacific", ["Atlantic", "Indian", "Arctic"]),
  mc("easy", "What is the capital of Australia?", "Canberra", ["Sydney", "Melbourne", "Brisbane"]),
  mc("easy", "Which country has the largest population?", "India", ["China", "USA", "Indonesia"]),
  mc("easy", "What is the capital of the United States?", "Washington D.C.", ["New York", "Los Angeles", "Chicago"]),
  mc("easy", "On which continent is Brazil located?", "South America", ["North America", "Africa", "Europe"]),
  mc("easy", "What is the capital of Germany?", "Berlin", ["Munich", "Hamburg", "Frankfurt"]),
  mc("easy", "Which desert is the largest hot desert in the world?", "Sahara", ["Arabian", "Gobi", "Kalahari"]),
  mc("easy", "What is the capital of Canada?", "Ottawa", ["Toronto", "Vancouver", "Montreal"]),
  mc("easy", "What country is the Eiffel Tower in?", "France", ["Italy", "Belgium", "Switzerland"]),
  mc("easy", "Which continent is the largest?", "Asia", ["Africa", "North America", "Europe"]),
  mc("easy", "What is the capital of Italy?", "Rome", ["Milan", "Florence", "Venice"]),
  mc("easy", "What mountain is the highest in the world?", "Mount Everest", ["K2", "Kangchenjunga", "Lhotse"]),
  mc("easy", "Which country is known as the Land of the Rising Sun?", "Japan", ["China", "South Korea", "Thailand"]),
  mc("easy", "What is the capital of Spain?", "Madrid", ["Barcelona", "Seville", "Valencia"]),
  mc("easy", "What is the capital of Brazil?", "Brasília", ["Rio de Janeiro", "São Paulo", "Salvador"]),
  mc("easy", "Which sea separates Europe from Africa?", "Mediterranean Sea", ["Red Sea", "Black Sea", "Caspian Sea"]),
  mc("easy", "What is the capital of China?", "Beijing", ["Shanghai", "Hong Kong", "Guangzhou"]),
  mc("easy", "Which river flows through Egypt?", "Nile", ["Congo", "Niger", "Zambezi"]),
  mc("easy", "What is the capital of India?", "New Delhi", ["Mumbai", "Kolkata", "Bangalore"]),
  mc("medium", "What is the capital of Argentina?", "Buenos Aires", ["Montevideo", "Santiago", "Lima"]),
  mc("medium", "Which country has the most time zones?", "France", ["Russia", "USA", "China"]),
  mc("medium", "What is the longest mountain range in the world?", "Andes", ["Himalayas", "Rockies", "Alps"]),
  mc("medium", "Which country is both in Europe and Asia?", "Turkey", ["Egypt", "Georgia", "Kazakhstan"]),
  mc("medium", "What is the capital of South Africa (executive)?", "Pretoria", ["Cape Town", "Johannesburg", "Durban"]),
  mc("medium", "What is the deepest lake in the world?", "Lake Baikal", ["Caspian Sea", "Lake Tanganyika", "Lake Superior"]),
  mc("medium", "How many countries are in Africa?", "54", ["48", "60", "44"]),
  mc("medium", "What is the capital of Egypt?", "Cairo", ["Alexandria", "Luxor", "Aswan"]),
  mc("medium", "Which country contains the largest portion of the Amazon rainforest?", "Brazil", ["Peru", "Colombia", "Venezuela"]),
  mc("medium", "Which ocean lies between Africa and Australia?", "Indian Ocean", ["Pacific", "Atlantic", "Southern"]),
  mc("medium", "What is the capital of Russia?", "Moscow", ["St. Petersburg", "Novosibirsk", "Volgograd"]),
  mc("medium", "Which country borders the most other countries?", "China", ["Russia", "Brazil", "Germany"]),
  mc("medium", "What is the world's largest island?", "Greenland", ["Australia", "New Guinea", "Borneo"]),
  mc("medium", "What is the capital of Mexico?", "Mexico City", ["Guadalajara", "Monterrey", "Cancún"]),
  mc("medium", "What is the capital of South Korea?", "Seoul", ["Busan", "Incheon", "Daegu"]),
  mc("medium", "Which country is home to the Great Barrier Reef?", "Australia", ["Indonesia", "Philippines", "Fiji"]),
  mc("medium", "What is the name of the strait separating Spain from Morocco?", "Strait of Gibraltar", ["Strait of Hormuz", "Bosphorus", "Strait of Malacca"]),
  mc("medium", "What is the capital of Nigeria?", "Abuja", ["Lagos", "Kano", "Ibadan"]),
  mc("medium", "What is the largest freshwater lake by surface area?", "Lake Superior", ["Lake Baikal", "Caspian Sea", "Lake Victoria"]),
  mc("medium", "Which country does the Sahara Desert primarily cover?", "Algeria", ["Egypt", "Libya", "Morocco"]),
  mc("medium", "What is the capital of Turkey?", "Ankara", ["Istanbul", "Izmir", "Bursa"]),
  mc("medium", "Which country has the most UNESCO World Heritage Sites?", "Italy", ["China", "Spain", "France"]),
  mc("medium", "What is the capital of Pakistan?", "Islamabad", ["Karachi", "Lahore", "Peshawar"]),
  mc("medium", "Which European country has the most islands?", "Sweden", ["Norway", "Greece", "Finland"]),
  mc("medium", "What is the name of the sea between Italy and the Balkans?", "Adriatic Sea", ["Aegean Sea", "Ionian Sea", "Tyrrhenian Sea"]),
  mc("hard", "What is the capital of Kazakhstan?", "Astana", ["Almaty", "Shymkent", "Nur-Sultan"]),
  mc("hard", "Which country has the most coastline?", "Canada", ["Norway", "Indonesia", "Russia"]),
  mc("hard", "What is the highest capital city in the world?", "Quito", ["La Paz", "Bogotá", "Addis Ababa"]),
  mc("hard", "What is the name of the deepest point in the ocean?", "Challenger Deep (Mariana Trench)", ["Puerto Rico Trench", "Java Trench", "Tonga Trench"]),
  mc("hard", "Which country is home to Angel Falls, the world's highest waterfall?", "Venezuela", ["Brazil", "Colombia", "Ecuador"]),
  mc("hard", "What is the driest place on Earth?", "Atacama Desert", ["Sahara Desert", "Death Valley", "Namib Desert"]),
  mc("hard", "What is the capital of Myanmar?", "Naypyidaw", ["Yangon", "Mandalay", "Bagan"]),
  mc("hard", "Which country has the most volcanoes?", "Indonesia", ["Japan", "USA", "Russia"]),
  mc("hard", "What is the capital of Ethiopia?", "Addis Ababa", ["Nairobi", "Khartoum", "Kampala"]),
  mc("hard", "What is the name of the body of water between Sweden and Finland?", "Gulf of Bothnia", ["Baltic Sea", "Gulf of Finland", "Kattegat"]),
  mc("hard", "Which landlocked country is the largest in the world?", "Kazakhstan", ["Mongolia", "Chad", "Niger"]),
  mc("hard", "What is the capital of Uzbekistan?", "Tashkent", ["Samarkand", "Bukhara", "Namangan"]),
  mc("hard", "What is the name of the narrow strip of land connecting North and South America?", "Isthmus of Panama", ["Strait of Magellan", "Canal Zone", "Darien Gap"]),
  mc("hard", "Which country has the world's longest land border?", "China", ["Russia", "Brazil", "USA"]),
  mc("hard", "What is the world's highest lake?", "Lake Titicaca", ["Lake Baikal", "Crater Lake", "Dead Sea"]),
  mc("expert", "What is the exact height of Mount Everest in metres?", "8,849m", ["8,800m", "9,000m", "8,500m"]),
  mc("expert", "What is the capital of Kyrgyzstan?", "Bishkek", ["Dushanbe", "Tashkent", "Almaty"]),
  mc("expert", "The Caspian Sea borders how many countries?", "5", ["4", "6", "3"]),
  mc("expert", "What is the name of the ancient trade route connecting China to Rome?", "Silk Road", ["Spice Route", "Amber Road", "Marco Polo Route"]),
  mc("expert", "What is the smallest country in Asia?", "Maldives", ["Singapore", "Bahrain", "Brunei"]),
  mc("expert", "Which African country has the most pyramids?", "Sudan", ["Egypt", "Ethiopia", "Libya"]),
  mc("expert", "What is the second tallest mountain in the world?", "K2", ["Kangchenjunga", "Lhotse", "Makalu"]),
  mc("expert", "What is the capital of Bhutan?", "Thimphu", ["Kathmandu", "Paro", "Punakha"]),
  mc("expert", "Which country has the most borders with other countries?", "China and Russia (tied at 14)", ["Brazil", "Germany", "Sudan"]),
  mc("expert", "What is the name of the world's longest river if measured from its most distant source?", "Amazon", ["Nile", "Yangtze", "Mississippi-Missouri"]),
];
