import { mc } from "./seed";
import type { QuestionSeed } from "./seed";

export const GEOGRAPHY_SEEDS: QuestionSeed[] = [
  mc("easy", "What is the capital of France?", "Paris", ["Rome", "Berlin", "Madrid"]),
  mc("easy", "What is the largest country in the world by area?", "Russia", ["Canada", "China", "USA"]),
  mc("easy", "What is the capital of Japan?", "Tokyo", ["Osaka", "Kyoto", "Hiroshima"]),
  mc("easy", "On which continent is Egypt located?", "Africa", ["Asia", "Europe", "Middle East"]),
  mc("easy", "What is the longest river in the world?", "Nile", ["Amazon", "Yangtze", "Mississippi"]),
  mc("easy", "What is the smallest country in the world?", "Vatican City", ["Monaco", "San Marino", "Liechtenstein"]),
  mc("easy", "Which ocean is the largest?", "Pacific", ["Atlantic", "Indian", "Arctic"]),
  mc("easy", "What is the capital of Australia?", "Canberra", ["Sydney", "Melbourne", "Brisbane"]),
  mc("easy", "Which country has the largest population?", "India", ["China", "USA", "Indonesia"]),
  mc("easy", "What is the capital of the United States?", "Washington D.C.", ["New York", "Los Angeles", "Chicago"]),
  mc("easy", "On which continent is Brazil located?", "South America", ["North America", "Africa", "Europe"]),
  mc("easy", "What is the capital of Germany?", "Berlin", ["Munich", "Hamburg", "Frankfurt"]),
  mc("easy", "Which desert is the largest hot desert in the world?", "Sahara", ["Arabian", "Gobi", "Kalahari"]),
  mc("easy", "What is the capital of Canada?", "Ottawa", ["Toronto", "Vancouver", "Montreal"]),
  mc("easy", "What country is the Eiffel Tower in?", "France", ["Italy", "Belgium", "Switzerland"]),
  mc("easy", "Which continent is the largest?", "Asia", ["Africa", "North America", "Europe"]),
  mc("easy", "What is the capital of Italy?", "Rome", ["Milan", "Florence", "Venice"]),
  mc("easy", "What mountain is the highest in the world?", "Mount Everest", ["K2", "Kangchenjunga", "Lhotse"]),
  mc("easy", "Which country is known as the Land of the Rising Sun?", "Japan", ["China", "South Korea", "Thailand"]),
  mc("easy", "What is the capital of Spain?", "Madrid", ["Barcelona", "Seville", "Valencia"]),
  mc("easy", "What is the capital of Brazil?", "Brasília", ["Rio de Janeiro", "São Paulo", "Salvador"]),
  mc("easy", "Which sea separates Europe from Africa?", "Mediterranean Sea", ["Red Sea", "Black Sea", "Caspian Sea"]),
  mc("easy", "What is the capital of China?", "Beijing", ["Shanghai", "Hong Kong", "Guangzhou"]),
  mc("easy", "Which river flows through Egypt?", "Nile", ["Congo", "Niger", "Zambezi"]),
  mc("easy", "What is the capital of India?", "New Delhi", ["Mumbai", "Kolkata", "Bangalore"]),
  mc("medium", "What is the capital of Argentina?", "Buenos Aires", ["Montevideo", "Santiago", "Lima"]),
  mc("medium", "Which country has the most time zones?", "France", ["Russia", "USA", "China"]),
  mc("medium", "What is the longest mountain range in the world?", "Andes", ["Himalayas", "Rockies", "Alps"]),
  mc("medium", "Which country is both in Europe and Asia?", "Turkey", ["Egypt", "Georgia", "Kazakhstan"]),
  mc("medium", "What is the capital of South Africa (executive)?", "Pretoria", ["Cape Town", "Johannesburg", "Durban"]),
  mc("medium", "What is the deepest lake in the world?", "Lake Baikal", ["Caspian Sea", "Lake Tanganyika", "Lake Superior"]),
  mc("medium", "How many countries are in Africa?", "54", ["48", "60", "44"]),
  mc("medium", "What is the capital of Egypt?", "Cairo", ["Alexandria", "Luxor", "Aswan"]),
  mc("medium", "Which country contains the largest portion of the Amazon rainforest?", "Brazil", ["Peru", "Colombia", "Venezuela"]),
  mc("medium", "Which ocean lies between Africa and Australia?", "Indian Ocean", ["Pacific", "Atlantic", "Southern"]),
  mc("medium", "What is the capital of Russia?", "Moscow", ["St. Petersburg", "Novosibirsk", "Volgograd"]),
  mc("medium", "Which country borders the most other countries?", "China", ["Russia", "Brazil", "Germany"]),
  mc("medium", "What is the world's largest island?", "Greenland", ["Australia", "New Guinea", "Borneo"]),
  mc("medium", "What is the capital of Mexico?", "Mexico City", ["Guadalajara", "Monterrey", "Cancún"]),
  mc("medium", "What is the capital of South Korea?", "Seoul", ["Busan", "Incheon", "Daegu"]),
  mc("medium", "Which country is home to the Great Barrier Reef?", "Australia", ["Indonesia", "Philippines", "Fiji"]),
  mc("medium", "What is the name of the strait separating Spain from Morocco?", "Strait of Gibraltar", ["Strait of Hormuz", "Bosphorus", "Strait of Malacca"]),
  mc("medium", "What is the capital of Nigeria?", "Abuja", ["Lagos", "Kano", "Ibadan"]),
  mc("medium", "What is the largest freshwater lake by surface area?", "Lake Superior", ["Lake Baikal", "Caspian Sea", "Lake Victoria"]),
  mc("medium", "Which country does the Sahara Desert primarily cover?", "Algeria", ["Egypt", "Libya", "Morocco"]),
  mc("medium", "What is the capital of Turkey?", "Ankara", ["Istanbul", "Izmir", "Bursa"]),
  mc("medium", "Which country has the most UNESCO World Heritage Sites?", "Italy", ["China", "Spain", "France"]),
  mc("medium", "What is the capital of Pakistan?", "Islamabad", ["Karachi", "Lahore", "Peshawar"]),
  mc("medium", "Which European country has the most islands?", "Sweden", ["Norway", "Greece", "Finland"]),
  mc("medium", "What is the name of the sea between Italy and the Balkans?", "Adriatic Sea", ["Aegean Sea", "Ionian Sea", "Tyrrhenian Sea"]),
  mc("hard", "What is the capital of Kazakhstan?", "Astana", ["Almaty", "Shymkent", "Nur-Sultan"]),
  mc("hard", "Which country has the most coastline?", "Canada", ["Norway", "Indonesia", "Russia"]),
  mc("hard", "What is the highest capital city in the world?", "Quito", ["La Paz", "Bogotá", "Addis Ababa"]),
  mc("hard", "What is the name of the deepest point in the ocean?", "Challenger Deep (Mariana Trench)", ["Puerto Rico Trench", "Java Trench", "Tonga Trench"]),
  mc("hard", "Which country is home to Angel Falls, the world's highest waterfall?", "Venezuela", ["Brazil", "Colombia", "Ecuador"]),
  mc("hard", "What is the driest place on Earth?", "Atacama Desert", ["Sahara Desert", "Death Valley", "Namib Desert"]),
  mc("hard", "What is the capital of Myanmar?", "Naypyidaw", ["Yangon", "Mandalay", "Bagan"]),
  mc("hard", "Which country has the most volcanoes?", "Indonesia", ["Japan", "USA", "Russia"]),
  mc("hard", "What is the capital of Ethiopia?", "Addis Ababa", ["Nairobi", "Khartoum", "Kampala"]),
  mc("hard", "What is the name of the body of water between Sweden and Finland?", "Gulf of Bothnia", ["Baltic Sea", "Gulf of Finland", "Kattegat"]),
  mc("hard", "Which landlocked country is the largest in the world?", "Kazakhstan", ["Mongolia", "Chad", "Niger"]),
  mc("hard", "What is the capital of Uzbekistan?", "Tashkent", ["Samarkand", "Bukhara", "Namangan"]),
  mc("hard", "What is the name of the narrow strip of land connecting North and South America?", "Isthmus of Panama", ["Strait of Magellan", "Canal Zone", "Darien Gap"]),
  mc("hard", "Which country has the world's longest land border?", "China", ["Russia", "Brazil", "USA"]),
  mc("hard", "What is the world's highest lake?", "Lake Titicaca", ["Lake Baikal", "Crater Lake", "Dead Sea"]),
  mc("expert", "What is the exact height of Mount Everest in metres?", "8,849m", ["8,800m", "9,000m", "8,500m"]),
  mc("expert", "What is the capital of Kyrgyzstan?", "Bishkek", ["Dushanbe", "Tashkent", "Almaty"]),
  mc("expert", "The Caspian Sea borders how many countries?", "5", ["4", "6", "3"]),
  mc("expert", "What is the name of the ancient trade route connecting China to Rome?", "Silk Road", ["Spice Route", "Amber Road", "Marco Polo Route"]),
  mc("expert", "What is the smallest country in Asia?", "Maldives", ["Singapore", "Bahrain", "Brunei"]),
  mc("expert", "Which African country has the most pyramids?", "Sudan", ["Egypt", "Ethiopia", "Libya"]),
  mc("expert", "What is the second tallest mountain in the world?", "K2", ["Kangchenjunga", "Lhotse", "Makalu"]),
  mc("expert", "What is the capital of Bhutan?", "Thimphu", ["Kathmandu", "Paro", "Punakha"]),
  mc("expert", "Which country has the most borders with other countries?", "China and Russia (tied at 14)", ["Brazil", "Germany", "Sudan"]),
  mc("expert", "What is the name of the world's longest river if measured from its most distant source?", "Amazon", ["Nile", "Yangtze", "Mississippi-Missouri"]),
  mc("easy", "Which continent is the largest by area?", "Asia", ["Africa", "North America", "Europe"]),
  mc("medium", "What is the smallest independent nation-state by area?", "Vatican City", ["Monaco", "Liechtenstein", "San Marino"]),
  mc("medium", "Which mountain range contains Mount Kilimanjaro?", "The Eastern Arc Mountains", ["The Atlas Mountains", "The Rwenzori Mountains", "The Drakensberg Mountains"]),
  mc("medium", "Which is the deepest ocean trench?", "Mariana Trench", ["Tonga Trench", "Philippine Trench", "Kuril-Kamchatka Trench"]),
  mc("hard", "Which African country was formerly known as Abyssinia?", "Ethiopia", ["Eritrea", "Djibouti", "Somalia"]),
  mc("hard", "Which European country is surrounded by Italy?", "San Marino", ["Vatican City", "Monaco", "Liechtenstein"]),
  mc("hard", "What is the second-largest country by area in South America?", "Peru", ["Colombia", "Chile", "Argentina"]),
  mc("expert", "Which country is home to Lake Titicaca, the highest navigable lake in the world?", "Bolivia and Peru", ["Ecuador and Colombia", "Chile and Argentina", "Peru and Ecuador"]),
  mc("easy", "Which country is known as the Land Down Under?", "Australia", ["New Zealand", "Fiji", "Papua New Guinea"]),
  mc("medium", "What is the capital of Mongolia?", "Ulaanbaatar", ["Erdenet", "Darkhan", "Choibalsan"]),
  mc("medium", "How many time zones does Russia span?", "11", ["9", "12", "13"]),
  mc("medium", "What is the smallest independent country in the world by population?", "Vatican City", ["Monaco", "San Marino", "Liechtenstein"]),
  mc("medium", "Which strait separates Spain from Morocco?", "Strait of Gibraltar", ["English Channel", "Davis Strait", "Bering Strait"]),
  mc("hard", "What is the capital of Burkina Faso?", "Ouagadougou", ["Bobo-Dioulasso", "Koudougou", "Tenkodogo"]),
  mc("hard", "Which South American country has the most time zones?", "France", ["Brazil", "Peru", "Chile"]),
  mc("expert", "Which country has the most UNESCO World Heritage Sites as of 2023?", "Italy", ["China", "Spain", "Germany"]),
  mc("easy", "Which continent is the Sahara Desert located on?", "Africa", ["Asia", "South America", "Australia"]),
  mc("medium", "Which country has the most islands?", "Sweden", ["Norway", "Finland", "Canada"]),
  mc("medium", "What is the smallest country in the world by area?", "Vatican City", ["Monaco", "San Marino", "Liechtenstein"]),
  mc("medium", "Which city is the capital of Australia?", "Canberra", ["Sydney", "Melbourne", "Brisbane"]),
  mc("hard", "What is the capital of Djibouti?", "Djibouti City", ["Arta", "Tadjourah", "Ali Sabieh"]),
  mc("hard", "Which African country is the most populous?", "Nigeria", ["Ethiopia", "Egypt", "Democratic Republic of the Congo"]),
  mc("hard", "The Dead Sea is located between which two countries?", "Israel and Jordan", ["Syria and Lebanon", "Palestine and Egypt", "Iraq and Iran"]),
  mc("expert", "Which European country has three official capital cities?", "South Africa", ["Belgium", "Netherlands", "Switzerland"]),
  mc("easy", "Which continent is the driest?", "Antarctica", ["Africa", "Australia", "South America"]),
  mc("easy", "What is the longest river in Africa?", "Nile River", ["Congo River", "Niger River", "Zambezi River"]),
  mc("medium", "What is the capital of New Zealand?", "Wellington", ["Auckland", "Christchurch", "Dunedin"]),
  mc("medium", "Which U.S. state has the highest average elevation?", "Colorado", ["Wyoming", "Utah", "Montana"]),
  mc("hard", "Which lake is the deepest in the world?", "Lake Baikal", ["Lake Tanganyika", "Crater Lake", "Lake Superior"]),
  mc("hard", "What is the highest capital city in the world by elevation?", "La Paz", ["Quito", "Bogotá", "Lhasa"]),
  mc("expert", "Which African country was formerly known as Rhodesia?", "Zimbabwe", ["Zambia", "Mozambique", "Malawi"]),
  mc("expert", "What is the world's longest-running territorial dispute?", "Kashmir dispute", ["Western Sahara conflict", "Crimea dispute", "Golan Heights dispute"]),
  mc("easy", "Which country is home to the Great Wall?", "China", ["Mongolia", "Vietnam", "Korea"]),
  mc("medium", "Which African country has the most official languages?", "South Africa", ["Nigeria", "Kenya", "Democratic Republic of Congo"]),
  mc("medium", "Which river is the longest in South America?", "Amazon River", ["Paraná River", "Orinoco River", "São Francisco River"]),
  mc("medium", "Which country is the world's largest by land area?", "Russia", ["Canada", "United States", "China"]),
  mc("hard", "Which European capital lies on both sides of the Danube River?", "Budapest", ["Vienna", "Bratislava", "Belgrade"]),
  mc("hard", "What is the second-longest river in Africa?", "Congo River", ["Niger River", "Zambezi River", "Nile River"]),
  mc("hard", "Which U.S. state has the most national parks?", "California", ["Utah", "Colorado", "Alaska"]),
  mc("easy", "How many continents are there?", "7", ["5", "6", "8"]),
  mc("medium", "The Dead Sea borders which two countries?", "Israel and Jordan", ["Israel and Palestine", "Jordan and Syria", "Israel and Lebanon"]),
  mc("medium", "Which African country was formerly called Rhodesia?", "Zimbabwe", ["Zambia", "Mozambique", "Botswana"]),
  mc("hard", "The Atacama Desert is primarily located in which country?", "Chile", ["Peru", "Bolivia", "Argentina"]),
  mc("expert", "What is the only country that borders both the Atlantic and Indian Oceans?", "South Africa", ["Mozambique", "Madagascar", "Mauritius"]),
];
