import { img, mc } from "./seed";
import type { QuestionSeed } from "./seed";

export const GEOGRAPHY_SEEDS: QuestionSeed[] = [
  mc("easy", "What is the capital of France?", "Paris", ["Lyon", "Marseille", "Nice"]),
  mc("easy", "What is the capital of Japan?", "Tokyo", ["Osaka", "Kyoto", "Yokohama"]),
  mc("easy", "What is the largest continent by area?", "Asia", ["Africa", "Europe", "North America"]),
  mc("easy", "What is the longest river in the world?", "Nile", ["Amazon", "Mississippi", "Yangtze"]),
  mc("easy", "Which ocean is the largest?", "Pacific", ["Atlantic", "Indian", "Arctic"]),
  mc("easy", "What is the capital of the United States?", "Washington, D.C.", ["New York City", "Los Angeles", "Chicago"]),
  mc("easy", "Which country is known as the Land of the Rising Sun?", "Japan", ["China", "South Korea", "Thailand"]),
  mc("easy", "What is the tallest mountain in the world?", "Mount Everest", ["K2", "Denali", "Kilimanjaro"]),
  mc("easy", "Which desert is the largest in the world?", "Antarctic Desert", ["Sahara", "Gobi", "Mojave"]),
  mc("easy", "What is the smallest country in the world by area?", "Vatican City", ["Monaco", "San Marino", "Liechtenstein"]),
  mc("medium", "Which country has the most natural lakes?", "Canada", ["Russia", "United States", "Finland"]),
  mc("medium", "What is the capital of Australia?", "Canberra", ["Sydney", "Melbourne", "Perth"]),
  mc("medium", "Which African country was never colonized by a European power?", "Ethiopia", ["Kenya", "Nigeria", "Ghana"]),
  mc("medium", "What is the capital of Canada?", "Ottawa", ["Toronto", "Vancouver", "Montreal"]),
  mc("medium", "Which sea is the saltiest body of water in the world?", "Dead Sea", ["Red Sea", "Caspian Sea", "Black Sea"]),
  mc("medium", "What is the smallest continent by area?", "Australia", ["Europe", "Antarctica", "South America"]),
  mc("medium", "Which river flows through Egypt?", "Nile", ["Tigris", "Euphrates", "Jordan"]),
  mc("medium", "What is the capital of Brazil?", "Brasília", ["Rio de Janeiro", "São Paulo", "Salvador"]),
  mc("medium", "Which country has the largest population in the world?", "India", ["China", "United States", "Indonesia"]),
  mc("medium", "What strait separates Europe and Africa at their closest point?", "Strait of Gibraltar", ["Bosporus", "Strait of Hormuz", "Bering Strait"]),
  mc("hard", "Which country has the most time zones?", "France", ["Russia", "United States", "China"]),
  mc("hard", "What is the capital of Kazakhstan?", "Astana", ["Almaty", "Bishkek", "Tashkent"]),
  mc("hard", "Which mountain range separates Europe from Asia?", "Ural Mountains", ["Alps", "Caucasus", "Carpathians"]),
  mc("hard", "What is the only country that borders both France and Spain (besides each other)?", "Andorra", ["Monaco", "Luxembourg", "Liechtenstein"]),
  mc("hard", "Which African country has three capital cities?", "South Africa", ["Nigeria", "Kenya", "Egypt"]),
  mc("hard", "What is the deepest point in the ocean called?", "Challenger Deep", ["Mariana Trench Floor", "Puerto Rico Trench", "Tonga Trench"]),
  mc("expert", "Which country has the longest coastline in the world?", "Canada", ["Indonesia", "Russia", "Australia"]),
  mc("expert", "What is the world's only landlocked country bordered by two other landlocked countries?", "Uzbekistan", ["Mongolia", "Bolivia", "Switzerland"]),
  mc("expert", "Which city is considered the world's northernmost capital city?", "Reykjavík", ["Oslo", "Helsinki", "Nuuk"]),
  mc("expert", "What was the former name of Istanbul before 1930?", "Constantinople", ["Byzantium", "Adrianople", "Ankara"]),
  img("easy", "🇯🇵", "Which country's flag is this?", "Japan", ["China", "South Korea", "Vietnam"]),
  img("easy", "🇨🇦", "Which country's flag is this?", "Canada", ["United States", "Mexico", "Australia"]),
  img("easy", "🇧🇷", "Which country's flag is this?", "Brazil", ["Argentina", "Portugal", "Mexico"]),
  img("medium", "🇰🇪", "Which country's flag is this?", "Kenya", ["Ghana", "Ethiopia", "Tanzania"]),
  img("medium", "🇳🇴", "Which country's flag is this?", "Norway", ["Sweden", "Denmark", "Iceland"]),
  img("medium", "🗽", "Which country is this famous landmark located in?", "United States", ["France", "United Kingdom", "Canada"]),
  img("medium", "🗼", "Which country is this famous landmark located in?", "France", ["Italy", "Spain", "Germany"]),
  img("hard", "🏛️", "This style of column-lined architecture originated in which ancient civilization?", "Greece", ["Rome", "Egypt", "Persia"]),
];
