import { mc } from "./seed";
import type { QuestionSeed } from "./seed";

export const HISTORY_SEEDS: QuestionSeed[] = [
  mc("easy", "Who was the first President of the United States?", "George Washington", ["Thomas Jefferson", "Abraham Lincoln", "John Adams"]),
  mc("easy", "In what year did World War II end?", "1945", ["1944", "1943", "1946"]),
  mc("easy", "Which ancient wonder was located in Egypt?", "Great Pyramid of Giza", ["Colossus of Rhodes", "Hanging Gardens", "Lighthouse of Alexandria"]),
  mc("easy", "Who was the first man to walk on the moon?", "Neil Armstrong", ["Buzz Aldrin", "Yuri Gagarin", "John Glenn"]),
  mc("easy", "In what year did World War I begin?", "1914", ["1912", "1916", "1918"]),
  mc("easy", "Which empire was Julius Caesar part of?", "Roman Empire", ["Greek Empire", "Byzantine Empire", "Ottoman Empire"]),
  mc("easy", "What wall separated East and West Berlin?", "Berlin Wall", ["Iron Curtain", "Brandenburg Gate", "Rhine Wall"]),
  mc("easy", "Who was the Egyptian queen famous for her relationship with Julius Caesar?", "Cleopatra", ["Nefertiti", "Hatshepsut", "Isis"]),
  mc("easy", "In what year did Christopher Columbus first reach the Americas?", "1492", ["1498", "1488", "1502"]),
  mc("easy", "Which country did the United States gain independence from?", "Great Britain", ["France", "Spain", "Portugal"]),
  mc("easy", "Who invented the telephone?", "Alexander Graham Bell", ["Thomas Edison", "Nikola Tesla", "Guglielmo Marconi"]),
  mc("easy", "What was the name of the ship that sank in 1912 after hitting an iceberg?", "Titanic", ["Lusitania", "Britannic", "Mauretania"]),
  mc("easy", "Who painted the Mona Lisa?", "Leonardo da Vinci", ["Michelangelo", "Raphael", "Botticelli"]),
  mc("easy", "Which country launched the first artificial satellite, Sputnik?", "Soviet Union", ["USA", "Germany", "China"]),
  mc("easy", "What ancient city was destroyed by the volcano Vesuvius?", "Pompeii", ["Herculaneum", "Rome", "Athens"]),
  mc("easy", "Who was the leader of Nazi Germany during World War II?", "Adolf Hitler", ["Joseph Stalin", "Benito Mussolini", "Francisco Franco"]),
  mc("easy", "In what year did the French Revolution begin?", "1789", ["1776", "1799", "1815"]),
  mc("easy", "What was the name of the first artificial satellite launched into space?", "Sputnik", ["Explorer 1", "Vanguard", "Luna 1"]),
  mc("easy", "Who wrote the Declaration of Independence?", "Thomas Jefferson", ["Benjamin Franklin", "John Adams", "George Washington"]),
  mc("easy", "What is the name of the famous wartime British prime minister during WWII?", "Winston Churchill", ["Neville Chamberlain", "Clement Attlee", "Anthony Eden"]),
  mc("medium", "In what year did the Berlin Wall fall?", "1989", ["1987", "1991", "1985"]),
  mc("medium", "Which country was the first to give women the right to vote?", "New Zealand", ["Australia", "Finland", "USA"]),
  mc("medium", "Who was the first female Prime Minister of the United Kingdom?", "Margaret Thatcher", ["Theresa May", "Indira Gandhi", "Angela Merkel"]),
  mc("medium", "What ancient wonder was located in Babylon?", "Hanging Gardens", ["Lighthouse of Alexandria", "Temple of Artemis", "Colossus of Rhodes"]),
  mc("medium", "What year did the United States land on the moon?", "1969", ["1967", "1971", "1965"]),
  mc("medium", "Which empire was the largest in history by land area?", "Mongol Empire", ["British Empire", "Roman Empire", "Russian Empire"]),
  mc("medium", "What event triggered the start of World War I?", "Assassination of Archduke Franz Ferdinand", ["German invasion of Poland", "Sinking of the Lusitania", "Treaty of Versailles"]),
  mc("medium", "In what year did the Cold War officially end?", "1991", ["1989", "1985", "1993"]),
  mc("medium", "Who was the first Emperor of China?", "Qin Shi Huang", ["Han Gaozu", "Kublai Khan", "Tang Taizong"]),
  mc("medium", "Which treaty ended World War I?", "Treaty of Versailles", ["Treaty of Paris", "Treaty of Ghent", "Treaty of Utrecht"]),
  mc("medium", "Who led the civil rights movement in the United States during the 1960s?", "Martin Luther King Jr.", ["Malcolm X", "Rosa Parks", "John Lewis"]),
  mc("medium", "What ancient civilization built Machu Picchu?", "Inca", ["Aztec", "Maya", "Olmec"]),
  mc("medium", "Which country was the first to industrialize?", "Great Britain", ["France", "Germany", "USA"]),
  mc("medium", "In which year did the Soviet Union dissolve?", "1991", ["1989", "1993", "1985"]),
  mc("medium", "Who was the first person to circumnavigate the globe?", "Ferdinand Magellan's crew", ["Christopher Columbus", "Vasco da Gama", "James Cook"]),
  mc("medium", "What was the name of Napoleon's final defeat?", "Battle of Waterloo", ["Battle of Trafalgar", "Battle of Leipzig", "Battle of Borodino"]),
  mc("hard", "In what year did the Magna Carta get signed?", "1215", ["1066", "1189", "1265"]),
  mc("hard", "Who was the first female Pharaoh of Egypt?", "Hatshepsut", ["Cleopatra", "Nefertiti", "Nefertari"]),
  mc("hard", "What was the name of the first permanent English settlement in America?", "Jamestown", ["Plymouth", "Roanoke", "Boston"]),
  mc("hard", "Which Chinese dynasty built the majority of the Great Wall?", "Ming Dynasty", ["Qin Dynasty", "Han Dynasty", "Tang Dynasty"]),
  mc("hard", "What year did the American Civil War end?", "1865", ["1863", "1867", "1870"]),
  mc("hard", "Who commanded the Allied forces on D-Day?", "Dwight D. Eisenhower", ["George Patton", "Bernard Montgomery", "Omar Bradley"]),
  mc("hard", "Which ancient Greek philosopher was the teacher of Alexander the Great?", "Aristotle", ["Plato", "Socrates", "Pythagoras"]),
  mc("hard", "What was the name of the Soviet space program's first human spaceflight?", "Vostok 1", ["Soyuz 1", "Mir", "Sputnik 2"]),
  mc("hard", "In which year did the Black Death reach Europe?", "1347", ["1215", "1492", "1066"]),
  mc("hard", "What was the name of the first successful powered airplane flight?", "Flyer (Kitty Hawk)", ["Spirit of St. Louis", "Wright Flyer II", "Sopwith Camel"]),
  mc("expert", "What year was the Magna Carta reissued in its most famous form?", "1225", ["1215", "1265", "1300"]),
  mc("expert", "Who was the Byzantine Emperor during the fall of Constantinople in 1453?", "Constantine XI", ["Justinian I", "Alexios I", "Basil II"]),
  mc("expert", "What was the name of the first European to reach India by sea?", "Vasco da Gama", ["Christopher Columbus", "Ferdinand Magellan", "Bartolomeu Dias"]),
  mc("expert", "Which Roman general crossed the Rubicon in 49 BC?", "Julius Caesar", ["Pompey", "Crassus", "Mark Antony"]),
  mc("expert", "What was the name of the ship Charles Darwin sailed on during his famous voyage?", "HMS Beagle", ["HMS Endeavour", "HMS Victory", "HMS Bounty"]),
  mc("expert", "In what year was the Eiffel Tower completed?", "1889", ["1885", "1900", "1876"]),
  mc("expert", "Who was the last Tsar of Russia?", "Nicholas II", ["Alexander III", "Nicholas I", "Alexander II"]),
  mc("expert", "What was the name of the famous code used by the Nazis in WWII that was cracked at Bletchley Park?", "Enigma", ["Lorenz", "Purple", "Jade"]),
  mc("expert", "Who was the first person to reach the South Pole?", "Roald Amundsen", ["Robert Falcon Scott", "Ernest Shackleton", "Richard Byrd"]),
  mc("expert", "What year did the United States enter World War II?", "1941", ["1939", "1942", "1940"]),
  mc("medium", "Which ancient wonder of the world still stands today?", "The Great Pyramid of Giza", ["The Hanging Gardens of Babylon", "The Colossus of Rhodes", "The Lighthouse of Alexandria"]),
  mc("medium", "What year did the Titanic sink?", "1912", ["1910", "1915", "1920"]),
  mc("hard", "In what year did the Byzantine Empire fall to the Ottoman Turks?", "1453", ["1389", "1521", "1683"]),
  mc("hard", "Which treaty ended the Thirty Years' War?", "The Peace of Westphalia", ["The Treaty of Utrecht", "The Peace of Paris", "The Treaty of Augsburg"]),
  mc("easy", "During which war was the Battle of Gettysburg fought?", "The American Civil War", ["The American Revolutionary War", "The War of 1812", "The Mexican-American War"]),
  mc("medium", "Which civilization built the Great Wall of China?", "Imperial China", ["Ancient Persia", "The Ottoman Empire", "Medieval Japan"]),
  mc("hard", "Who was the first Holy Roman Emperor?", "Charlemagne", ["Otto I", "Frederick Barbarossa", "Charles V"]),
  mc("hard", "Which Chinese dynasty was known for the Terracotta Army?", "The Qin Dynasty", ["The Han Dynasty", "The Ming Dynasty", "The Tang Dynasty"]),
  mc("easy", "Who was the first Emperor of Rome?", "Augustus Caesar", ["Julius Caesar", "Nero", "Caligula"]),
  mc("easy", "In what year did Christopher Columbus reach the Americas?", "1492", ["1485", "1502", "1498"]),
  mc("medium", "Which empire built Machu Picchu?", "The Inca Empire", ["The Aztec Empire", "The Maya Civilization", "The Olmec Civilization"]),
  mc("medium", "Which British monarch reigned the longest during the 19th century?", "Queen Victoria", ["King George III", "King William IV", "King Edward VII"]),
  mc("medium", "What was the primary cause of the French Revolution?", "Economic crisis and food scarcity", ["Invasion by neighboring countries", "Religious conflict with the Pope", "Excessive military spending"]),
  mc("medium", "Which civilization is credited with inventing the printing press?", "Medieval Germany (Johannes Gutenberg)", ["Ancient China", "Renaissance Italy", "Ottoman Empire"]),
  mc("hard", "The Treaty of Westphalia in 1648 primarily ended which conflict?", "The Thirty Years' War", ["The English Civil War", "The War of Spanish Succession", "The Hundred Years' War"]),
  mc("hard", "Which African nation was never colonized by a European power?", "Ethiopia", ["Botswana", "Ghana", "Kenya"]),
  mc("hard", "What was the primary purpose of the Monroe Doctrine of 1823?", "To prevent European colonization in the Americas", ["To establish U.S. trade routes to Asia", "To justify westward expansion", "To end the War of 1812"]),
  mc("hard", "In which battle did Napoleon suffer his first major defeat in Europe?", "Battle of Aspern-Essling", ["Battle of Waterloo", "Battle of Leipzig", "Battle of Borodino"]),
  mc("expert", "The Sykes-Picot Agreement of 1916 divided which region between Britain and France?", "The Middle East (Ottoman territories)", ["North Africa", "South Asia", "Central Europe"]),
  mc("expert", "Which medieval Japanese shogunate was established in 1185 after the Genpei War?", "The Kamakura shogunate", ["The Ashikaga shogunate", "The Tokugawa shogunate", "The Oda shogunate"]),
  mc("expert", "What historical event sparked the Winter War of 1939-1940?", "Soviet invasion of Finland", ["Nazi invasion of Poland", "Japanese invasion of Manchuria", "Italian invasion of Ethiopia"]),
  mc("easy", "In what year did Christopher Columbus sail to the Americas?", "1492", ["1498", "1485", "1507"]),
  mc("medium", "The Berlin Wall fell in which year?", "1989", ["1987", "1991", "1985"]),
  mc("medium", "In what year did the Titanic sink?", "1912", ["1910", "1915", "1920"]),
  mc("medium", "Which document was signed at Runnymede in 1215?", "Magna Carta", ["Treaty of Versailles", "Declaration of Independence", "Mayflower Compact"]),
  mc("medium", "Who led the Russian Revolution that overthrew the Tsar?", "Vladimir Lenin", ["Leon Trotsky", "Joseph Stalin", "Grigori Rasputin"]),
  mc("hard", "Which Pharaoh commissioned the construction of the Great Pyramid of Giza?", "Khufu", ["Khafre", "Menkaure", "Pepi II"]),
  mc("hard", "The Library of Alexandria was destroyed primarily during the reign of which Roman leader?", "Julius Caesar", ["Augustus", "Nero", "Trajan"]),
  mc("expert", "The Concordat of Worms (1122) resolved disputes between which two powers?", "The Pope and the Holy Roman Emperor", ["The King of France and the Pope", "The Holy Roman Emperor and the King of England", "The Papacy and the Venetian Republic"]),
  mc("expert", "Which ancient historian wrote the account of Cleopatra dissolving a pearl in wine?", "Pliny the Elder", ["Livy", "Tacitus", "Suetonius"]),
  mc("expert", "The Peace of Utrecht (1713) primarily concluded which war?", "The War of the Spanish Succession", ["The War of Jenkins' Ear", "The Seven Years' War", "The War of Austrian Succession"]),
  mc("easy", "Which country was ruled by Queen Victoria for most of the 19th century?", "United Kingdom", ["France", "Spain", "Netherlands"]),
  mc("medium", "The French Revolution began in which year?", "1789", ["1776", "1792", "1799"]),
  mc("hard", "Which Byzantine Emperor ordered the construction of the Hagia Sophia?", "Justinian I", ["Constantine I", "Theodosius II", "Basil II"]),
  mc("hard", "The Treaty of Westphalia in 1648 ended which conflict?", "The Thirty Years' War", ["The English Civil War", "The War of Spanish Succession", "The War of Austrian Succession"]),
  mc("hard", "The Gutenberg printing press was invented in approximately which year?", "1440", ["1420", "1460", "1480"]),
  mc("expert", "Which pharaoh commissioned the Great Temple of Abu Simbel?", "Ramesses II", ["Thutmose III", "Amenhotep III", "Seti I"]),
  mc("expert", "Which Chinese dynasty was known for the construction of the Great Wall's most famous brick sections?", "Ming Dynasty", ["Han Dynasty", "Qin Dynasty", "Tang Dynasty"]),
  mc("medium", "Which French queen was executed during the French Revolution?", "Marie Antoinette", ["Catherine de Medici", "Eleanor of Aquitaine", "Joan of Arc"]),
  mc("medium", "In which country did the Industrial Revolution begin?", "England", ["France", "Germany", "Belgium"]),
  mc("medium", "What ancient city was destroyed by Mount Vesuvius in 79 AD?", "Pompeii", ["Rome", "Athens", "Carthage"]),
  mc("hard", "Which Russian Tsar was known as 'The Great'?", "Peter I", ["Ivan IV", "Catherine II", "Alexander III"]),
  mc("hard", "What treaty ended the Thirty Years' War?", "Peace of Westphalia", ["Treaty of Utrecht", "Peace of Paris", "Treaty of Augsburg"]),
  mc("hard", "Which ancient Greek city-state defeated the Persians at Marathon?", "Athens", ["Sparta", "Corinth", "Thebes"]),
  mc("expert", "In which year did the Byzantine Empire fall to the Ottoman Turks?", "1453", ["1389", "1521", "1683"]),
  mc("expert", "Which African kingdom was known for its wealth in gold and salt during the medieval period?", "Mali Empire", ["Kingdom of Kush", "Songhai Empire", "Great Zimbabwe"]),
  mc("expert", "What was the primary cause of the Haitian Revolution?", "Slave uprising against French colonial rule", ["American intervention and invasion", "Economic recession and trade wars", "Napoleon's forced conscription"]),
  mc("easy", "Which empire built the Great Wall of China?", "Chinese", ["Mongol", "Persian", "Roman"]),
  mc("medium", "The French Revolution began in what year?", "1789", ["1776", "1804", "1815"]),
  mc("medium", "Which pharaoh commissioned the construction of the Great Pyramid of Giza?", "Khufu", ["Ramesses II", "Tutankhamun", "Menkaure"]),
  mc("medium", "The Renaissance began in which European country?", "Italy", ["France", "Spain", "Germany"]),
  mc("hard", "The Treaty of Westphalia in 1648 ended which major conflict?", "The Thirty Years' War", ["The Nine Years' War", "The War of Spanish Succession", "The English Civil War"]),
  mc("hard", "Which Mesoamerican civilization developed the first writing system in the Americas?", "The Olmec", ["The Maya", "The Aztec", "The Toltec"]),
  mc("expert", "The Haymarket Affair of 1886 occurred in which U.S. city?", "Chicago", ["New York", "Boston", "Philadelphia"]),
  mc("expert", "Which ancient Greek city-state was ruled by the Thirty Tyrants after the Peloponnesian War?", "Athens", ["Sparta", "Corinth", "Thebes"]),
];
