import { mc } from "./seed";
import type { QuestionSeed } from "./seed";

export const HISTORY_SEEDS: QuestionSeed[] = [
  mc("easy", "Who was the first President of the United States?", "George Washington", ["Thomas Jefferson", "Abraham Lincoln", "John Adams"]),
  mc("easy", "In what year did World War II end?", "1945", ["1944", "1943", "1946"]),
  mc("easy", "Which ancient wonder was located in Egypt?", "Great Pyramid of Giza", ["Colossus of Rhodes", "Hanging Gardens", "Lighthouse of Alexandria"]),
  mc("easy", "Who was the first man to walk on the moon?", "Neil Armstrong", ["Buzz Aldrin", "Yuri Gagarin", "John Glenn"]),
  mc("easy", "In what year did World War I begin?", "1914", ["1912", "1916", "1918"]),
  mc("easy", "Which empire was Julius Caesar part of?", "Roman Empire", ["Greek Empire", "Byzantine Empire", "Ottoman Empire"]),
  mc("easy", "What wall separated East and West Berlin?", "Berlin Wall", ["Iron Curtain", "Brandenburg Gate", "Rhine Wall"]),
  mc("easy", "Who was the Egyptian queen famous for her relationship with Julius Caesar?", "Cleopatra", ["Nefertiti", "Hatshepsut", "Isis"]),
  mc("easy", "In what year did Christopher Columbus first reach the Americas?", "1492", ["1498", "1488", "1502"]),
  mc("easy", "Which country did the United States gain independence from?", "Great Britain", ["France", "Spain", "Portugal"]),
  mc("easy", "Who invented the telephone?", "Alexander Graham Bell", ["Thomas Edison", "Nikola Tesla", "Guglielmo Marconi"]),
  mc("easy", "What was the name of the ship that sank in 1912 after hitting an iceberg?", "Titanic", ["Lusitania", "Britannic", "Mauretania"]),
  mc("easy", "Who painted the Mona Lisa?", "Leonardo da Vinci", ["Michelangelo", "Raphael", "Botticelli"]),
  mc("easy", "Which country launched the first artificial satellite, Sputnik?", "Soviet Union", ["USA", "Germany", "China"]),
  mc("easy", "What ancient city was destroyed by the volcano Vesuvius?", "Pompeii", ["Herculaneum", "Rome", "Athens"]),
  mc("easy", "Who was the leader of Nazi Germany during World War II?", "Adolf Hitler", ["Joseph Stalin", "Benito Mussolini", "Francisco Franco"]),
  mc("easy", "In what year did the French Revolution begin?", "1789", ["1776", "1799", "1815"]),
  mc("easy", "What was the name of the first artificial satellite launched into space?", "Sputnik", ["Explorer 1", "Vanguard", "Luna 1"]),
  mc("easy", "Who wrote the Declaration of Independence?", "Thomas Jefferson", ["Benjamin Franklin", "John Adams", "George Washington"]),
  mc("easy", "What is the name of the famous wartime British prime minister during WWII?", "Winston Churchill", ["Neville Chamberlain", "Clement Attlee", "Anthony Eden"]),
  mc("medium", "In what year did the Berlin Wall fall?", "1989", ["1987", "1991", "1985"]),
  mc("medium", "Which country was the first to give women the right to vote?", "New Zealand", ["Australia", "Finland", "USA"]),
  mc("medium", "Who was the first female Prime Minister of the United Kingdom?", "Margaret Thatcher", ["Theresa May", "Indira Gandhi", "Angela Merkel"]),
  mc("medium", "What ancient wonder was located in Babylon?", "Hanging Gardens", ["Lighthouse of Alexandria", "Temple of Artemis", "Colossus of Rhodes"]),
  mc("medium", "What year did the United States land on the moon?", "1969", ["1967", "1971", "1965"]),
  mc("medium", "Which empire was the largest in history by land area?", "Mongol Empire", ["British Empire", "Roman Empire", "Russian Empire"]),
  mc("medium", "What event triggered the start of World War I?", "Assassination of Archduke Franz Ferdinand", ["German invasion of Poland", "Sinking of the Lusitania", "Treaty of Versailles"]),
  mc("medium", "In what year did the Cold War officially end?", "1991", ["1989", "1985", "1993"]),
  mc("medium", "Who was the first Emperor of China?", "Qin Shi Huang", ["Han Gaozu", "Kublai Khan", "Tang Taizong"]),
  mc("medium", "Which treaty ended World War I?", "Treaty of Versailles", ["Treaty of Paris", "Treaty of Ghent", "Treaty of Utrecht"]),
  mc("medium", "Who led the civil rights movement in the United States during the 1960s?", "Martin Luther King Jr.", ["Malcolm X", "Rosa Parks", "John Lewis"]),
  mc("medium", "What ancient civilization built Machu Picchu?", "Inca", ["Aztec", "Maya", "Olmec"]),
  mc("medium", "Which country was the first to industrialize?", "Great Britain", ["France", "Germany", "USA"]),
  mc("medium", "In which year did the Soviet Union dissolve?", "1991", ["1989", "1993", "1985"]),
  mc("medium", "Who was the first person to circumnavigate the globe?", "Ferdinand Magellan's crew", ["Christopher Columbus", "Vasco da Gama", "James Cook"]),
  mc("medium", "What was the name of Napoleon's final defeat?", "Battle of Waterloo", ["Battle of Trafalgar", "Battle of Leipzig", "Battle of Borodino"]),
  mc("hard", "In what year did the Magna Carta get signed?", "1215", ["1066", "1189", "1265"]),
  mc("hard", "Who was the first female Pharaoh of Egypt?", "Hatshepsut", ["Cleopatra", "Nefertiti", "Nefertari"]),
  mc("hard", "What was the name of the first permanent English settlement in America?", "Jamestown", ["Plymouth", "Roanoke", "Boston"]),
  mc("hard", "Which Chinese dynasty built the majority of the Great Wall?", "Ming Dynasty", ["Qin Dynasty", "Han Dynasty", "Tang Dynasty"]),
  mc("hard", "What year did the American Civil War end?", "1865", ["1863", "1867", "1870"]),
  mc("hard", "Who commanded the Allied forces on D-Day?", "Dwight D. Eisenhower", ["George Patton", "Bernard Montgomery", "Omar Bradley"]),
  mc("hard", "Which ancient Greek philosopher was the teacher of Alexander the Great?", "Aristotle", ["Plato", "Socrates", "Pythagoras"]),
  mc("hard", "What was the name of the Soviet space program's first human spaceflight?", "Vostok 1", ["Soyuz 1", "Mir", "Sputnik 2"]),
  mc("hard", "In which year did the Black Death reach Europe?", "1347", ["1215", "1492", "1066"]),
  mc("hard", "What was the name of the first successful powered airplane flight?", "Flyer (Kitty Hawk)", ["Spirit of St. Louis", "Wright Flyer II", "Sopwith Camel"]),
  mc("expert", "What year was the Magna Carta reissued in its most famous form?", "1225", ["1215", "1265", "1300"]),
  mc("expert", "Who was the Byzantine Emperor during the fall of Constantinople in 1453?", "Constantine XI", ["Justinian I", "Alexios I", "Basil II"]),
  mc("expert", "What was the name of the first European to reach India by sea?", "Vasco da Gama", ["Christopher Columbus", "Ferdinand Magellan", "Bartolomeu Dias"]),
  mc("expert", "Which Roman general crossed the Rubicon in 49 BC?", "Julius Caesar", ["Pompey", "Crassus", "Mark Antony"]),
  mc("expert", "What was the name of the ship Charles Darwin sailed on during his famous voyage?", "HMS Beagle", ["HMS Endeavour", "HMS Victory", "HMS Bounty"]),
  mc("expert", "In what year was the Eiffel Tower completed?", "1889", ["1885", "1900", "1876"]),
  mc("expert", "Who was the last Tsar of Russia?", "Nicholas II", ["Alexander III", "Nicholas I", "Alexander II"]),
  mc("expert", "What was the name of the famous code used by the Nazis in WWII that was cracked at Bletchley Park?", "Enigma", ["Lorenz", "Purple", "Jade"]),
  mc("expert", "Who was the first person to reach the South Pole?", "Roald Amundsen", ["Robert Falcon Scott", "Ernest Shackleton", "Richard Byrd"]),
  mc("expert", "What year did the United States enter World War II?", "1941", ["1939", "1942", "1940"]),
  mc("medium", "Which ancient wonder of the world still stands today?", "The Great Pyramid of Giza", ["The Hanging Gardens of Babylon", "The Colossus of Rhodes", "The Lighthouse of Alexandria"]),
  mc("medium", "What year did the Titanic sink?", "1912", ["1910", "1915", "1920"]),
  mc("hard", "In what year did the Byzantine Empire fall to the Ottoman Turks?", "1453", ["1389", "1521", "1683"]),
  mc("hard", "Which treaty ended the Thirty Years' War?", "The Peace of Westphalia", ["The Treaty of Utrecht", "The Peace of Paris", "The Treaty of Augsburg"]),
  mc("easy", "During which war was the Battle of Gettysburg fought?", "The American Civil War", ["The American Revolutionary War", "The War of 1812", "The Mexican-American War"]),
  mc("medium", "Which civilization built the Great Wall of China?", "Imperial China", ["Ancient Persia", "The Ottoman Empire", "Medieval Japan"]),
  mc("hard", "Who was the first Holy Roman Emperor?", "Charlemagne", ["Otto I", "Frederick Barbarossa", "Charles V"]),
  mc("hard", "Which Chinese dynasty was known for the Terracotta Army?", "The Qin Dynasty", ["The Han Dynasty", "The Ming Dynasty", "The Tang Dynasty"]),
  mc("easy", "Who was the first Emperor of Rome?", "Augustus Caesar", ["Julius Caesar", "Nero", "Caligula"]),
];
