import { mc } from "./seed";
import type { QuestionSeed } from "./seed";

export const HISTORY_SEEDS: QuestionSeed[] = [
  mc("easy", "Who was the first President of the United States?", "George Washington", ["Thomas Jefferson", "John Adams", "Abraham Lincoln"]),
  mc("easy", "In what year did World War II end?", "1945", ["1943", "1939", "1950"]),
  mc("easy", "Which ancient civilization built the pyramids of Giza?", "Egyptians", ["Romans", "Greeks", "Mayans"]),
  mc("easy", "Who wrote the Declaration of Independence?", "Thomas Jefferson", ["Benjamin Franklin", "George Washington", "John Hancock"]),
  mc("easy", "What wall divided Berlin during the Cold War?", "Berlin Wall", ["Great Wall", "Iron Curtain Wall", "Western Wall"]),
  mc("easy", "Which ship famously sank in 1912 after hitting an iceberg?", "Titanic", ["Lusitania", "Britannic", "Olympic"]),
  mc("easy", "Who was the British Prime Minister during most of World War II?", "Winston Churchill", ["Neville Chamberlain", "Tony Blair", "Margaret Thatcher"]),
  mc("easy", "What ancient wonder of the world still stands today?", "Great Pyramid of Giza", ["Hanging Gardens of Babylon", "Colossus of Rhodes", "Lighthouse of Alexandria"]),
  mc("easy", "In what year did Christopher Columbus reach the Americas?", "1492", ["1500", "1480", "1510"]),
  mc("easy", "Which empire was ruled by Julius Caesar?", "Roman Empire", ["Greek Empire", "Persian Empire", "Egyptian Empire"]),
  mc("medium", "Which country gifted the Statue of Liberty to the United States?", "France", ["United Kingdom", "Spain", "Italy"]),
  mc("medium", "Who was the first man to walk on the moon?", "Neil Armstrong", ["Buzz Aldrin", "Yuri Gagarin", "John Glenn"]),
  mc("medium", "What was the name of the period of cultural rebirth following the Middle Ages?", "The Renaissance", ["The Enlightenment", "The Reformation", "The Industrial Revolution"]),
  mc("medium", "Which queen ruled England during the defeat of the Spanish Armada?", "Elizabeth I", ["Mary I", "Victoria", "Anne"]),
  mc("medium", "What event triggered the start of World War I?", "Assassination of Archduke Franz Ferdinand", ["Invasion of Poland", "Sinking of the Lusitania", "Treaty of Versailles"]),
  mc("medium", "Which U.S. president led the country through the Civil War?", "Abraham Lincoln", ["Andrew Johnson", "Ulysses S. Grant", "James Buchanan"]),
  mc("medium", "What was the name of the trade network connecting Europe and Asia for centuries?", "Silk Road", ["Spice Route", "Amber Road", "Trans-Saharan Route"]),
  mc("medium", "Who painted the ceiling of the Sistine Chapel?", "Michelangelo", ["Leonardo da Vinci", "Raphael", "Donatello"]),
  mc("medium", "Which country was the first to grant women the right to vote nationally?", "New Zealand", ["United States", "United Kingdom", "France"]),
  mc("medium", "What was the name of the ship the Pilgrims sailed to America on in 1620?", "Mayflower", ["Santa Maria", "Discovery", "Endeavour"]),
  mc("hard", "Which treaty officially ended World War I?", "Treaty of Versailles", ["Treaty of Paris", "Treaty of Ghent", "Treaty of Tordesillas"]),
  mc("hard", "Who was the last Tsar of Russia?", "Nicholas II", ["Alexander III", "Peter the Great", "Ivan the Terrible"]),
  mc("hard", "Which civilization is credited with inventing the wheel?", "Sumerians", ["Egyptians", "Chinese", "Romans"]),
  mc("hard", "What was the name of the global pandemic that struck in 1918?", "Spanish Flu", ["Bubonic Plague", "Asian Flu", "Smallpox Epidemic"]),
  mc("hard", "Which dynasty began construction of the Great Wall of China?", "Qin Dynasty", ["Ming Dynasty", "Tang Dynasty", "Han Dynasty"]),
  mc("hard", "Who was the first Emperor of Rome?", "Augustus", ["Julius Caesar", "Nero", "Caligula"]),
  mc("expert", "What was the name of the policy of appeasing Hitler before WWII, associated with Neville Chamberlain?", "Appeasement", ["Containment", "Détente", "Isolationism"]),
  mc("expert", "Which battle is considered the turning point of the American Civil War?", "Battle of Gettysburg", ["Battle of Antietam", "Battle of Bull Run", "Battle of Shiloh"]),
  mc("expert", "What was the name of the secret American project to develop the atomic bomb?", "Manhattan Project", ["Operation Overlord", "Operation Paperclip", "Trinity Project"]),
  mc("expert", "Who was the Carthaginian general who famously crossed the Alps with elephants?", "Hannibal", ["Scipio Africanus", "Hamilcar Barca", "Hasdrubal"]),
];
