import { mc } from "./seed";
import type { QuestionSeed } from "./seed";

export const LOGIC_SEEDS: QuestionSeed[] = [
  mc("easy", "If all dogs are animals and Rex is a dog, what is Rex?", "An animal", ["A dog only", "Not an animal", "Cannot be determined"]),
  mc("easy", "What comes next: 2, 4, 6, 8, __?", "10", ["9", "12", "11"]),
  mc("easy", "If you have 3 apples and give away 1, how many do you have?", "2", ["3", "1", "4"]),
  mc("easy", "What comes next: A, B, C, D, __?", "E", ["F", "G", "Z"]),
  mc("easy", "If today is Monday, what day is the day after tomorrow?", "Wednesday", ["Tuesday", "Thursday", "Sunday"]),
  mc("easy", "Which number is the odd one out: 2, 4, 6, 7, 8?", "7", ["2", "6", "8"]),
  mc("easy", "If a clock shows 3:00, what angle do the hands make?", "90 degrees", ["45 degrees", "180 degrees", "60 degrees"]),
  mc("easy", "What comes next: 1, 3, 5, 7, __?", "9", ["8", "10", "11"]),
  mc("easy", "If you flip a fair coin, what is the chance of getting heads?", "50%", ["25%", "75%", "100%"]),
  mc("easy", "Which shape has 3 sides?", "Triangle", ["Square", "Pentagon", "Hexagon"]),
  mc("easy", "What comes next: Monday, Tuesday, Wednesday, __?", "Thursday", ["Friday", "Tuesday", "Sunday"]),
  mc("easy", "If a train leaves at 9am and arrives at 11am, how long was the journey?", "2 hours", ["1 hour", "3 hours", "4 hours"]),
  mc("easy", "What number is halfway between 10 and 20?", "15", ["12", "18", "14"]),
  mc("easy", "If Sarah is taller than Tom, and Tom is taller than Amy, who is shortest?", "Amy", ["Tom", "Sarah", "Cannot be determined"]),
  mc("easy", "What comes next: 10, 20, 30, 40, __?", "50", ["45", "60", "55"]),
  mc("medium", "A bat and a ball cost $1.10 in total. The bat costs $1.00 more than the ball. How much does the ball cost?", "5 cents", ["10 cents", "1 cent", "15 cents"]),
  mc("medium", "If it takes 5 machines 5 minutes to make 5 widgets, how long for 100 machines to make 100 widgets?", "5 minutes", ["100 minutes", "10 minutes", "50 minutes"]),
  mc("medium", "What comes next: 1, 1, 2, 3, 5, 8, __?", "13", ["11", "12", "16"]),
  mc("medium", "A man builds a house with 4 walls, each facing south. A bear walks by. What colour is the bear?", "White (polar bear)", ["Brown", "Black", "Cannot be determined"]),
  mc("medium", "You have a 3-gallon jug and a 5-gallon jug with no markings. Which sequence of steps will measure exactly 4 gallons in the 5-gallon jug?", "Fill the 3-gallon jug, pour it into the 5-gallon jug, fill the 3-gallon jug again, and pour from it into the 5-gallon jug until full (leaving 1 gallon in the 3-gallon jug). Empty the 5-gallon jug, pour the 1 gallon from the 3-gallon jug into the 5-gallon jug, fill the 3-gallon jug again, and pour it into the 5-gallon jug (resulting in exactly 4 gallons)", ["Fill the 5-gallon jug and remove 1 gallon by eye", "Fill the 3-gallon jug and the 5-gallon jug, then combine them", "It is impossible to measure exactly 4 gallons with these two jugs"]),
  mc("medium", "What comes next: 2, 6, 12, 20, 30, __?", "42", ["36", "40", "44"]),
  mc("medium", "In a room of 23 people, what is the approximate probability two share a birthday?", "50%", ["5%", "25%", "75%"]),
  mc("medium", "If all Bloops are Razzies and all Razzies are Lazzies, are all Bloops Lazzies?", "Yes", ["No", "Sometimes", "Cannot be determined"]),
  mc("medium", "What is the next number in this sequence: 3, 9, 27, 81, ?", "243", ["189", "162", "324"]),
  mc("medium", "You have two ropes that each take 60 minutes to burn. How do you measure 45 minutes?", "Light rope 1 from both ends and rope 2 from one end; when rope 1 is done, light rope 2's other end", ["Light both from one end after 15 minutes", "Cut one rope in half", "Cannot be done"]),
  mc("hard", "What is the missing number: 2, 3, 5, 7, 11, 13, __?", "17", ["15", "14", "16"]),
  mc("hard", "Three friends split a $30 hotel bill, paying $10 each. The manager returns $5, but the bellboy keeps $2. Each person gets $1 back, paying $9 each, totalling $27 + $2 = $29. Where is the missing dollar?", "There is no missing dollar — $27 paid minus $2 kept = $25 for the room, plus $3 returned = $28 ✓", ["The bellboy took it", "The manager kept it", "Accounting error"]),
  mc("hard", "You have 12 balls, one is heavier. With 3 weighings on a balance scale, can you find it?", "Yes", ["No", "Only with 4 weighings", "Only if you know which half it's in"]),
  mc("hard", "What comes next: 0, 1, 4, 9, 16, 25, __?", "36", ["30", "49", "32"]),
  mc("hard", "A snail is at the bottom of a 10-foot well. Each day it climbs 3 feet, each night it slides 2 feet. How many days to escape?", "8 days", ["10 days", "5 days", "7 days"]),
  mc("hard", "If you fold a standard sheet of paper (0.1 millimeter thick) in half 42 times, approximately how thick would the resulting stack be?", "Approximately 440 million kilometers (well beyond the Moon)", ["Approximately 240,000 kilometers (roughly the Moon's distance)", "Approximately 8,848 meters (Mount Everest's height)", "Approximately 42 centimeters"]),
  mc("hard", "What is the next number in the sequence: 1, 8, 27, 64, 125, __?", "216", ["196", "225", "243"]),
  mc("hard", "A clock loses 10 minutes every hour. If it shows the correct time now, when will it next show the correct time?", "After 72 hours", ["After 12 hours", "After 24 hours", "After 6 hours"]),
  mc("hard", "100 people are in a line. Alternate people are removed starting from person 1. This repeats. Who is last?", "Person 64", ["Person 50", "Person 100", "Person 72"]),
  mc("hard", "How many squares are on a standard 8×8 chessboard in total?", "204", ["64", "128", "196"]),
  mc("expert", "What is the smallest number divisible by all integers from 1 to 10?", "2520", ["1000", "3628800", "5040"]),
  mc("expert", "The Monty Hall problem: switching doors after a reveal gives what probability of winning?", "2/3", ["1/2", "1/3", "3/4"]),
  mc("expert", "In logic, what is the name for a statement that is always false?", "Contradiction", ["Tautology", "Contingency", "Paradox"]),
  mc("expert", "If you have an infinite number of mathematicians and an infinite hotel, can you always fit more guests?", "Yes (Hilbert's Hotel paradox)", ["No", "Only if you move some out", "Only with finite guests"]),
  mc("expert", "What is the maximum number of moves in a game of Towers of Hanoi with 10 discs?", "1023", ["512", "2048", "1024"]),
  mc("expert", "A liar always lies, a truth-teller always tells the truth. You meet one and ask 'Are you a liar?' What do they say?", "Both say 'No'", ["Liar says Yes, truth-teller says No", "Liar says No, truth-teller says Yes", "You can't determine"]),
  mc("expert", "What is the halting problem in computer science?", "It's undecidable whether a program will halt or run forever", ["Programs always terminate if well-written", "A method to stop infinite loops", "A way to measure algorithm efficiency"]),
  mc("expert", "In a group of 30 people, what is the probability that at least two share a birthday?", "About 70%", ["About 30%", "About 50%", "About 90%"]),
  mc("expert", "What is the name of the famous paradox: 'This statement is false'?", "The Liar Paradox", ["Russell's Paradox", "Zeno's Paradox", "The Barber Paradox"]),
  mc("expert", "How many handshakes occur when 10 people each shake hands with every other person once?", "45", ["90", "100", "50"]),
  mc("easy", "If all roses are flowers and all flowers are plants, are all roses plants?", "Yes", ["No", "Only sometimes", "Cannot be determined"]),
  mc("easy", "What is the logical opposite of 'all cats are mammals'?", "Some cats are not mammals", ["No cats are mammals", "All mammals are cats", "Some mammals are not cats"]),
  mc("easy", "If today is Monday, what day will it be in 7 days?", "Monday", ["Tuesday", "Sunday", "Wednesday"]),
  mc("medium", "In a group of 100 people, 60 like coffee and 50 like tea. What is the minimum number who like both?", "10", ["0", "50", "110"]),
  mc("medium", "A person born in May cannot be the child of someone born in April if what logical principle applies?", "Biological parenthood requires gestation", ["Calendar months must be sequential", "Birth months determine genetics", "People age backward in logic puzzles"]),
  mc("medium", "If P implies Q, and Q is false, what can we conclude about P?", "P must be false", ["P must be true", "P could be either true or false", "Q must be true"]),
  mc("medium", "What is the flaw in this argument: 'All birds fly. Penguins are birds. Therefore, penguins fly.'?", "The first premise is factually false", ["The conclusion doesn't follow logically", "Penguins are not actually birds", "The argument has no logical flaw"]),
  mc("medium", "In formal logic, what is a statement that is true in all possible interpretations called?", "Tautology", ["Paradox", "Fallacy", "Contrapositive"]),
  mc("hard", "Which logical fallacy involves assuming the conclusion is true in order to prove the conclusion?", "Begging the question", ["Straw man", "Ad hominem", "False dilemma"]),
  mc("hard", "If exactly 3 of these 4 statements are true, which is most likely false? (1) Logic is rational (2) All paradoxes confuse us (3) This sentence is true (4) Logic governs language", "All paradoxes confuse us", ["Logic is rational", "This sentence is true", "Logic governs language"]),
  mc("hard", "In modal logic, what is the difference between 'possibly true' and 'necessarily true'?", "Necessarily true holds in all possible worlds; possibly true holds in at least one", ["Necessarily true means mathematically proven; possibly true means uncertain", "They mean the same thing", "Possibly true is stronger than necessarily true"]),
  mc("hard", "What is the name of the logical principle stating that something cannot both be and not be in the same respect at the same time?", "Law of non-contradiction", ["Law of excluded middle", "Law of identity", "Principle of bivalence"]),
  mc("expert", "In the liar's paradox ('This statement is false'), what meta-logical property makes it unresolvable in classical logic?", "Self-reference without a truth value", ["Temporal ambiguity", "Quantifier scope confusion", "Failure of modus ponens"]),
  mc("expert", "Which logical system allows for truth values beyond just true and false?", "Fuzzy logic", ["Boolean algebra", "Propositional logic", "First-order logic"]),
  mc("expert", "What does Gödel's incompleteness theorem prove about sufficiently complex formal systems?", "They cannot be both complete and consistent", ["They must contain contradictions", "They cannot be proven true", "They require infinite axioms"]),
  mc("easy", "Which of these is NOT a logical fallacy?", "Valid deductive reasoning from true premises", ["Ad hominem attack", "Appeal to authority", "Begging the question"]),
  mc("easy", "In formal logic, what is the name of a statement that is always true?", "Tautology", ["Paradox", "Contradiction", "Antonym"]),
  mc("easy", "If all cats are animals and Fluffy is a cat, what can we logically conclude?", "Fluffy is an animal", ["Fluffy is the only cat", "All animals are cats", "Fluffy is not an animal"]),
  mc("medium", "What is the logical fallacy of assuming that because A causes B, then B must also cause A?", "Converse error (or inverse reasoning)", ["Affirming the consequent", "Post hoc ergo propter hoc", "Begging the question"]),
  mc("medium", "In symbolic logic, what does the symbol ∧ represent?", "Logical AND", ["Logical OR", "Logical NOT", "Logical XOR"]),
  mc("medium", "Which principle states that something cannot be both true and false at the same time?", "Law of Non-Contradiction", ["Law of Excluded Middle", "Law of Identity", "Law of Sufficient Reason"]),
  mc("medium", "What is a syllogism with two premises where the conclusion doesn't follow called?", "Fallacious syllogism", ["Valid syllogism", "Sound argument", "Deductive proof"]),
  mc("medium", "If the statement 'All dogs bark' is false, what must be true?", "At least one dog does not bark", ["No dogs bark", "Some dogs bark", "Dogs never bark"]),
  mc("hard", "What logical problem is represented by 'This sentence is false'?", "The Liar's Paradox", ["Russell's Paradox", "The Ship of Theseus", "Zeno's Paradox"]),
  mc("hard", "In predicate logic, what is the scope ambiguity problem when quantifiers overlap called?", "Quantifier scope ambiguity", ["Modal collapse", "Reference indeterminacy", "Semantic satiation"]),
  mc("hard", "Which logician developed the system of Boolean algebra used in modern computing?", "George Boole", ["Aristotle", "Gottlob Frege", "David Hume"]),
  mc("hard", "In formal logic, a statement that is contingent means it is:", "True in some possible worlds and false in others", ["True in all possible worlds", "False in all possible worlds", "Meaningless"]),
  mc("expert", "What does Gödel's Incompleteness Theorem prove about consistent formal systems?", "They cannot prove all true statements within the system", ["They are always inconsistent", "They are circular by nature", "They require infinite axioms"]),
  mc("expert", "In modal logic, which axiom schema states that if something is possibly necessary, then it must be necessary? (Formally: ◇□P → □P)", "S5", ["S4", "T", "K"]),
  mc("expert", "What is the relationship between intuitionistic logic and the Law of Excluded Middle?", "Intuitionistic logic rejects the Law of Excluded Middle", ["Intuitionistic logic strengthens it", "They are identical systems", "The law is irrelevant to intuitionistic logic"]),
  mc("easy", "In formal logic, what is the name for a statement that is always true?", "Tautology", ["Paradox", "Fallacy", "Contradiction"]),
  mc("easy", "If Statement A is true and Statement B is false, what is the truth value of 'A AND B'?", "False", ["True", "Unknown", "Both true and false"]),
  mc("medium", "Which logical fallacy occurs when you assume that because two things often occur together, one must cause the other?", "Correlation implies causation", ["Begging the question", "Appeal to authority", "Straw man"]),
  mc("medium", "In a truth table for 'A OR B', how many rows result in a true outcome?", "3", ["1", "2", "4"]),
  mc("medium", "What is the contrapositive of 'If it rains, the ground is wet'?", "If the ground is not wet, it does not rain", ["If the ground is wet, it rains", "If it doesn't rain, the ground is dry", "If the ground is not wet, it rains"]),
  mc("medium", "Which of these is an example of circular reasoning?", "The Bible is true because it says so in the Bible", ["Cats have four legs because they are mammals", "He is guilty because evidence proves it", "Plants need sunlight to survive"]),
  mc("medium", "In De Morgan's Laws, the negation of 'A AND B' is equivalent to what?", "NOT A OR NOT B", ["NOT A AND NOT B", "A OR B", "A AND NOT B"]),
  mc("hard", "What is the name of the logical puzzle where you must determine who owns the fish from a series of constraints?", "Einstein's Riddle", ["Tower of Hanoi", "Sorites Paradox", "Liar's Paradox"]),
  mc("hard", "In formal logic, what term describes an argument that is valid but has at least one false premise?", "Unsound", ["Invalid", "Illogical", "Inconclusive"]),
  mc("hard", "Which of the following is a self-referential statement that creates a logical paradox?", "This statement is false", ["This sentence contains five words", "All statements are either true or false", "Some statements refer to themselves"]),
  mc("hard", "In propositional logic, what is the only condition under which an implication 'If P then Q' is false?", "P is true and Q is false", ["P is false and Q is true", "Both P and Q are false", "P and Q have different truth values"]),
  mc("expert", "In modal logic, what is the standard technical term for a proposition that is true in all possible worlds?", "Necessary", ["Contingent", "Possible", "Universal"]),
  mc("expert", "Which logical system allows propositions to have truth values other than strictly true or false?", "Fuzzy logic", ["Classical logic", "Boolean algebra", "Symbolic logic"]),
  mc("expert", "In Gödel's Incompleteness Theorems, what cannot be proven within a consistent formal system?", "The consistency of the system itself", ["The existence of infinity", "The law of non-contradiction", "The validity of logical operators"]),
  mc("easy", "If all roses are flowers and some flowers fade quickly, what can we conclude?", "Some roses might fade quickly", ["All roses fade quickly", "No roses fade quickly", "Flowers are a type of rose"]),
  mc("easy", "Which logical operator returns true only when both inputs are true?", "AND", ["OR", "NOT", "XOR"]),
];
