import { mc } from "./seed";
import type { QuestionSeed } from "./seed";

export const LOGIC_SEEDS: QuestionSeed[] = [
  mc("easy", "If all dogs are animals and Rex is a dog, what is Rex?", "An animal", ["A dog only", "Not an animal", "Cannot be determined"]),
  mc("easy", "What comes next: 2, 4, 6, 8, __?", "10", ["9", "12", "11"]),
  mc("easy", "If you have 3 apples and give away 1, how many do you have?", "2", ["3", "1", "4"]),
  mc("easy", "What comes next: A, B, C, D, __?", "E", ["F", "G", "Z"]),
  mc("easy", "If today is Monday, what day is the day after tomorrow?", "Wednesday", ["Tuesday", "Thursday", "Sunday"]),
  mc("easy", "Which number is the odd one out: 2, 4, 6, 7, 8?", "7", ["2", "6", "8"]),
  mc("easy", "If a clock shows 3:00, what angle do the hands make?", "90 degrees", ["45 degrees", "180 degrees", "60 degrees"]),
  mc("easy", "What comes next: 1, 3, 5, 7, __?", "9", ["8", "10", "11"]),
  mc("easy", "If you flip a fair coin, what is the chance of getting heads?", "50%", ["25%", "75%", "100%"]),
  mc("easy", "Which shape has 3 sides?", "Triangle", ["Square", "Pentagon", "Hexagon"]),
  mc("easy", "What comes next: Monday, Tuesday, Wednesday, __?", "Thursday", ["Friday", "Tuesday", "Sunday"]),
  mc("easy", "If a train leaves at 9am and arrives at 11am, how long was the journey?", "2 hours", ["1 hour", "3 hours", "4 hours"]),
  mc("easy", "What number is halfway between 10 and 20?", "15", ["12", "18", "14"]),
  mc("easy", "If Sarah is taller than Tom, and Tom is taller than Amy, who is shortest?", "Amy", ["Tom", "Sarah", "Cannot be determined"]),
  mc("easy", "What comes next: 10, 20, 30, 40, __?", "50", ["45", "60", "55"]),
  mc("medium", "A bat and a ball cost $1.10 in total. The bat costs $1.00 more than the ball. How much does the ball cost?", "5 cents", ["10 cents", "1 cent", "15 cents"]),
  mc("medium", "If it takes 5 machines 5 minutes to make 5 widgets, how long for 100 machines to make 100 widgets?", "5 minutes", ["100 minutes", "10 minutes", "50 minutes"]),
  mc("medium", "What comes next: 1, 1, 2, 3, 5, 8, __?", "13", ["11", "12", "16"]),
  mc("medium", "A man builds a house with 4 walls, each facing south. A bear walks by. What colour is the bear?", "White (polar bear)", ["Brown", "Black", "Cannot be determined"]),
  mc("medium", "If you have a 3-gallon jug and a 5-gallon jug, how do you measure exactly 4 gallons?", "Fill 5, pour into 3, empty 3, pour remainder into 3, fill 5 again, top up the 3", ["Fill the 3 twice and add", "Fill 5 and take out 1", "Cannot be done"]),
  mc("medium", "What comes next: 2, 6, 12, 20, 30, __?", "42", ["36", "40", "44"]),
  mc("medium", "In a room of 23 people, what is the approximate probability two share a birthday?", "50%", ["5%", "25%", "75%"]),
  mc("medium", "If all Bloops are Razzies and all Razzies are Lazzies, are all Bloops Lazzies?", "Yes", ["No", "Sometimes", "Cannot be determined"]),
  mc("medium", "What is the next number: 3, 9, 27, 81, __?", "243", ["162", "729", "108"]),
  mc("medium", "You have two ropes that each take 60 minutes to burn. How do you measure 45 minutes?", "Light rope 1 from both ends and rope 2 from one end; when rope 1 is done, light rope 2's other end", ["Light both from one end after 15 minutes", "Cut one rope in half", "Cannot be done"]),
  mc("hard", "What is the missing number: 2, 3, 5, 7, 11, 13, __?", "17", ["15", "14", "16"]),
  mc("hard", "Three friends split a $30 hotel bill, paying $10 each. The manager returns $5, but the bellboy keeps $2. Each person gets $1 back, paying $9 each, totalling $27 + $2 = $29. Where is the missing dollar?", "There is no missing dollar — $27 paid minus $2 kept = $25 for the room, plus $3 returned = $28 ✓", ["The bellboy took it", "The manager kept it", "Accounting error"]),
  mc("hard", "You have 12 balls, one is heavier. With 3 weighings on a balance scale, can you find it?", "Yes", ["No", "Only with 4 weighings", "Only if you know which half it's in"]),
  mc("hard", "What comes next: 0, 1, 4, 9, 16, 25, __?", "36", ["30", "49", "32"]),
  mc("hard", "A snail is at the bottom of a 10-foot well. Each day it climbs 3 feet, each night it slides 2 feet. How many days to escape?", "8 days", ["10 days", "5 days", "7 days"]),
  mc("hard", "If you fold a piece of paper 42 times, how thick would it be (roughly)?", "Distance to the Moon", ["1 metre", "Height of Mount Everest", "1 kilometre"]),
  mc("hard", "What is the next number in the sequence: 1, 8, 27, 64, 125, __?", "216", ["196", "225", "243"]),
  mc("hard", "A clock loses 10 minutes every hour. If it shows the correct time now, when will it next show the correct time?", "After 72 hours", ["After 12 hours", "After 24 hours", "After 6 hours"]),
  mc("hard", "100 people are in a line. Alternate people are removed starting from person 1. This repeats. Who is last?", "Person 64", ["Person 50", "Person 100", "Person 72"]),
  mc("hard", "How many squares are on a standard 8×8 chessboard in total?", "204", ["64", "128", "196"]),
  mc("expert", "What is the smallest number divisible by all integers from 1 to 10?", "2520", ["1000", "3628800", "5040"]),
  mc("expert", "The Monty Hall problem: switching doors after a reveal gives what probability of winning?", "2/3", ["1/2", "1/3", "3/4"]),
  mc("expert", "In logic, what is the name for a statement that is always false?", "Contradiction", ["Tautology", "Contingency", "Paradox"]),
  mc("expert", "If you have an infinite number of mathematicians and an infinite hotel, can you always fit more guests?", "Yes (Hilbert's Hotel paradox)", ["No", "Only if you move some out", "Only with finite guests"]),
  mc("expert", "What is the maximum number of moves in a game of Towers of Hanoi with 10 discs?", "1023", ["512", "2048", "1024"]),
  mc("expert", "A liar always lies, a truth-teller always tells the truth. You meet one and ask 'Are you a liar?' What do they say?", "Both say 'No'", ["Liar says Yes, truth-teller says No", "Liar says No, truth-teller says Yes", "You can't determine"]),
  mc("expert", "What is the halting problem in computer science?", "It's undecidable whether a program will halt or run forever", ["Programs always terminate if well-written", "A method to stop infinite loops", "A way to measure algorithm efficiency"]),
  mc("expert", "In a group of 30 people, what is the probability that at least two share a birthday?", "About 70%", ["About 30%", "About 50%", "About 90%"]),
  mc("expert", "What is the name of the famous paradox: 'This statement is false'?", "The Liar Paradox", ["Russell's Paradox", "Zeno's Paradox", "The Barber Paradox"]),
  mc("expert", "How many handshakes occur when 10 people each shake hands with every other person once?", "45", ["90", "100", "50"]),
];
