import { mc } from "./seed";
import type { QuestionSeed } from "./seed";

export const NATURE_SEEDS: QuestionSeed[] = [
  mc("easy", "What is the largest animal on Earth?", "Blue whale", ["Elephant", "Giraffe", "Great white shark"]),
  mc("easy", "What do caterpillars turn into?", "Butterflies or moths", ["Beetles", "Dragonflies", "Bees"]),
  mc("easy", "Which animal is known as the king of the jungle?", "Lion", ["Tiger", "Elephant", "Gorilla"]),
  mc("easy", "What is the fastest land animal?", "Cheetah", ["Lion", "Greyhound", "Horse"]),
  mc("easy", "How many legs does an insect have?", "6", ["4", "8", "10"]),
  mc("easy", "Which bird cannot fly?", "Penguin", ["Eagle", "Sparrow", "Parrot"]),
  mc("easy", "What is the human-made structure where domestic honeybees are typically kept by beekeepers?", "Hive", ["Den", "Burrow", "Nest"]),
  mc("easy", "Which animal is known for its black and white stripes?", "Zebra", ["Tiger", "Skunk", "Panda"]),
  mc("easy", "What is a group of lions called?", "Pride", ["Pack", "Herd", "Flock"]),
  mc("easy", "Which animal has the longest neck?", "Giraffe", ["Ostrich", "Flamingo", "Camel"]),
  mc("easy", "What is the term most commonly used in North American English for a female deer?", "Doe", ["Cow", "Hen", "Ewe"]),
  mc("easy", "Which ocean creature has eight arms?", "Octopus", ["Squid", "Jellyfish", "Starfish"]),
  mc("easy", "What is the largest land animal?", "African elephant", ["Hippopotamus", "White rhinoceros", "Giraffe"]),
  mc("easy", "What do frogs use to breathe underwater?", "Skin", ["Gills", "Lungs", "Fins"]),
  mc("easy", "Which bird species is famous for its ability to mimic the calls of other bird species and is named for this behavior?", "Mockingbird", ["Parrot", "Crow", "Starling"]),
  mc("easy", "What is a baby kangaroo called?", "Joey", ["Cub", "Pup", "Kit"]),
  mc("easy", "Which plant is known as the 'king of the desert'?", "Cactus", ["Palm tree", "Tumbleweed", "Aloe vera"]),
  mc("easy", "How many humps does a Bactrian camel have?", "2", ["1", "3", "0"]),
  mc("easy", "What is the largest type of bear?", "Polar bear", ["Grizzly bear", "Kodiak bear", "Brown bear"]),
  mc("easy", "Which insect produces honey?", "Bee", ["Wasp", "Ant", "Butterfly"]),
  mc("medium", "What is the gestation period of an elephant?", "22 months", ["12 months", "18 months", "9 months"]),
  mc("medium", "Which of these animals is capable of regenerating an entire lost arm and regrowing it to full functionality?", "Starfish", ["Axolotl", "Gecko", "Crab"]),
  mc("medium", "What is the name for an animal that is active at night?", "Nocturnal", ["Diurnal", "Crepuscular", "Cathemeral"]),
  mc("medium", "Which fish can generate electric shocks?", "Electric eel", ["Stingray", "Torpedo ray", "Stargazer"]),
  mc("medium", "What is the largest species of shark?", "Whale shark", ["Great white shark", "Basking shark", "Tiger shark"]),
  mc("medium", "Which mammal lays eggs?", "Platypus", ["Bat", "Whale", "Dolphin"]),
  mc("medium", "What is the term for the complete transformation process that includes egg, larva, pupa, and adult stages in insects like butterflies?", "Metamorphosis", ["Molting", "Ecdysis", "Gestation"]),
  mc("medium", "Which of these animals has the thickest actual skin layer (not including blubber or fat)?", "Hippopotamus", ["Whale", "Elephant", "Rhinoceros"]),
  mc("medium", "What is a group of wolves called?", "Pack", ["Pride", "Herd", "Flock"]),
  mc("medium", "Which bird has the largest wingspan?", "Wandering albatross", ["Condor", "Bald eagle", "Pelican"]),
  mc("medium", "What is the term for plants that lose their leaves in winter?", "Deciduous", ["Evergreen", "Perennial", "Annual"]),
  mc("medium", "Which animal has the highest blood pressure?", "Giraffe", ["Elephant", "Blue whale", "Horse"]),
  mc("medium", "What is the largest species of penguin?", "Emperor penguin", ["King penguin", "Chinstrap penguin", "Gentoo penguin"]),
  mc("medium", "Which type of tree produces acorns?", "Oak", ["Maple", "Beech", "Ash"]),
  mc("medium", "What is the name for an animal that eats only plants?", "Herbivore", ["Omnivore", "Carnivore", "Insectivore"]),
  mc("medium", "What is the maximum known lifespan of Galápagos tortoises, the longest-living land tortoise species?", "Over 150 years", ["Over 100 years", "Over 120 years", "Over 130 years"]),
  mc("hard", "What is the scientific name for the domestic dog?", "Canis lupus familiaris", ["Canis domesticus", "Canis familiaris", "Felis catus"]),
  mc("hard", "How many hearts does an octopus have?", "3", ["1", "2", "4"]),
  mc("hard", "Which animal has the most powerful bite force?", "Saltwater crocodile", ["Hippopotamus", "Great white shark", "Hyena"]),
  mc("hard", "What is the name of the process by which plants release water vapour?", "Transpiration", ["Evaporation", "Respiration", "Photosynthesis"]),
  mc("hard", "Which bird is the only one known to fly backwards regularly?", "Hummingbird", ["Kingfisher", "Swallow", "Martin"]),
  mc("hard", "What is the fastest fish in the ocean?", "Sailfish", ["Marlin", "Tuna", "Mako shark"]),
  mc("hard", "How many species belong to the genus Panthera, which includes the largest roaring cats?", "5", ["4", "6", "7"]),
  mc("hard", "What is the name of the symbiotic relationship between a clownfish and sea anemone?", "Mutualism", ["Commensalism", "Parasitism", "Predation"]),
  mc("hard", "Which animal has the largest brain-to-body mass ratio?", "Human", ["Sperm whale", "Dolphin", "Elephant"]),
  mc("hard", "What is the largest species of turtle?", "Leatherback sea turtle", ["Green sea turtle", "Loggerhead turtle", "Aldabra tortoise"]),
  mc("expert", "What is the term for a group of crows?", "Murder", ["Flock", "Colony", "Congress"]),
  mc("expert", "Which animal has blue blood?", "Horseshoe crab", ["Squid", "Lobster", "Octopus"]),
  mc("expert", "Which of the following is a pigment that contributes to color in bird feathers?", "Melanin", ["Hemoglobin", "Chlorophyll", "Collagen"]),
  mc("expert", "How many species of tree are there in the Amazon rainforest?", "~16,000", ["~5,000", "~30,000", "~10,000"]),
  mc("expert", "What is the deepest-diving marine mammal?", "Cuvier's beaked whale", ["Sperm whale", "Elephant seal", "Blue whale"]),
  mc("expert", "Which plant produces the largest individual flower bloom by diameter?", "Rafflesia arnoldii", ["Venus flytrap", "Sunflower", "Water lily"]),
  mc("expert", "What is the name of the chemical communication signals animals produce?", "Pheromones", ["Hormones", "Neurotransmitters", "Cytokines"]),
  mc("expert", "How many eyes does a dragonfly have?", "~30,000 facets across 2 compound eyes", ["2 simple eyes", "8 eyes", "4 eyes"]),
  mc("expert", "Which of these animals is known to have continuously growing teeth throughout its lifetime?", "Shark", ["Elephant", "Human", "Crocodile"]),
  mc("expert", "What is the term for the annual movement of animals from one region to another?", "Migration", ["Hibernation", "Nomadism", "Dispersal"]),
  mc("easy", "What is the largest planet in our solar system?", "Jupiter", ["Saturn", "Neptune", "Venus"]),
  mc("easy", "Which animal can change its skin color in seconds through chromatophores to match its surroundings?", "Cuttlefish", ["Chameleon", "Tree frog", "Parrot"]),
  mc("easy", "What do plants need from the sun to survive?", "Light energy", ["Heat only", "Ultraviolet rays", "Solar wind"]),
  mc("medium", "What is the process by which plants convert sunlight into chemical energy?", "Photosynthesis", ["Respiration", "Fermentation", "Transpiration"]),
  mc("medium", "Which biome has the highest biodiversity?", "Tropical rainforest", ["Temperate forest", "Grassland", "Tundra"]),
  mc("medium", "What is the smallest mammal in the world?", "Bumblebee bat", ["Pygmy shrew", "Feathertail glider", "Honey possum"]),
  mc("medium", "Which layer of Earth's atmosphere do airplanes typically fly through?", "Troposphere", ["Stratosphere", "Mesosphere", "Ionosphere"]),
  mc("medium", "What percentage of Earth's oxygen is produced by the ocean?", "At least 50%", ["About 20%", "Less than 10%", "Nearly 100%"]),
  mc("hard", "Water absorbed by plant roots travels upward to the leaves primarily through which tissue?", "Xylem", ["Phloem", "Bark", "Cortex"]),
  mc("hard", "What is the name of the supercontinent that existed 200 million years ago?", "Pangaea", ["Laurasia", "Gondwana", "Rodinia"]),
  mc("hard", "Which deep-sea creature produces light through bioluminescence using luciferin?", "Anglerfish", ["Vampire squid", "Barreleye fish", "Gulper eel"]),
  mc("expert", "What is the name of the protein in red blood cells that binds to oxygen?", "Hemoglobin", ["Myoglobin", "Chlorophyll", "Keratin"]),
  mc("expert", "Which enzyme breaks down hydrogen peroxide in cells to prevent oxidative damage?", "Catalase", ["Amylase", "Protease", "Lipase"]),
  mc("easy", "What do plants need from the sun to grow?", "Light", ["Heat only", "Oxygen", "Water"]),
  mc("easy", "What is the deepest ocean on Earth?", "Pacific Ocean", ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean"]),
  mc("medium", "Which biome receives the least annual rainfall?", "Desert", ["Tundra", "Taiga", "Grassland"]),
  mc("medium", "What process do plants use to convert sunlight into energy?", "Photosynthesis", ["Respiration", "Transpiration", "Fermentation"]),
  mc("medium", "Which of these animals is classified as an amphibian?", "Frog", ["Crocodile", "Lizard", "Turtle"]),
  mc("medium", "What is the primary gas in Earth's atmosphere?", "Nitrogen", ["Oxygen", "Carbon Dioxide", "Argon"]),
  mc("medium", "How often do monarch butterflies migrate?", "Once per year", ["Twice per year", "Every two years", "Every five years"]),
  mc("hard", "Which tree species is the tallest in the world?", "Coast Redwood", ["Douglas Fir", "Giant Sequoia", "Sitka Spruce"]),
  mc("hard", "What is the scientific name for the common fruit fly used in genetic research?", "Drosophila melanogaster", ["Musca domestica", "Calliphora vomitoria", "Lucilia sericata"]),
  mc("hard", "In which year was DNA structure first determined by Watson, Crick, and Franklin?", "1953", ["1951", "1955", "1950"]),
  mc("hard", "Which mammal is the only one capable of true flight?", "Bat", ["Flying squirrel", "Flying fish", "Flying lemur"]),
  mc("expert", "What is the only mammal known to have a venomous bite and venomous spurs?", "Platypus", ["Echidna", "Solenodon", "Shrew"]),
  mc("easy", "What is the largest land animal on Earth?", "African elephant", ["Hippopotamus", "Giraffe", "Rhinoceros"]),
  mc("easy", "Which gas do plants absorb from the atmosphere during photosynthesis?", "Carbon dioxide", ["Oxygen", "Nitrogen", "Helium"]),
  mc("medium", "Which biome is characterized by permafrost and extremely low temperatures?", "Tundra", ["Taiga", "Desert", "Savanna"]),
  mc("medium", "Which class of vertebrate animals is characterized by having dry, scaly skin and being cold-blooded?", "Reptile", ["Mammal", "Bird", "Fish"]),
  mc("medium", "Which ocean is the largest by surface area?", "Pacific Ocean", ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean"]),
  mc("medium", "What is the primary food source for a blue whale?", "Krill", ["Plankton", "Small fish", "Seaweed"]),
  mc("hard", "Which process describes the conversion of atmospheric nitrogen into usable compounds by microorganisms?", "Nitrogen fixation", ["Denitrification", "Nitrification", "Ammonification"]),
  mc("hard", "What is the name of the layer of the Earth's atmosphere where weather occurs?", "Troposphere", ["Stratosphere", "Mesosphere", "Thermosphere"]),
  mc("hard", "Which animal can rotate its eyes independently of each other?", "Chameleon", ["Owl", "Dragonfly", "Mantis"]),
  mc("hard", "What is the term for an animal that eats both plants and meat?", "Omnivore", ["Herbivore", "Carnivore", "Detritivore"]),
  mc("expert", "Which enzyme is responsible for breaking down cellulose in herbivores' digestive systems?", "Cellulase", ["Amylase", "Protease", "Lipase"]),
  mc("expert", "What is the name of the phenomenon where a species evolves different traits in isolated populations?", "Allopatric speciation", ["Sympatric speciation", "Adaptive radiation", "Convergent evolution"]),
  mc("expert", "Which biogeographic zone is characterized by high biodiversity and year-round warm temperatures near the equator?", "Tropical rainforest", ["Temperate deciduous forest", "Boreal forest", "Subtropical grassland"]),
  mc("easy", "How many legs does a spider typically have?", "8", ["6", "10", "12"]),
  mc("easy", "What do you call a group of lions?", "Pride", ["Pack", "Herd", "Colony"]),
  mc("medium", "Which mammal lays eggs instead of giving birth to live young?", "Platypus", ["Koala", "Kangaroo", "Dolphin"]),
  mc("medium", "What is the largest organ in the human body by surface area?", "Skin", ["Liver", "Lungs", "Intestines"]),
  mc("medium", "Which type of tree is the tallest species on Earth?", "Coast redwood", ["Douglas fir", "Sitka spruce", "Eucalyptus"]),
  mc("medium", "What is the process by which water changes from liquid to vapor?", "Evaporation", ["Condensation", "Sublimation", "Precipitation"]),
  mc("hard", "Which hot biome is characterized by less than 10 inches of annual precipitation and extremely high temperatures year-round?", "Desert", ["Tundra", "Tropical rainforest", "Temperate grassland"]),
  mc("hard", "Which organelle is responsible for producing energy in plant and animal cells?", "Mitochondria", ["Ribosome", "Vacuole", "Centrosome"]),
];
