import { img, mc } from "./seed";
import type { QuestionSeed } from "./seed";

export const NATURE_SEEDS: QuestionSeed[] = [
  mc("easy", "What is the largest mammal in the world?", "Blue whale", ["Elephant", "Giraffe", "Hippopotamus"]),
  mc("easy", "What is the fastest land animal?", "Cheetah", ["Lion", "Horse", "Greyhound"]),
  mc("easy", "Which bird is known for its inability to fly but excellent swimming?", "Penguin", ["Ostrich", "Eagle", "Flamingo"]),
  mc("easy", "What do bees produce that humans eat?", "Honey", ["Pollen", "Wax", "Nectar"]),
  mc("easy", "Which animal is known as the 'King of the Jungle'?", "Lion", ["Tiger", "Elephant", "Gorilla"]),
  mc("easy", "What is a baby kangaroo called?", "Joey", ["Cub", "Pup", "Fawn"]),
  mc("easy", "Which tree produces acorns?", "Oak", ["Maple", "Pine", "Birch"]),
  mc("easy", "How many legs does an insect have?", "6", ["8", "4", "10"]),
  mc("easy", "What is the largest species of big cat?", "Tiger", ["Lion", "Jaguar", "Leopard"]),
  mc("easy", "Which gas do animals breathe in to survive?", "Oxygen", ["Carbon dioxide", "Nitrogen", "Helium"]),
  mc("medium", "Which animal has the longest lifespan, in some species over 400 years?", "Greenland shark", ["Galápagos tortoise", "Blue whale", "African elephant"]),
  mc("medium", "What is the only mammal capable of true flight?", "Bat", ["Flying squirrel", "Sugar glider", "Colugo"]),
  mc("medium", "Which plant is known for catching and digesting insects?", "Venus flytrap", ["Sunflower", "Cactus", "Fern"]),
  mc("medium", "What is the term for an animal that eats both plants and meat?", "Omnivore", ["Herbivore", "Carnivore", "Detritivore"]),
  mc("medium", "Which is the largest rainforest in the world?", "Amazon Rainforest", ["Congo Rainforest", "Daintree Rainforest", "Valdivian Rainforest"]),
  mc("medium", "What do you call a group of wolves?", "Pack", ["Herd", "Flock", "Pod"]),
  mc("medium", "Which animal can regenerate a lost limb?", "Starfish", ["Dolphin", "Octopus only", "Sea turtle"]),
  mc("medium", "What is the tallest grass in the world?", "Bamboo", ["Sugarcane", "Wheat", "Pampas grass"]),
  mc("hard", "Which animal has the largest eyes of any land mammal?", "Horse", ["Owl", "Elephant", "Tarsier"]),
  mc("hard", "What is the only continent without any native ant species?", "Antarctica", ["Australia", "South America", "Europe"]),
  mc("hard", "Which tree species is believed to be the oldest living organism on Earth?", "Bristlecone pine", ["Giant sequoia", "Baobab", "Olive tree"]),
  mc("hard", "What is a group of crows called?", "A murder", ["A flock", "A gaggle", "A parliament"]),
  mc("expert", "Which animal's heart can weigh up to 400 pounds?", "Blue whale", ["African elephant", "Sperm whale", "Giraffe"]),
  mc("expert", "What is the name for a symbiotic relationship where both species benefit?", "Mutualism", ["Parasitism", "Commensalism", "Predation"]),
  img("easy", "🦁", "What animal is this?", "Lion", ["Tiger", "Bear", "Wolf"]),
  img("easy", "🐘", "What animal is this?", "Elephant", ["Rhino", "Hippo", "Walrus"]),
  img("easy", "🐧", "What animal is this?", "Penguin", ["Seal", "Duck", "Puffin"]),
  img("medium", "🦒", "What animal is this?", "Giraffe", ["Zebra", "Camel", "Antelope"]),
  img("medium", "🐊", "What animal is this?", "Crocodile", ["Alligator", "Lizard", "Komodo dragon"]),
  img("medium", "🦥", "What animal is this?", "Sloth", ["Koala", "Anteater", "Armadillo"]),
];
