import { mc } from "./seed";
import type { QuestionSeed } from "./seed";

export const NATURE_SEEDS: QuestionSeed[] = [
  mc("easy", "What is the largest animal on Earth?", "Blue whale", ["Elephant", "Giraffe", "Great white shark"]),
  mc("easy", "What do caterpillars turn into?", "Butterflies or moths", ["Beetles", "Dragonflies", "Bees"]),
  mc("easy", "Which animal is known as the king of the jungle?", "Lion", ["Tiger", "Elephant", "Gorilla"]),
  mc("easy", "What is the fastest land animal?", "Cheetah", ["Lion", "Greyhound", "Horse"]),
  mc("easy", "How many legs does an insect have?", "6", ["4", "8", "10"]),
  mc("easy", "Which bird cannot fly?", "Penguin", ["Eagle", "Sparrow", "Parrot"]),
  mc("easy", "What do bees live in?", "Hive", ["Den", "Burrow", "Nest"]),
  mc("easy", "Which animal is known for its black and white stripes?", "Zebra", ["Tiger", "Skunk", "Panda"]),
  mc("easy", "What is a group of lions called?", "Pride", ["Pack", "Herd", "Flock"]),
  mc("easy", "Which animal has the longest neck?", "Giraffe", ["Ostrich", "Flamingo", "Camel"]),
  mc("easy", "What do you call a female deer?", "Doe", ["Hind", "Cow", "Hen"]),
  mc("easy", "Which ocean creature has eight arms?", "Octopus", ["Squid", "Jellyfish", "Starfish"]),
  mc("easy", "What is the largest land animal?", "African elephant", ["Hippopotamus", "White rhinoceros", "Giraffe"]),
  mc("easy", "What do frogs use to breathe underwater?", "Skin", ["Gills", "Lungs", "Fins"]),
  mc("easy", "Which bird is known for mimicking sounds?", "Parrot", ["Crow", "Mockingbird", "Starling"]),
  mc("easy", "What is a baby kangaroo called?", "Joey", ["Cub", "Pup", "Kit"]),
  mc("easy", "Which plant is known as the 'king of the desert'?", "Cactus", ["Palm tree", "Tumbleweed", "Aloe vera"]),
  mc("easy", "How many humps does a Bactrian camel have?", "2", ["1", "3", "0"]),
  mc("easy", "What is the largest type of bear?", "Polar bear", ["Grizzly bear", "Kodiak bear", "Brown bear"]),
  mc("easy", "Which insect produces honey?", "Bee", ["Wasp", "Ant", "Butterfly"]),
  mc("medium", "What is the gestation period of an elephant?", "22 months", ["12 months", "18 months", "9 months"]),
  mc("medium", "Which animal can regrow its limbs?", "Axolotl", ["Gecko", "Starfish", "Crab"]),
  mc("medium", "What is the name for an animal that is active at night?", "Nocturnal", ["Diurnal", "Crepuscular", "Cathemeral"]),
  mc("medium", "Which fish can generate electric shocks?", "Electric eel", ["Stingray", "Torpedo ray", "Stargazer"]),
  mc("medium", "What is the largest species of shark?", "Whale shark", ["Great white shark", "Basking shark", "Tiger shark"]),
  mc("medium", "Which mammal lays eggs?", "Platypus", ["Bat", "Whale", "Dolphin"]),
  mc("medium", "What is the name for the process by which a caterpillar transforms into a butterfly?", "Metamorphosis", ["Molting", "Pupation", "Chrysalisation"]),
  mc("medium", "Which animal has the thickest skin?", "Whale", ["Elephant", "Hippopotamus", "Rhinoceros"]),
  mc("medium", "What is a group of wolves called?", "Pack", ["Pride", "Herd", "Flock"]),
  mc("medium", "Which bird has the largest wingspan?", "Wandering albatross", ["Condor", "Bald eagle", "Pelican"]),
  mc("medium", "What is the term for plants that lose their leaves in winter?", "Deciduous", ["Evergreen", "Perennial", "Annual"]),
  mc("medium", "Which animal has the highest blood pressure?", "Giraffe", ["Elephant", "Blue whale", "Horse"]),
  mc("medium", "What is the largest species of penguin?", "Emperor penguin", ["King penguin", "Chinstrap penguin", "Gentoo penguin"]),
  mc("medium", "Which type of tree produces acorns?", "Oak", ["Maple", "Beech", "Ash"]),
  mc("medium", "What is the name for an animal that eats only plants?", "Herbivore", ["Omnivore", "Carnivore", "Insectivore"]),
  mc("medium", "How long can a tortoise live?", "Over 150 years", ["50 years", "80 years", "100 years"]),
  mc("hard", "What is the scientific name for the domestic dog?", "Canis lupus familiaris", ["Canis domesticus", "Canis familiaris", "Felis catus"]),
  mc("hard", "How many hearts does an octopus have?", "3", ["1", "2", "4"]),
  mc("hard", "Which animal has the most powerful bite force?", "Saltwater crocodile", ["Hippopotamus", "Great white shark", "Hyena"]),
  mc("hard", "What is the name of the process by which plants release water vapour?", "Transpiration", ["Evaporation", "Respiration", "Photosynthesis"]),
  mc("hard", "Which bird is the only one known to fly backwards regularly?", "Hummingbird", ["Kingfisher", "Swallow", "Martin"]),
  mc("hard", "What is the fastest fish in the ocean?", "Sailfish", ["Marlin", "Tuna", "Mako shark"]),
  mc("hard", "How many species of big cats are there?", "5", ["4", "6", "7"]),
  mc("hard", "What is the name of the symbiotic relationship between a clownfish and sea anemone?", "Mutualism", ["Commensalism", "Parasitism", "Predation"]),
  mc("hard", "Which animal has the largest brain relative to its body size?", "Sperm whale (by mass)", ["Dolphin", "Crow", "Chimpanzee"]),
  mc("hard", "What is the largest species of turtle?", "Leatherback sea turtle", ["Green sea turtle", "Loggerhead turtle", "Aldabra tortoise"]),
  mc("expert", "What is the term for a group of crows?", "Murder", ["Flock", "Colony", "Congress"]),
  mc("expert", "Which animal has blue blood?", "Horseshoe crab", ["Squid", "Lobster", "Octopus"]),
  mc("expert", "What is the name of the protein that gives bird feathers their colour?", "Melanin", ["Keratin", "Carotenoid", "Porphyrin"]),
  mc("expert", "How many species of tree are there in the Amazon rainforest?", "~16,000", ["~5,000", "~30,000", "~10,000"]),
  mc("expert", "What is the deepest-diving marine mammal?", "Cuvier's beaked whale", ["Sperm whale", "Elephant seal", "Blue whale"]),
  mc("expert", "Which plant has the world's largest flower?", "Rafflesia arnoldii", ["Titan arum", "Corpse flower", "Amorphophallus"]),
  mc("expert", "What is the name of the chemical communication signals animals produce?", "Pheromones", ["Hormones", "Neurotransmitters", "Cytokines"]),
  mc("expert", "How many eyes does a dragonfly have?", "~30,000 facets across 2 compound eyes", ["2 simple eyes", "8 eyes", "4 eyes"]),
  mc("expert", "Which animal has the most teeth?", "Garden snail (up to 14,000)", ["Great white shark", "Spinner dolphin", "Catfish"]),
  mc("expert", "What is the term for the annual movement of animals from one region to another?", "Migration", ["Hibernation", "Nomadism", "Dispersal"]),
];
