import { mc } from "./seed";
import type { QuestionSeed } from "./seed";

export const SCIENCE_SEEDS: QuestionSeed[] = [
  mc("easy", "What is the chemical symbol for water?", "H2O", ["CO2", "O2", "H2O2"]),
  mc("easy", "What planet is known as the Red Planet?", "Mars", ["Venus", "Jupiter", "Mercury"]),
  mc("easy", "What gas do plants absorb from the air?", "Carbon dioxide", ["Oxygen", "Nitrogen", "Hydrogen"]),
  mc("easy", "How many bones are in the adult human body?", "206", ["196", "216", "186"]),
  mc("easy", "What is the powerhouse of the cell called?", "Mitochondria", ["Nucleus", "Ribosome", "Golgi body"]),
  mc("easy", "What force pulls objects toward the Earth?", "Gravity", ["Magnetism", "Friction", "Inertia"]),
  mc("easy", "What is the boiling point of water in Celsius?", "100°C", ["90°C", "120°C", "80°C"]),
  mc("easy", "What part of the body pumps blood?", "Heart", ["Lungs", "Liver", "Kidneys"]),
  mc("easy", "What is the chemical symbol for gold?", "Au", ["Ag", "Gd", "Go"]),
  mc("easy", "How many legs does a spider have?", "8", ["6", "10", "4"]),
  mc("medium", "What is the hardest natural substance on Earth?", "Diamond", ["Quartz", "Titanium", "Granite"]),
  mc("medium", "What is the most abundant gas in Earth's atmosphere?", "Nitrogen", ["Oxygen", "Carbon dioxide", "Argon"]),
  mc("medium", "What type of energy is stored in food?", "Chemical energy", ["Kinetic energy", "Thermal energy", "Nuclear energy"]),
  mc("medium", "Which blood type is known as the universal donor?", "O negative", ["AB positive", "A negative", "B positive"]),
  mc("medium", "What is the study of fungi called?", "Mycology", ["Botany", "Zoology", "Entomology"]),
  mc("medium", "What part of the atom has a negative charge?", "Electron", ["Proton", "Neutron", "Nucleus"]),
  mc("medium", "What is the pH of pure water?", "7", ["0", "14", "5"]),
  mc("medium", "Which organ produces insulin?", "Pancreas", ["Liver", "Kidney", "Spleen"]),
  mc("medium", "What is the speed of light in a vacuum (approximately)?", "300,000 km/s", ["150,000 km/s", "1,000,000 km/s", "30,000 km/s"]),
  mc("medium", "What type of bond forms when atoms share electrons?", "Covalent bond", ["Ionic bond", "Metallic bond", "Hydrogen bond"]),
  mc("hard", "What is the most abundant element in the universe?", "Hydrogen", ["Helium", "Oxygen", "Carbon"]),
  mc("hard", "Which scientist developed the theory of general relativity?", "Albert Einstein", ["Isaac Newton", "Niels Bohr", "Max Planck"]),
  mc("hard", "What is the unit of electrical resistance?", "Ohm", ["Volt", "Watt", "Ampere"]),
  mc("hard", "What is the process by which plants make food called?", "Photosynthesis", ["Respiration", "Transpiration", "Fermentation"]),
  mc("hard", "Which element has the atomic number 1?", "Hydrogen", ["Helium", "Lithium", "Carbon"]),
  mc("hard", "What is the name for an animal that is both predator and prey?", "Mesopredator", ["Omnivore", "Scavenger", "Apex predator"]),
  mc("expert", "What particle is responsible for giving other particles mass, confirmed in 2012?", "Higgs boson", ["Quark", "Neutrino", "Photon"]),
  mc("expert", "What is the name of the process where a star collapses into a black hole?", "Gravitational collapse", ["Nuclear fission", "Supernova rebound", "Stellar fusion"]),
  mc("expert", "Which scientist first proposed the theory of evolution by natural selection?", "Charles Darwin", ["Gregor Mendel", "Carl Linnaeus", "Alfred Wegener"]),
  mc("expert", "What is the term for a solid turning directly into a gas without becoming liquid?", "Sublimation", ["Condensation", "Deposition", "Evaporation"]),
];
