import { mc } from "./seed";
import type { QuestionSeed } from "./seed";

export const SCIENCE_SEEDS: QuestionSeed[] = [
  // ── easy ──────────────────────────────────────────────────────────────────
  mc("easy", "What is the chemical symbol for water?", "H2O", ["CO2", "O2", "H2O2"]),
  mc("easy", "What gas do plants absorb from the air?", "Carbon dioxide", ["Oxygen", "Nitrogen", "Hydrogen"]),
  mc("easy", "How many bones are in the adult human body?", "206", ["196", "216", "186"]),
  mc("easy", "What is the powerhouse of the cell called?", "Mitochondria", ["Nucleus", "Ribosome", "Golgi body"]),
  mc("easy", "What force pulls objects toward the Earth?", "Gravity", ["Magnetism", "Friction", "Inertia"]),
  mc("easy", "What is the boiling point of water in Celsius?", "100°C", ["90°C", "120°C", "80°C"]),
  mc("easy", "What part of the body pumps blood?", "Heart", ["Lungs", "Liver", "Kidneys"]),
  mc("easy", "What is the chemical symbol for gold?", "Au", ["Ag", "Gd", "Go"]),
  mc("easy", "How many legs does a spider have?", "8", ["6", "10", "4"]),
  mc("easy", "What gas do humans breathe out?", "Carbon dioxide", ["Oxygen", "Nitrogen", "Hydrogen"]),
  mc("easy", "What is the centre of an atom called?", "Nucleus", ["Electron", "Neutron", "Proton"]),
  mc("easy", "Which planet has the shortest year in our solar system?", "Mercury", ["Venus", "Earth", "Mars"]),
  mc("easy", "What colour is chlorophyll?", "Green", ["Yellow", "Blue", "Red"]),
  mc("easy", "How many chambers does the human heart have?", "4", ["2", "3", "6"]),
  mc("easy", "What organ removes waste from the blood?", "Kidneys", ["Liver", "Lungs", "Spleen"]),
  mc("easy", "What is the freezing point of water in Celsius?", "0°C", ["-10°C", "10°C", "5°C"]),
  mc("easy", "Which planet is largest in our solar system?", "Jupiter", ["Saturn", "Neptune", "Uranus"]),
  mc("easy", "What do you call a baby frog?", "Tadpole", ["Froglet", "Spawn", "Hatchling"]),
  mc("easy", "What is the chemical symbol for oxygen?", "O", ["Ox", "O2", "Om"]),
  mc("easy", "How many teeth does an adult human normally have?", "32", ["28", "30", "36"]),
  mc("easy", "Which of the following is the primary source of energy that powers the Sun?", "Nuclear fusion of hydrogen into helium", ["Chemical combustion of gases", "Gravitational collapse alone", "Radioactive decay of uranium"]),
  mc("easy", "What is the smallest planet in our solar system?", "Mercury", ["Mars", "Pluto", "Venus"]),
  mc("easy", "What do bees produce?", "Honey", ["Wax only", "Silk", "Syrup"]),
  mc("easy", "What is the study of plants called?", "Botany", ["Zoology", "Ecology", "Mycology"]),
  mc("easy", "How many individual chromosomes are present in a typical human somatic cell?", "46", ["23", "20", "92"]),

  // ── medium ────────────────────────────────────────────────────────────────
  mc("medium", "What is the hardest natural substance on Earth?", "Diamond", ["Quartz", "Titanium", "Granite"]),
  mc("medium", "What is the most abundant gas in Earth's atmosphere?", "Nitrogen", ["Oxygen", "Carbon dioxide", "Argon"]),
  mc("medium", "Which blood type is known as the universal donor?", "O negative", ["AB positive", "A negative", "B positive"]),
  mc("medium", "What is the study of fungi called?", "Mycology", ["Botany", "Zoology", "Entomology"]),
  mc("medium", "What part of the atom has a negative charge?", "Electron", ["Proton", "Neutron", "Nucleus"]),
  mc("medium", "What is the pH of pure water?", "7", ["0", "14", "5"]),
  mc("medium", "Which organ produces insulin?", "Pancreas", ["Liver", "Kidney", "Spleen"]),
  mc("medium", "What is the speed of light in a vacuum, approximately?", "300,000 km/s", ["150,000 km/s", "1,000,000 km/s", "30,000 km/s"]),
  mc("medium", "What type of bond forms when atoms share electrons?", "Covalent bond", ["Ionic bond", "Metallic bond", "Hydrogen bond"]),
  mc("medium", "What is the name of the process by which liquid becomes gas?", "Evaporation", ["Condensation", "Sublimation", "Precipitation"]),
  mc("medium", "How many chambers does a fish's heart have?", "2", ["3", "4", "1"]),
  mc("medium", "What is the unit of electrical current?", "Ampere", ["Volt", "Watt", "Ohm"]),
  mc("medium", "What is the name for a group of organisms of the same species living in the same area?", "Population", ["Community", "Ecosystem", "Biome"]),
  mc("medium", "What part of a plant conducts water upward from roots?", "Xylem", ["Phloem", "Cambium", "Epidermis"]),
  mc("medium", "Methane (CH₄) typically comprises what percentage of natural gas by volume?", "70-90%", ["10-30%", "40-60%", "95-99%"]),
  mc("medium", "Which layer of the atmosphere contains the ozone layer?", "Stratosphere", ["Troposphere", "Mesosphere", "Thermosphere"]),
  mc("medium", "What is the name for a force that opposes relative motion between surfaces?", "Friction", ["Tension", "Normal force", "Drag"]),
  mc("medium", "What is the atomic number of carbon?", "6", ["4", "8", "12"]),
  mc("medium", "Which organelle is responsible for protein synthesis?", "Ribosome", ["Mitochondria", "Golgi body", "Nucleus"]),
  mc("medium", "What is the term for the bending of light as it passes through water?", "Refraction", ["Reflection", "Diffraction", "Dispersion"]),
  mc("medium", "What is the name of the process plants use to make food?", "Photosynthesis", ["Respiration", "Transpiration", "Fermentation"]),
  mc("medium", "What are the three states of matter?", "Solid, liquid, gas", ["Hot, warm, cold", "Element, compound, mixture", "Organic, inorganic, plasma"]),
  mc("medium", "What is the chemical formula for table salt?", "NaCl", ["KCl", "NaF", "CaCl2"]),
  mc("medium", "What is the name of the force that keeps planets in orbit?", "Gravity", ["Magnetism", "Centrifugal force", "Electrostatic force"]),
  mc("medium", "How many valence electrons does oxygen have?", "6", ["4", "8", "2"]),

  // ── hard ──────────────────────────────────────────────────────────────────
  mc("hard", "What is the most abundant element in the universe?", "Hydrogen", ["Helium", "Oxygen", "Carbon"]),
  mc("hard", "Which scientist developed the theory of general relativity?", "Albert Einstein", ["Isaac Newton", "Niels Bohr", "Max Planck"]),
  mc("hard", "What is the unit of electrical resistance?", "Ohm", ["Volt", "Watt", "Ampere"]),
  mc("hard", "Which element has the atomic number 1?", "Hydrogen", ["Helium", "Lithium", "Carbon"]),
  mc("hard", "In a food chain, an organism that hunts smaller animals but is also hunted by larger predators is best described as a(n):", "Intermediate consumer", ["Apex predator", "Primary consumer", "Decomposer"]),
  mc("hard", "What is the half-life of carbon-14 in years?", "5,730 years", ["1,000 years", "50,000 years", "500 years"]),
  mc("hard", "Which layer of Earth is defined as the thin, solid, outermost shell composed primarily of silicate rock?", "Crust", ["Mantle", "Outer core", "Inner core"]),
  mc("hard", "What type of wave is sound?", "Longitudinal", ["Transverse", "Electromagnetic", "Surface"]),
  mc("hard", "What is the chemical formula for ammonia?", "NH3", ["NO2", "N2H4", "NaCl"]),
  mc("hard", "What is Newton's second law of motion?", "Force = mass × acceleration", ["For every action there is an equal and opposite reaction", "An object in motion stays in motion", "Energy cannot be created or destroyed"]),
  mc("hard", "Which two elements make up water?", "Hydrogen and oxygen", ["Carbon and hydrogen", "Nitrogen and oxygen", "Helium and oxygen"]),
  mc("hard", "What is the name for the measure of disorder in a system?", "Entropy", ["Enthalpy", "Energy", "Equilibrium"]),
  mc("hard", "What is the main function of white blood cells?", "Fight infection", ["Carry oxygen", "Clot blood", "Produce hormones"]),
  mc("hard", "In which year did the Chernobyl nuclear disaster occur?", "1986", ["1979", "1992", "1984"]),
  mc("hard", "What is the chemical symbol for iron?", "Fe", ["Ir", "In", "Io"]),

  // ── expert ────────────────────────────────────────────────────────────────
  mc("expert", "What particle is responsible for giving other particles mass, confirmed in 2012?", "Higgs boson", ["Quark", "Neutrino", "Photon"]),
  mc("expert", "What is the name of the process where a star collapses into a black hole?", "Gravitational collapse", ["Nuclear fission", "Supernova rebound", "Stellar fusion"]),
  mc("expert", "Which scientist first proposed the theory of evolution by natural selection?", "Charles Darwin", ["Gregor Mendel", "Carl Linnaeus", "Alfred Wegener"]),
  mc("expert", "What is the term for a solid turning directly into a gas?", "Sublimation", ["Condensation", "Deposition", "Evaporation"]),
  mc("expert", "What is the Planck constant approximately equal to?", "6.626 × 10⁻³⁴ J·s", ["3.0 × 10⁸ m/s", "9.8 m/s²", "6.022 × 10²³"]),
  mc("expert", "What is CRISPR primarily used for?", "Gene editing", ["Protein synthesis", "Drug delivery", "Cell imaging"]),
  mc("expert", "What is the name of the phenomenon where light behaves as both a wave and a particle?", "Wave-particle duality", ["Quantum entanglement", "Superposition", "Uncertainty principle"]),
  mc("expert", "Which element was discovered by Marie Curie and named after her homeland?", "Polonium", ["Radium", "Curium", "Francium"]),
  mc("expert", "What is the approximate age of the universe in years?", "13.8 billion", ["4.5 billion", "100 billion", "6 billion"]),
  mc("expert", "What does DNA stand for?", "Deoxyribonucleic acid", ["Dinitrogen adenine", "Deoxyribose amino acid", "Dinucleotide acid"]),
  mc("medium", "What is the only mammal capable of true flight?", "Bat", ["Flying squirrel", "Flying fish", "Flying lemur"]),
  mc("medium", "As of 2024, which planet in our solar system has the greatest number of confirmed moons?", "Saturn", ["Jupiter", "Uranus", "Neptune"]),
  mc("hard", "What is the name of the protein in red blood cells that carries oxygen?", "Hemoglobin", ["Myoglobin", "Chlorophyll", "Keratin"]),
  mc("easy", "What gas do plants absorb from the atmosphere?", "Carbon dioxide", ["Oxygen", "Nitrogen", "Helium"]),
  mc("medium", "What is the smallest unit of life?", "Cell", ["Atom", "Molecule", "Organism"]),
  mc("hard", "Which scientist became the first person to win Nobel Prizes in two different scientific disciplines?", "Marie Curie", ["Ernest Rutherford", "Frederick Sanger", "John Bardeen"]),
  mc("medium", "What type of animal is a dolphin?", "Mammal", ["Fish", "Amphibian", "Reptile"]),
  mc("hard", "What is the name of the theoretical boundary around a black hole?", "Event horizon", ["Singularity", "Photon sphere", "Accretion disk"]),
  mc("hard", "What is the quantum number that describes the shape of an orbital?", "Angular momentum quantum number", ["Principal quantum number", "Magnetic quantum number", "Spin quantum number"]),
  mc("easy", "What is the speed of light in a vacuum?", "299,792,458 meters per second", ["150,000,000 meters per second", "500,000,000 meters per second", "100,000,000 meters per second"]),
  mc("medium", "In the periodic table, what element has the atomic number 26?", "Iron", ["Cobalt", "Nickel", "Zinc"]),
  mc("medium", "What type of animal is a seahorse?", "Fish", ["Mollusk", "Crustacean", "Marine mammal"]),
  mc("medium", "Which organelle in plant cells is responsible for photosynthesis?", "Chloroplast", ["Mitochondrion", "Ribosome", "Vacuole"]),
  mc("hard", "What is the name of the phenomenon where light bends when passing through different media?", "Refraction", ["Diffraction", "Reflection", "Polarization"]),
  mc("hard", "Which neurotransmitter is primarily involved in mood regulation and is targeted by SSRIs?", "Serotonin", ["Dopamine", "Acetylcholine", "GABA"]),
  mc("hard", "What is the name of the boundary layer around a black hole beyond which nothing can escape?", "Event horizon", ["Singularity", "Photon sphere", "Ergosphere"]),
  mc("expert", "Which of the following is a chemical element found on the periodic table of elements?", "Copper", ["Hydrogen (not an element, it's a compound)", "Oxygen (not a pure element)", "Nitrogen (not a pure element)"]),
  mc("expert", "In quantum mechanics, what is the name of the principle stating that certain pairs of physical properties cannot both be known to arbitrary precision?", "Heisenberg uncertainty principle", ["Pauli exclusion principle", "Planck's constant principle", "Compton scattering principle"]),
  mc("medium", "What is the process by which water changes from a liquid to a gas?", "Evaporation", ["Condensation", "Sublimation", "Precipitation"]),
  mc("medium", "Which organelle is responsible for producing energy in a cell?", "Mitochondrion", ["Ribosome", "Nucleus", "Golgi apparatus"]),
  mc("easy", "What is the speed of light in vacuum?", "299,792,458 meters per second", ["150,000,000 meters per second", "450,000,000 meters per second", "100,000,000 meters per second"]),
  mc("medium", "What is the most abundant element in the Earth's atmosphere?", "Nitrogen", ["Oxygen", "Argon", "Carbon dioxide"]),
  mc("medium", "Which type of blood cell is responsible for fighting infections?", "White blood cells", ["Red blood cells", "Platelets", "Hemoglobin"]),
  mc("medium", "What is the SI unit of electric current?", "Ampere", ["Volt", "Ohm", "Watt"]),
  mc("hard", "In quantum mechanics, what principle states that certain pairs of physical properties cannot both be known precisely?", "Heisenberg uncertainty principle", ["Pauli exclusion principle", "Planck's constant", "Schrödinger's equation"]),
  mc("expert", "What is the name of the hypothetical particle predicted to give mass to other particles?", "Higgs boson", ["Gluon", "Muon", "Tau particle"]),
  mc("expert", "What is the term for the minimum energy needed to remove an electron from an atom?", "Ionization energy", ["Binding energy", "Activation energy", "Dissociation energy"]),
  mc("easy", "What gas do plants absorb from the atmosphere during photosynthesis?", "Carbon dioxide", ["Oxygen", "Nitrogen", "Helium"]),
  mc("medium", "At what temperature does water boil at sea level?", "100°C", ["90°C", "110°C", "85°C"]),
  mc("hard", "Charles Darwin published 'On the Origin of Species' in which year?", "1859", ["1844", "1871", "1882"]),
  mc("hard", "What is the process by which plants convert light energy into chemical energy?", "Photosynthesis", ["Respiration", "Fermentation", "Oxidation"]),
  mc("expert", "What is the name of the phenomenon where light bends as it passes through a lens or prism?", "Refraction", ["Diffraction", "Dispersion", "Reflection"]),
  mc("expert", "What is the name of the boundary between the Earth's crust and mantle?", "Mohorovičić discontinuity", ["Gutenberg discontinuity", "Lehmann discontinuity", "Conrad discontinuity"]),
  mc("medium", "What organelle is responsible for producing ATP in a cell?", "Mitochondrion", ["Ribosome", "Golgi apparatus", "Lysosome"]),
  mc("medium", "Which element has the atomic number 8?", "Oxygen", ["Nitrogen", "Carbon", "Neon"]),
  mc("hard", "What is the name of the phenomenon where light bends when passing through a medium?", "Refraction", ["Reflection", "Diffraction", "Dispersion"]),
  mc("hard", "In 1858, Charles Darwin and Alfred Russell Wallace jointly presented their theory of natural selection to which scientific society?", "The Linnean Society of London", ["The Royal Society of London", "The British Museum of Natural History", "The Cambridge Philosophical Society"]),
  mc("hard", "What is the most abundant element in the Earth's crust?", "Oxygen", ["Silicon", "Aluminum", "Iron"]),
  mc("expert", "What is the name of the theoretical boundary around a black hole beyond which nothing can escape?", "Event horizon", ["Photon sphere", "Singularity", "Accretion disk"]),
  mc("expert", "Which physicist formulated the uncertainty principle in quantum mechanics?", "Werner Heisenberg", ["Erwin Schrödinger", "Niels Bohr", "Max Planck"]),
  mc("easy", "What is the powerhouse of the cell?", "Mitochondria", ["Nucleus", "Ribosome", "Chloroplast"]),
  mc("medium", "What is the process by which water changes from liquid to gas?", "Evaporation", ["Condensation", "Sublimation", "Freezing"]),
  mc("medium", "How many chambers does a human heart have?", "Four", ["Two", "Three", "Six"]),
  mc("medium", "What type of radiation has the longest wavelength?", "Radio waves", ["Ultraviolet", "Gamma rays", "X-rays"]),
  mc("hard", "In physics, what is the SI unit of electric current?", "Ampere", ["Watt", "Ohm", "Volt"]),
  mc("hard", "Which organelle is responsible for producing ATP in plant cells through photosynthesis?", "Chloroplast", ["Vacuole", "Lysosome", "Golgi apparatus"]),
  mc("expert", "Which amino acid is the only one without a chiral center in its structure?", "Glycine", ["Alanine", "Serine", "Leucine"]),
  mc("easy", "What gas do plants primarily use for photosynthesis?", "Carbon dioxide", ["Oxygen", "Nitrogen", "Hydrogen"]),
  mc("medium", "What type of blood cell helps fight infections?", "White blood cell", ["Red blood cell", "Platelet", "Hemoglobin"]),
  mc("medium", "In genetics, what does 'DNA' stand for?", "Deoxyribonucleic acid", ["Diribose nucleic acid", "Deoxyribose nucleotide assembly", "Dynamic nucleic algorithm"]),
  mc("hard", "What is the name of the phenomenon where light bends when passing through a medium of different density?", "Refraction", ["Diffraction", "Reflection", "Dispersion"]),
  mc("hard", "Which physicist conducted experiments with falling bodies and electrical resistance that helped establish the mechanical equivalent of heat, a key foundation for the law of conservation of energy?", "James Joule", ["Isaac Newton", "Michael Faraday", "Joseph Black"]),
  mc("expert", "In quantum mechanics, what is the name of the principle stating that the position and momentum of a particle cannot both be precisely known?", "Heisenberg uncertainty principle", ["Pauli exclusion principle", "Planck's constant theorem", "Born rule approximation"]),
  mc("expert", "What is the name of the protein that carries oxygen in red blood cells?", "Hemoglobin", ["Myoglobin", "Cytochrome c", "Ferritin"]),
];
