import { mc } from "./seed";
import type { QuestionSeed } from "./seed";

export const SPACE_SEEDS: QuestionSeed[] = [
  mc("easy", "How many planets are in our solar system?", "8", ["9", "7", "10"]),
  mc("easy", "What is the closest star to Earth?", "The Sun", ["Proxima Centauri", "Alpha Centauri", "Sirius"]),
  mc("easy", "Which planet is known as the Red Planet?", "Mars", ["Venus", "Jupiter", "Mercury"]),
  mc("easy", "What is the name of Earth's natural satellite?", "Moon", ["Titan", "Europa", "Phobos"]),
  mc("easy", "Which is the largest planet in our solar system?", "Jupiter", ["Saturn", "Neptune", "Uranus"]),
  mc("easy", "What is the name of the galaxy we live in?", "Milky Way", ["Andromeda", "Triangulum", "Whirlpool"]),
  mc("easy", "Which planet has rings?", "Saturn", ["Jupiter", "Uranus", "Neptune"]),
  mc("easy", "What is a shooting star made of?", "Meteors (space debris burning up)", ["Gas", "Ice", "Light from distant stars"]),
  mc("easy", "How long does it take Earth to orbit the Sun?", "365.25 days", ["360 days", "400 days", "300 days"]),
  mc("easy", "What is the name of NASA's famous space telescope launched in 1990?", "Hubble Space Telescope", ["James Webb Telescope", "Chandra X-ray", "Spitzer"]),
  mc("easy", "Which planet is closest to the Sun?", "Mercury", ["Venus", "Earth", "Mars"]),
  mc("easy", "What is the force that keeps planets in orbit around the Sun?", "Gravity", ["Magnetism", "Nuclear force", "Inertia"]),
  mc("easy", "Who was the first human in space?", "Yuri Gagarin", ["Neil Armstrong", "Alan Shepard", "Buzz Aldrin"]),
  mc("easy", "What is the name of the first space station?", "Salyut 1", ["Mir", "ISS", "Skylab"]),
  mc("easy", "Which planet has the most moons?", "Saturn", ["Jupiter", "Uranus", "Neptune"]),
  mc("easy", "What are the tiny pieces of rock and dust that orbit the Sun called?", "Asteroids", ["Comets", "Meteorites", "Dwarf planets"]),
  mc("easy", "What is the Sun made mostly of?", "Hydrogen and helium", ["Carbon and oxygen", "Iron and nickel", "Nitrogen and oxygen"]),
  mc("easy", "Which planet is smallest in our solar system?", "Mercury", ["Mars", "Pluto", "Venus"]),
  mc("easy", "What do you call a star that has exploded?", "Supernova", ["Black hole", "Pulsar", "Nebula"]),
  mc("easy", "In what year did humans first land on the Moon?", "1969", ["1967", "1971", "1965"]),
  mc("medium", "What is the name of the closest galaxy to the Milky Way?", "Andromeda Galaxy", ["Large Magellanic Cloud", "Triangulum Galaxy", "Centaurus A"]),
  mc("medium", "How many Earth days is one day on Venus?", "243 Earth days", ["50 days", "120 days", "365 days"]),
  mc("medium", "What is the Great Red Spot on Jupiter?", "A giant storm", ["A volcanic region", "An impact crater", "A frozen ocean"]),
  mc("medium", "Which planet has the highest surface temperature?", "Venus", ["Mercury", "Mars", "Jupiter"]),
  mc("medium", "What is a light-year a measure of?", "Distance", ["Time", "Speed", "Brightness"]),
  mc("medium", "What is the name of Mars' largest volcano?", "Olympus Mons", ["Mons Huygens", "Maxwell Montes", "Arsia Mons"]),
  mc("medium", "What is the term for the point of no return around a black hole?", "Event horizon", ["Singularity", "Schwarzschild radius", "Photon sphere"]),
  mc("medium", "Which space mission first landed on Mars?", "Viking 1 (1976)", ["Mars Pathfinder", "Curiosity", "Spirit"]),
  mc("medium", "What is the name of the dark matter that makes up most of the universe?", "Dark matter", ["Anti-matter", "Dark energy", "Neutrinos"]),
  mc("medium", "How far is the Moon from Earth in kilometres?", "384,400 km", ["150,000 km", "700,000 km", "1,000,000 km"]),
  mc("medium", "What is the name of the spacecraft that first left the solar system?", "Voyager 1", ["Pioneer 10", "New Horizons", "Voyager 2"]),
  mc("medium", "Which planet rotates on its side?", "Uranus", ["Venus", "Saturn", "Neptune"]),
  mc("medium", "What is the Kuiper Belt?", "A region of the solar system beyond Neptune containing icy bodies", ["A ring around Saturn", "The asteroid belt between Mars and Jupiter", "A cloud of comets around the solar system"]),
  mc("medium", "How many Earth-sized planets could fit inside Jupiter?", "About 1,300", ["100", "500", "11"]),
  mc("medium", "What is the name of the current Mars rover still active as of 2024?", "Perseverance", ["Curiosity", "Spirit", "Opportunity"]),
  mc("hard", "What is the approximate age of the Sun?", "4.6 billion years", ["1 billion years", "10 billion years", "2 billion years"]),
  mc("hard", "What is the name of the theoretical boundary at the end of the observable universe?", "Cosmic horizon", ["Event horizon", "Hubble sphere", "Light cone"]),
  mc("hard", "What is the second most abundant element in the universe?", "Helium", ["Oxygen", "Carbon", "Hydrogen"]),
  mc("hard", "Which moon of Jupiter is thought to have a subsurface ocean?", "Europa", ["Io", "Ganymede", "Callisto"]),
  mc("hard", "What is the name of the force causing the universe to expand faster?", "Dark energy", ["Dark matter", "Gravity", "Cosmic inflation"]),
  mc("hard", "What is the diameter of the Milky Way in light-years, approximately?", "100,000 light-years", ["50,000 light-years", "1 million light-years", "10,000 light-years"]),
  mc("hard", "What is the name of the first space telescope to use infrared to see through dust clouds?", "Spitzer Space Telescope", ["Hubble", "James Webb", "Chandra"]),
  mc("hard", "What is the Chandrasekhar limit?", "The maximum mass a white dwarf star can have", ["The minimum size of a neutron star", "The speed at which light escapes a black hole", "The temperature at which fusion starts"]),
  mc("hard", "Which planet has the fastest winds in the solar system?", "Neptune", ["Jupiter", "Saturn", "Uranus"]),
  mc("hard", "What is the name of the region between Mars and Jupiter filled with rocky objects?", "Asteroid Belt", ["Kuiper Belt", "Oort Cloud", "Zodiacal Cloud"]),
  mc("expert", "What is the name of the process that powers the Sun?", "Nuclear fusion", ["Nuclear fission", "Combustion", "Plasma convection"]),
  mc("expert", "What is the approximate distance from Earth to the Sun in astronomical units?", "1 AU (149.6 million km)", ["0.5 AU", "2 AU", "1.5 AU"]),
  mc("expert", "Which moon of Saturn has a thick atmosphere and lakes of liquid methane?", "Titan", ["Enceladus", "Mimas", "Rhea"]),
  mc("expert", "What is the name of the mathematical model describing the Big Bang's early rapid expansion?", "Cosmic inflation", ["Steady-state theory", "Big Crunch", "Oscillating universe"]),
  mc("expert", "What is the Oort Cloud?", "A hypothetical shell of icy bodies surrounding the solar system", ["A dust ring around a black hole", "A cloud of gas around the Milky Way", "Dark matter surrounding our galaxy"]),
  mc("expert", "What year did the James Webb Space Telescope launch?", "2021", ["2019", "2023", "2018"]),
  mc("expert", "What is the name of the first exoplanet confirmed to orbit a sun-like star?", "51 Pegasi b", ["HD 209458 b", "Kepler-22b", "Proxima b"]),
  mc("expert", "What is the escape velocity of Earth?", "11.2 km/s", ["7.9 km/s", "15 km/s", "9.8 km/s"]),
  mc("expert", "What is a magnetar?", "A neutron star with an extremely strong magnetic field", ["A type of black hole", "A collapsed white dwarf", "A binary star system"]),
  mc("expert", "How many times larger is the Sun's diameter than Earth's?", "About 109 times", ["About 50 times", "About 200 times", "About 75 times"]),
  mc("easy", "How many planets are in our Solar System?", "8", ["9", "10", "7"]),
  mc("easy", "Which planet is the largest in our Solar System?", "Jupiter", ["Saturn", "Neptune", "Uranus"]),
  mc("medium", "What is the name of the region of icy bodies beyond Neptune's orbit?", "Kuiper Belt", ["Oort Cloud", "Asteroid Belt", "Heliosphere"]),
  mc("medium", "Which spacecraft was the first to land humans on the Moon?", "Apollo 11", ["Apollo 10", "Skylab 1", "Gemini 8"]),
  mc("medium", "What is the term for the explosive death of a massive star?", "Supernova", ["Pulsar", "Quasar", "Black hole"]),
  mc("medium", "Which gas makes up most of the Sun's composition?", "Hydrogen", ["Helium", "Oxygen", "Nitrogen"]),
  mc("medium", "What is the name of Saturn's largest moon?", "Titan", ["Enceladus", "Iapetus", "Rhea"]),
  mc("hard", "What is the Chandrasekhar limit related to?", "Maximum mass of a white dwarf", ["Size of event horizons", "Temperature of neutron stars", "Age of black holes"]),
  mc("hard", "Which moon of Jupiter shows evidence of a subsurface ocean?", "Europa", ["Io", "Ganymede", "Callisto"]),
  mc("hard", "What is the name of the boundary around a black hole beyond which nothing can escape?", "Event horizon", ["Singularity", "Photon sphere", "Schwarzschild radius"]),
  mc("expert", "What is the current estimated age of the universe?", "13.8 billion years", ["9.2 billion years", "18.5 billion years", "11.3 billion years"]),
  mc("expert", "What phenomenon causes the redshift observed in distant galaxies moving away from us?", "Cosmic expansion", ["Gravitational lensing", "Doppler effect alone", "Interstellar dust absorption"]),
  mc("easy", "What is the Sun primarily made of?", "Hydrogen and helium", ["Oxygen and nitrogen", "Iron and nickel", "Carbon and silicon"]),
  mc("medium", "What is the closest star to our Sun?", "Proxima Centauri", ["Sirius", "Betelgeuse", "Alpha Centauri A"]),
  mc("medium", "Which space agency successfully landed the Perseverance rover on Mars?", "NASA", ["ESA", "Roscosmos", "CNSA"]),
  mc("medium", "What phenomenon describes the bending of light around a massive object?", "Gravitational lensing", ["Doppler shift", "Refraction", "Diffraction"]),
  mc("hard", "What is the escape velocity from Earth's surface?", "11.2 km/s", ["7.8 km/s", "15.3 km/s", "9.1 km/s"]),
  mc("hard", "Which dwarf planet was reclassified in 2006, no longer considered a full planet?", "Pluto", ["Eris", "Ceres", "Makemake"]),
  mc("expert", "What is the name of the hypothetical region surrounding a star where liquid water could exist on a planet's surface?", "The habitable zone", ["The Oort cloud", "The photosphere", "The exosphere"]),
  mc("expert", "Which space telescope, launched in 2021, is named after a famous astronomer?", "James Webb Space Telescope", ["Kepler Space Telescope", "Hubble Space Telescope", "Spitzer Space Telescope"]),
  mc("easy", "What is the closest planet to the Sun?", "Mercury", ["Venus", "Earth", "Mars"]),
  mc("easy", "How many moons does Mars have?", "2", ["0", "1", "4"]),
  mc("easy", "What do we call a star system with two stars orbiting each other?", "Binary star system", ["Dual constellation", "Double nebula", "Twin galaxy"]),
  mc("medium", "Which planet has the most prominent ring system?", "Saturn", ["Jupiter", "Uranus", "Neptune"]),
  mc("medium", "What is the name of the spacecraft that recently landed on Mars in 2021?", "Perseverance", ["Curiosity", "Opportunity", "Spirit"]),
  mc("medium", "How long does it take light from the Sun to reach Earth?", "About 8 minutes", ["About 2 minutes", "About 15 minutes", "About 1 minute"]),
  mc("medium", "What is the name of the giant cloud of gas and dust where stars form?", "Nebula", ["Pulsar", "Quasar", "Supernova"]),
  mc("medium", "Which space agency launched the Hubble Space Telescope?", "NASA", ["ESA", "Roscosmos", "JAXA"]),
  mc("hard", "How many Galilean moons does Jupiter have?", "4", ["16", "79", "8"]),
  mc("hard", "Which exoplanet was the first confirmed discovery around a Sun-like star?", "51 Pegasi b", ["Proxima Centauri b", "TRAPPIST-1e", "Kepler-452b"]),
  mc("expert", "What is the Chandrasekhar limit approximately equal to in solar masses?", "1.4", ["2.8", "0.7", "3.2"]),
  mc("expert", "Which dwarf planet was discovered by Eris in the Kuiper Belt in 2005?", "Eris", ["Pluto", "Haumea", "Makemake"]),
  mc("easy", "How many moons does Earth have?", "One", ["Two", "Three", "None"]),
  mc("easy", "What is the name of the closest star to Earth besides the Sun?", "Proxima Centauri", ["Sirius", "Betelgeuse", "Polaris"]),
  mc("easy", "What does NASA stand for?", "National Aeronautics and Space Administration", ["National Aerospace and Space Agency", "National Air and Space Authority", "National Astronaut and Science Association"]),
  mc("medium", "Which space agency successfully landed the first rover on Mars?", "Soviet Union", ["NASA", "European Space Agency", "China National Space Administration"]),
  mc("medium", "What is the name of the supermassive black hole at the center of the Milky Way?", "Sagittarius A*", ["Cygnus X-1", "M87*", "Andromeda Prime"]),
  mc("medium", "In what year did the Hubble Space Telescope launch?", "1990", ["1985", "1995", "2000"]),
  mc("medium", "How many rings does Saturn have?", "At least 83", ["7", "42", "18"]),
  mc("medium", "What is the second-brightest star visible from Earth?", "Canopus", ["Arcturus", "Vega", "Capella"]),
  mc("hard", "What is the Chandrasekhar limit the maximum mass for?", "White dwarf stars", ["Neutron stars", "Main sequence stars", "Red giants"]),
  mc("hard", "Which Galilean moon of Jupiter has the most geological activity?", "Io", ["Europa", "Ganymede", "Callisto"]),
  mc("hard", "What phenomenon causes the blueshifting of light from an approaching celestial object?", "Doppler effect", ["Gravitational lensing", "Parallax", "Aberration"]),
  mc("expert", "Which exoplanet, discovered in 1995, was the first to orbit a Sun-like star?", "51 Pegasi b", ["TRAPPIST-1e", "Proxima Centauri b", "Kepler-452b"]),
  mc("medium", "What is the name of the spacecraft that first landed humans on the Moon?", "Apollo 11", ["Gemini 7", "Skylab 1", "Space Shuttle Columbia"]),
  mc("medium", "Which dwarf planet was reclassified in 2006 by the International Astronomical Union?", "Pluto", ["Eris", "Haumea", "Makemake"]),
];
