import { mc } from "./seed";
import type { QuestionSeed } from "./seed";

export const SPACE_SEEDS: QuestionSeed[] = [
  mc("easy", "How many planets are in our solar system?", "8", ["9", "7", "10"]),
  mc("easy", "What is the closest star to Earth?", "The Sun", ["Proxima Centauri", "Alpha Centauri", "Sirius"]),
  mc("easy", "Which planet is known as the Red Planet?", "Mars", ["Venus", "Jupiter", "Mercury"]),
  mc("easy", "What is the name of Earth's natural satellite?", "Moon", ["Titan", "Europa", "Phobos"]),
  mc("easy", "Which is the largest planet in our solar system?", "Jupiter", ["Saturn", "Neptune", "Uranus"]),
  mc("easy", "What is the name of the galaxy we live in?", "Milky Way", ["Andromeda", "Triangulum", "Whirlpool"]),
  mc("easy", "Which planet has rings?", "Saturn", ["Jupiter", "Uranus", "Neptune"]),
  mc("easy", "What is a shooting star made of?", "Meteors (space debris burning up)", ["Gas", "Ice", "Light from distant stars"]),
  mc("easy", "How long does it take Earth to orbit the Sun?", "365.25 days", ["360 days", "400 days", "300 days"]),
  mc("easy", "What is the name of NASA's famous space telescope launched in 1990?", "Hubble Space Telescope", ["James Webb Telescope", "Chandra X-ray", "Spitzer"]),
  mc("easy", "Which planet is closest to the Sun?", "Mercury", ["Venus", "Earth", "Mars"]),
  mc("easy", "What is the force that keeps planets in orbit around the Sun?", "Gravity", ["Magnetism", "Nuclear force", "Inertia"]),
  mc("easy", "Who was the first human in space?", "Yuri Gagarin", ["Neil Armstrong", "Alan Shepard", "Buzz Aldrin"]),
  mc("easy", "What is the name of the first space station?", "Salyut 1", ["Mir", "ISS", "Skylab"]),
  mc("easy", "Which planet has the most moons?", "Saturn", ["Jupiter", "Uranus", "Neptune"]),
  mc("easy", "What are the tiny pieces of rock and dust that orbit the Sun called?", "Asteroids", ["Comets", "Meteorites", "Dwarf planets"]),
  mc("easy", "What is the Sun made mostly of?", "Hydrogen and helium", ["Carbon and oxygen", "Iron and nickel", "Nitrogen and oxygen"]),
  mc("easy", "Which planet is smallest in our solar system?", "Mercury", ["Mars", "Pluto", "Venus"]),
  mc("easy", "What do you call a star that has exploded?", "Supernova", ["Black hole", "Pulsar", "Nebula"]),
  mc("easy", "In what year did humans first land on the Moon?", "1969", ["1967", "1971", "1965"]),
  mc("medium", "What is the name of the closest galaxy to the Milky Way?", "Andromeda Galaxy", ["Large Magellanic Cloud", "Triangulum Galaxy", "Centaurus A"]),
  mc("medium", "How many Earth days is one day on Venus?", "243 Earth days", ["50 days", "120 days", "365 days"]),
  mc("medium", "What is the Great Red Spot on Jupiter?", "A giant storm", ["A volcanic region", "An impact crater", "A frozen ocean"]),
  mc("medium", "Which planet has the highest surface temperature?", "Venus", ["Mercury", "Mars", "Jupiter"]),
  mc("medium", "What is a light-year a measure of?", "Distance", ["Time", "Speed", "Brightness"]),
  mc("medium", "What is the name of Mars' largest volcano?", "Olympus Mons", ["Mons Huygens", "Maxwell Montes", "Arsia Mons"]),
  mc("medium", "What is the term for the point of no return around a black hole?", "Event horizon", ["Singularity", "Schwarzschild radius", "Photon sphere"]),
  mc("medium", "Which space mission first landed on Mars?", "Viking 1 (1976)", ["Mars Pathfinder", "Curiosity", "Spirit"]),
  mc("medium", "What is the name of the dark matter that makes up most of the universe?", "Dark matter", ["Anti-matter", "Dark energy", "Neutrinos"]),
  mc("medium", "How far is the Moon from Earth in kilometres?", "384,400 km", ["150,000 km", "700,000 km", "1,000,000 km"]),
  mc("medium", "What is the name of the spacecraft that first left the solar system?", "Voyager 1", ["Pioneer 10", "New Horizons", "Voyager 2"]),
  mc("medium", "Which planet rotates on its side?", "Uranus", ["Venus", "Saturn", "Neptune"]),
  mc("medium", "What is the Kuiper Belt?", "A region of the solar system beyond Neptune containing icy bodies", ["A ring around Saturn", "The asteroid belt between Mars and Jupiter", "A cloud of comets around the solar system"]),
  mc("medium", "How many Earth-sized planets could fit inside Jupiter?", "About 1,300", ["100", "500", "11"]),
  mc("medium", "What is the name of the current Mars rover still active as of 2024?", "Perseverance", ["Curiosity", "Spirit", "Opportunity"]),
  mc("hard", "What is the approximate age of the Sun?", "4.6 billion years", ["1 billion years", "10 billion years", "2 billion years"]),
  mc("hard", "What is the name of the theoretical boundary at the end of the observable universe?", "Cosmic horizon", ["Event horizon", "Hubble sphere", "Light cone"]),
  mc("hard", "What is the second most abundant element in the universe?", "Helium", ["Oxygen", "Carbon", "Hydrogen"]),
  mc("hard", "Which moon of Jupiter is thought to have a subsurface ocean?", "Europa", ["Io", "Ganymede", "Callisto"]),
  mc("hard", "What is the name of the force causing the universe to expand faster?", "Dark energy", ["Dark matter", "Gravity", "Cosmic inflation"]),
  mc("hard", "What is the diameter of the Milky Way in light-years, approximately?", "100,000 light-years", ["50,000 light-years", "1 million light-years", "10,000 light-years"]),
  mc("hard", "What is the name of the first space telescope to use infrared to see through dust clouds?", "Spitzer Space Telescope", ["Hubble", "James Webb", "Chandra"]),
  mc("hard", "What is the Chandrasekhar limit?", "The maximum mass a white dwarf star can have", ["The minimum size of a neutron star", "The speed at which light escapes a black hole", "The temperature at which fusion starts"]),
  mc("hard", "Which planet has the fastest winds in the solar system?", "Neptune", ["Jupiter", "Saturn", "Uranus"]),
  mc("hard", "What is the name of the region between Mars and Jupiter filled with rocky objects?", "Asteroid Belt", ["Kuiper Belt", "Oort Cloud", "Zodiacal Cloud"]),
  mc("expert", "What is the name of the process that powers the Sun?", "Nuclear fusion", ["Nuclear fission", "Combustion", "Plasma convection"]),
  mc("expert", "What is the approximate distance from Earth to the Sun in astronomical units?", "1 AU (149.6 million km)", ["0.5 AU", "2 AU", "1.5 AU"]),
  mc("expert", "Which moon of Saturn has a thick atmosphere and lakes of liquid methane?", "Titan", ["Enceladus", "Mimas", "Rhea"]),
  mc("expert", "What is the name of the mathematical model describing the Big Bang's early rapid expansion?", "Cosmic inflation", ["Steady-state theory", "Big Crunch", "Oscillating universe"]),
  mc("expert", "What is the Oort Cloud?", "A hypothetical shell of icy bodies surrounding the solar system", ["A dust ring around a black hole", "A cloud of gas around the Milky Way", "Dark matter surrounding our galaxy"]),
  mc("expert", "What year did the James Webb Space Telescope launch?", "2021", ["2019", "2023", "2018"]),
  mc("expert", "What is the name of the first exoplanet confirmed to orbit a sun-like star?", "51 Pegasi b", ["HD 209458 b", "Kepler-22b", "Proxima b"]),
  mc("expert", "What is the escape velocity of Earth?", "11.2 km/s", ["7.9 km/s", "15 km/s", "9.8 km/s"]),
  mc("expert", "What is a magnetar?", "A neutron star with an extremely strong magnetic field", ["A type of black hole", "A collapsed white dwarf", "A binary star system"]),
  mc("expert", "How many times larger is the Sun's diameter than Earth's?", "About 109 times", ["About 50 times", "About 200 times", "About 75 times"]),
];
