import { mc } from "./seed";
import type { QuestionSeed } from "./seed";

export const SPORTS_SEEDS: QuestionSeed[] = [
  // ── easy ──────────────────────────────────────────────────────────────────
  mc("easy", "How many players are on a basketball court for one team at a time?", "5", ["6", "7", "4"]),
  mc("easy", "How many players are on a soccer team on the field at once?", "11", ["10", "9", "12"]),
  mc("easy", "In bowling, what is a perfect game's score?", "300", ["250", "200", "350"]),
  mc("easy", "What sport is played at Wimbledon?", "Tennis", ["Cricket", "Golf", "Badminton"]),
  mc("easy", "How many holes are on a standard golf course?", "18", ["16", "20", "12"]),
  mc("easy", "How many points is a touchdown worth in American football?", "6", ["7", "3", "10"]),
  mc("easy", "Which sport uses a shuttlecock?", "Badminton", ["Tennis", "Squash", "Table tennis"]),
  mc("easy", "How many periods are in a standard ice hockey game?", "3", ["2", "4", "5"]),
  mc("easy", "What is the maximum score for a single dart throw?", "60", ["50", "40", "100"]),
  mc("easy", "How many rings are on the Olympic flag?", "5", ["4", "6", "7"]),
  mc("easy", "In baseball, how many strikes make an out?", "3", ["2", "4", "5"]),
  mc("easy", "How many players are on each side in volleyball?", "6", ["5", "7", "4"]),
  mc("easy", "What colour jersey is worn by the leader of the Tour de France?", "Yellow", ["Red", "Green", "White"]),
  mc("easy", "What sport is played on a court with a net and a birdie?", "Badminton", ["Tennis", "Squash", "Pickleball"]),
  mc("easy", "How many points does a field goal score in American football?", "3", ["1", "2", "6"]),
  mc("easy", "In which sport would you perform a slam dunk?", "Basketball", ["Volleyball", "Water polo", "Handball"]),
  mc("easy", "What sport uses a puck?", "Ice hockey", ["Lacrosse", "Field hockey", "Polo"]),
  mc("easy", "How many innings are in a standard baseball game?", "9", ["7", "8", "10"]),
  mc("easy", "Which country invented basketball?", "United States", ["Canada", "Brazil", "England"]),
  mc("easy", "What is the term for scoring three consecutive strikes in bowling?", "Turkey", ["Hat trick", "Triple", "Perfect run"]),
  mc("easy", "In tennis, what is the score called when both players are at 40-40?", "Deuce", ["Tie", "Draw", "Level"]),
  mc("easy", "How long is an Olympic swimming pool in metres?", "50", ["25", "100", "75"]),
  mc("easy", "Which sport features a 'pommel horse'?", "Gymnastics", ["Equestrian", "Polo", "Hurdles"]),
  mc("easy", "In what sport would you do a 'free throw'?", "Basketball", ["Soccer", "Water polo", "Handball"]),
  mc("easy", "What is the name for a score of one under par in golf?", "Birdie", ["Eagle", "Bogey", "Par"]),

  // ── medium ────────────────────────────────────────────────────────────────
  mc("medium", "How many Grand Slam tennis tournaments are there per year?", "4", ["3", "5", "6"]),
  mc("medium", "In what year were the first modern Olympic Games held?", "1896", ["1900", "1888", "1920"]),
  mc("medium", "Which country has won the most FIFA World Cups?", "Brazil", ["Germany", "Argentina", "Italy"]),
  mc("medium", "What is the term for scoring three goals in one soccer match?", "Hat trick", ["Triple play", "Grand slam", "Treble"]),
  mc("medium", "Which boxing weight class is heaviest?", "Heavyweight", ["Middleweight", "Welterweight", "Cruiserweight"]),
  mc("medium", "How long is a marathon in miles, approximately?", "26.2", ["20", "30", "24"]),
  mc("medium", "Which country invented table tennis?", "England", ["China", "Japan", "Germany"]),
  mc("medium", "What is the distance of a standard 100m sprint in feet, roughly?", "328 feet", ["200 feet", "500 feet", "150 feet"]),
  mc("medium", "In rugby union, how many players are on each team?", "15", ["13", "11", "17"]),
  mc("medium", "What is the name for a score of two under par in golf?", "Eagle", ["Birdie", "Albatross", "Condor"]),
  mc("medium", "Which sport uses the term 'love' to mean zero?", "Tennis", ["Badminton", "Squash", "Volleyball"]),
  mc("medium", "How many events are in a decathlon?", "10", ["7", "8", "12"]),
  mc("medium", "What is the height of a regulation basketball hoop in feet?", "10", ["8", "12", "9"]),
  mc("medium", "In swimming, which stroke is the fastest?", "Freestyle (front crawl)", ["Butterfly", "Backstroke", "Breaststroke"]),
  mc("medium", "Which sport features a 'penalty shootout'?", "Soccer", ["Rugby", "Basketball", "Ice hockey"]),
  mc("medium", "How many cards are shown in soccer before a player is sent off?", "2 yellow or 1 red", ["3 yellow", "2 red", "1 yellow"]),
  mc("medium", "In which country did sumo wrestling originate?", "Japan", ["China", "South Korea", "Mongolia"]),
  mc("medium", "What is the regulation weight of a soccer ball in grams?", "410–450g", ["300–350g", "500–550g", "250–280g"]),
  mc("medium", "How many players are on a cricket team?", "11", ["9", "12", "10"]),
  mc("medium", "What do you call the line behind which a quarterback throws in American football?", "Line of scrimmage", ["Touchdown line", "Red zone", "Neutral zone"]),
  mc("medium", "In what year did the first FIFA World Cup take place?", "1930", ["1926", "1934", "1922"]),
  mc("medium", "How many sets must a player win to win a men's Grand Slam tennis match?", "3", ["2", "4", "5"]),
  mc("medium", "What sport is the Super Bowl associated with?", "American football", ["Rugby", "Basketball", "Baseball"]),
  mc("medium", "In which city are the Los Angeles Lakers based?", "Los Angeles", ["San Francisco", "Las Vegas", "San Diego"]),
  mc("medium", "What is the name of the trophy awarded to the winner of ice hockey's NHL?", "Stanley Cup", ["Presidents' Trophy", "Hart Trophy", "Conn Smythe"]),

  // ── hard ──────────────────────────────────────────────────────────────────
  mc("hard", "Who holds the record for most career home runs in MLB history?", "Barry Bonds", ["Babe Ruth", "Hank Aaron", "Alex Rodriguez"]),
  mc("hard", "Which tennis player has won the most Grand Slam singles titles (men's)?", "Novak Djokovic", ["Roger Federer", "Rafael Nadal", "Pete Sampras"]),
  mc("hard", "What is the diameter of a basketball hoop in inches?", "18", ["16", "20", "15"]),
  mc("hard", "Which NFL team won the very first Super Bowl?", "Green Bay Packers", ["Dallas Cowboys", "Kansas City Chiefs", "Oakland Raiders"]),
  mc("hard", "In cricket, how many runs is a 'six' worth?", "6", ["4", "5", "8"]),
  mc("hard", "Which country hosted the first FIFA World Cup in 1930?", "Uruguay", ["Brazil", "Italy", "France"]),
  mc("hard", "Which athlete won 9 Olympic gold medals at the 2008 Beijing Games?", "Michael Phelps", ["Usain Bolt", "Carl Lewis", "Mark Spitz"]),
  mc("hard", "What is the only country to have competed in every modern Olympics?", "Greece", ["United States", "France", "Great Britain"]),
  mc("hard", "In F1, what flag is waved to indicate danger on the track?", "Yellow flag", ["Red flag", "Blue flag", "White flag"]),
  mc("hard", "How many dimples are on a regulation golf ball, approximately?", "336", ["100", "500", "250"]),
  mc("hard", "Which player scored the most points in a single NBA game?", "Wilt Chamberlain", ["Kobe Bryant", "LeBron James", "Michael Jordan"]),
  mc("hard", "What is the length of an Olympic swimming race called the 'mile'?", "1500m", ["1600m", "1000m", "2000m"]),
  mc("hard", "In which year did Tiger Woods win his first Masters title?", "1997", ["1999", "2001", "1995"]),
  mc("hard", "Which team has won the most UEFA Champions League titles?", "Real Madrid", ["AC Milan", "Barcelona", "Bayern Munich"]),
  mc("hard", "What is the fastest recorded tennis serve speed in km/h?", "263 km/h", ["220 km/h", "300 km/h", "245 km/h"]),

  // ── expert ────────────────────────────────────────────────────────────────
  mc("expert", "Who was the first gymnast to score a perfect 10 in Olympic competition?", "Nadia Comăneci", ["Olga Korbut", "Simone Biles", "Mary Lou Retton"]),
  mc("expert", "Roughly how much longer is a marathon than 26 miles, in yards?", "385 yards", ["100 yards", "880 yards", "1 mile"]),
  mc("expert", "Which jockey won the Kentucky Derby five times, first achieved in 1952?", "Eddie Arcaro", ["Willie Shoemaker", "Calvin Borel", "Victor Espinoza"]),
  mc("expert", "In what year did the first Super Bowl take place?", "1967", ["1965", "1970", "1960"]),
  mc("expert", "Which boxer was known as 'The Real Deal'?", "Evander Holyfield", ["Lennox Lewis", "George Foreman", "Larry Holmes"]),
  mc("expert", "What is the exact distance of a standard horse racing furlong in metres?", "201.168m", ["150m", "250m", "175m"]),
  mc("expert", "Who is the only player to win the Ballon d'Or eight times?", "Lionel Messi", ["Cristiano Ronaldo", "Zinedine Zidane", "Ronaldo Nazário"]),
  mc("expert", "In what year were women first allowed to compete in the modern Olympics?", "1900", ["1908", "1920", "1896"]),
  mc("expert", "Which country has won the most Rugby World Cups?", "New Zealand", ["South Africa", "England", "Australia"]),
  mc("expert", "What is the maximum break in snooker?", "147", ["155", "100", "180"]),
];
