import { mc } from "./seed";
import type { QuestionSeed } from "./seed";

export const SPORTS_SEEDS: QuestionSeed[] = [
  // ── easy ──────────────────────────────────────────────────────────────────
  mc("easy", "How many players are on a basketball court for one team at a time?", "5", ["6", "7", "4"]),
  mc("easy", "How many players are on a soccer team on the field at once?", "11", ["10", "9", "12"]),
  mc("easy", "In bowling, what is a perfect game's score?", "300", ["250", "200", "350"]),
  mc("easy", "What sport is played at Wimbledon?", "Tennis", ["Cricket", "Golf", "Badminton"]),
  mc("easy", "How many holes are on a standard golf course?", "18", ["16", "20", "12"]),
  mc("easy", "How many points is a touchdown worth in American football?", "6", ["7", "3", "10"]),
  mc("easy", "Which sport uses a shuttlecock?", "Badminton", ["Tennis", "Squash", "Table tennis"]),
  mc("easy", "How many periods are in a standard ice hockey game?", "3", ["2", "4", "5"]),
  mc("easy", "What is the maximum score for a single dart throw?", "60", ["50", "40", "100"]),
  mc("easy", "How many rings are on the Olympic flag?", "5", ["4", "6", "7"]),
  mc("easy", "In baseball, how many strikes make an out?", "3", ["2", "4", "5"]),
  mc("easy", "How many players are on each side in volleyball?", "6", ["5", "7", "4"]),
  mc("easy", "What colour jersey is worn by the leader of the Tour de France?", "Yellow", ["Red", "Green", "White"]),
  mc("easy", "What sport is played on a court with a net and a birdie?", "Badminton", ["Tennis", "Squash", "Pickleball"]),
  mc("easy", "How many points does a field goal score in American football?", "3", ["1", "2", "6"]),
  mc("easy", "In which sport would you perform a slam dunk?", "Basketball", ["Volleyball", "Water polo", "Handball"]),
  mc("easy", "What sport uses a puck?", "Ice hockey", ["Lacrosse", "Field hockey", "Polo"]),
  mc("easy", "How many innings are in a standard baseball game?", "9", ["7", "8", "10"]),
  mc("easy", "Which country invented basketball?", "United States", ["Canada", "Brazil", "England"]),
  mc("easy", "What is the term for scoring three consecutive strikes in bowling?", "Turkey", ["Hat trick", "Triple", "Perfect run"]),
  mc("easy", "In tennis, what is the score called when both players are at 40-40?", "Deuce", ["Tie", "Draw", "Level"]),
  mc("easy", "How long is an Olympic swimming pool in metres?", "50", ["25", "100", "75"]),
  mc("easy", "Which sport features a 'pommel horse'?", "Gymnastics", ["Equestrian", "Polo", "Hurdles"]),
  mc("easy", "In what sport would you do a 'free throw'?", "Basketball", ["Soccer", "Water polo", "Handball"]),
  mc("easy", "What is the name for a score of one under par in golf?", "Birdie", ["Eagle", "Bogey", "Par"]),

  // ── medium ────────────────────────────────────────────────────────────────
  mc("medium", "How many Grand Slam tennis tournaments are there per year?", "4", ["3", "5", "6"]),
  mc("medium", "In what year were the first modern Olympic Games held?", "1896", ["1900", "1888", "1920"]),
  mc("medium", "Which country has won the most FIFA World Cups?", "Brazil", ["Germany", "Argentina", "Italy"]),
  mc("medium", "What is the term for scoring three goals in one soccer match?", "Hat trick", ["Triple play", "Grand slam", "Treble"]),
  mc("medium", "Which boxing weight class is heaviest?", "Heavyweight", ["Middleweight", "Welterweight", "Cruiserweight"]),
  mc("medium", "How long is a marathon in miles, approximately?", "26.2", ["20", "30", "24"]),
  mc("medium", "Which country invented table tennis?", "England", ["China", "Japan", "Germany"]),
  mc("medium", "What is the distance of a standard 100m sprint in feet, roughly?", "328 feet", ["200 feet", "500 feet", "150 feet"]),
  mc("medium", "In rugby union, how many players are on each team?", "15", ["13", "11", "17"]),
  mc("medium", "What is the name for a score of two under par in golf?", "Eagle", ["Birdie", "Albatross", "Condor"]),
  mc("medium", "Which sport uses the term 'love' to mean zero?", "Tennis", ["Badminton", "Squash", "Volleyball"]),
  mc("medium", "How many events are in a decathlon?", "10", ["7", "8", "12"]),
  mc("medium", "What is the height of a regulation basketball hoop in feet?", "10", ["8", "12", "9"]),
  mc("medium", "In swimming, which stroke is the fastest?", "Freestyle (front crawl)", ["Butterfly", "Backstroke", "Breaststroke"]),
  mc("medium", "Which sport features a 'penalty shootout'?", "Soccer", ["Rugby", "Basketball", "Ice hockey"]),
  mc("medium", "How many cards are shown in soccer before a player is sent off?", "2 yellow or 1 red", ["3 yellow", "2 red", "1 yellow"]),
  mc("medium", "In which country did sumo wrestling originate?", "Japan", ["China", "South Korea", "Mongolia"]),
  mc("medium", "What is the regulation weight of a soccer ball in grams?", "410–450g", ["300–350g", "500–550g", "250–280g"]),
  mc("medium", "How many players are on a cricket team?", "11", ["9", "12", "10"]),
  mc("medium", "What do you call the line behind which a quarterback throws in American football?", "Line of scrimmage", ["Touchdown line", "Red zone", "Neutral zone"]),
  mc("medium", "In what year did the first FIFA World Cup take place?", "1930", ["1926", "1934", "1922"]),
  mc("medium", "How many sets must a player win to win a men's Grand Slam tennis match?", "3", ["2", "4", "5"]),
  mc("medium", "What sport is the Super Bowl associated with?", "American football", ["Rugby", "Basketball", "Baseball"]),
  mc("medium", "In which city are the Los Angeles Lakers based?", "Los Angeles", ["San Francisco", "Las Vegas", "San Diego"]),
  mc("medium", "What is the name of the trophy awarded to the winner of ice hockey's NHL?", "Stanley Cup", ["Presidents' Trophy", "Hart Trophy", "Conn Smythe"]),

  // ── hard ──────────────────────────────────────────────────────────────────
  mc("hard", "Who holds the record for most career home runs in MLB history?", "Barry Bonds", ["Babe Ruth", "Hank Aaron", "Alex Rodriguez"]),
  mc("hard", "Which tennis player has won the most Grand Slam singles titles (men's)?", "Novak Djokovic", ["Roger Federer", "Rafael Nadal", "Pete Sampras"]),
  mc("hard", "What is the diameter of a basketball hoop in inches?", "18", ["16", "20", "15"]),
  mc("hard", "Which NFL team won the very first Super Bowl?", "Green Bay Packers", ["Dallas Cowboys", "Kansas City Chiefs", "Oakland Raiders"]),
  mc("hard", "In cricket, how many runs is a 'six' worth?", "6", ["4", "5", "8"]),
  mc("hard", "Which country hosted the first FIFA World Cup in 1930?", "Uruguay", ["Brazil", "Italy", "France"]),
  mc("hard", "Which athlete won 9 Olympic gold medals at the 2008 Beijing Games?", "Michael Phelps", ["Usain Bolt", "Carl Lewis", "Mark Spitz"]),
  mc("hard", "What is the only country to have competed in every modern Olympics?", "Greece", ["United States", "France", "Great Britain"]),
  mc("hard", "In F1, what flag is waved to indicate danger on the track?", "Yellow flag", ["Red flag", "Blue flag", "White flag"]),
  mc("hard", "How many dimples are on a regulation golf ball, approximately?", "336", ["100", "500", "250"]),
  mc("hard", "Which player scored the most points in a single NBA game?", "Wilt Chamberlain", ["Kobe Bryant", "LeBron James", "Michael Jordan"]),
  mc("hard", "What is the length of an Olympic swimming race called the 'mile'?", "1500m", ["1600m", "1000m", "2000m"]),
  mc("hard", "In which year did Tiger Woods win his first Masters title?", "1997", ["1999", "2001", "1995"]),
  mc("hard", "Which team has won the most UEFA Champions League titles?", "Real Madrid", ["AC Milan", "Barcelona", "Bayern Munich"]),
  mc("hard", "What is the fastest recorded tennis serve speed in km/h?", "263 km/h", ["220 km/h", "300 km/h", "245 km/h"]),

  // ── expert ────────────────────────────────────────────────────────────────
  mc("expert", "Who was the first gymnast to score a perfect 10 in Olympic competition?", "Nadia Comăneci", ["Olga Korbut", "Simone Biles", "Mary Lou Retton"]),
  mc("expert", "Roughly how much longer is a marathon than 26 miles, in yards?", "385 yards", ["100 yards", "880 yards", "1 mile"]),
  mc("expert", "Which jockey won the Kentucky Derby five times, first achieved in 1952?", "Eddie Arcaro", ["Willie Shoemaker", "Calvin Borel", "Victor Espinoza"]),
  mc("expert", "In what year did the first Super Bowl take place?", "1967", ["1965", "1970", "1960"]),
  mc("expert", "Which boxer was known as 'The Real Deal'?", "Evander Holyfield", ["Lennox Lewis", "George Foreman", "Larry Holmes"]),
  mc("expert", "What is the exact distance of a standard horse racing furlong in metres?", "201.168m", ["150m", "250m", "175m"]),
  mc("expert", "Who is the only player to win the Ballon d'Or eight times?", "Lionel Messi", ["Cristiano Ronaldo", "Zinedine Zidane", "Ronaldo Nazário"]),
  mc("expert", "In what year were women first allowed to compete in the modern Olympics?", "1900", ["1908", "1920", "1896"]),
  mc("expert", "Which country has won the most Rugby World Cups?", "New Zealand", ["South Africa", "England", "Australia"]),
  mc("expert", "What is the maximum break in snooker?", "147", ["155", "100", "180"]),
  mc("easy", "In American football, how many points is a touchdown worth?", "6 points", ["5 points", "7 points", "4 points"]),
  mc("easy", "Which sport uses a spherical ball and is played on a court with a net dividing two teams?", "Volleyball", ["Tennis", "Badminton", "Squash"]),
  mc("easy", "In basketball, how many players from each team are on the court at one time?", "5 players", ["6 players", "4 players", "7 players"]),
  mc("easy", "Which country hosts the Summer Olympic Games most recently before 2024?", "Japan", ["Brazil", "South Korea", "China"]),
  mc("easy", "In tennis, what is the term for a score of zero points?", "Love", ["Nil", "Zero", "Nothing"]),
  mc("medium", "Which golfer won the most major championships in professional golf history as of 2024?", "Tiger Woods", ["Jack Nicklaus", "Rory McIlroy", "Jon Rahm"]),
  mc("medium", "In Formula 1 racing, how many laps must a driver complete to have a race counted as official?", "More than half the scheduled distance", ["All scheduled laps", "75% of scheduled laps", "One complete lap"]),
  mc("medium", "Which National Hockey League team has won the most Stanley Cups?", "Montreal Canadiens", ["Toronto Maple Leafs", "New York Rangers", "Boston Bruins"]),
  mc("medium", "In cricket, what is the maximum number of runs a batter can score on a single legal delivery?", "6 runs", ["4 runs", "8 runs", "5 runs"]),
  mc("medium", "Which tennis player won the most Grand Slam singles titles in the Open Era?", "Novak Djokovic", ["Rafael Nadal", "Roger Federer", "Andy Murray"]),
  mc("hard", "In the sport of curling, what is the name of the stone-shaped equipment used in play?", "Rock", ["Slider", "Handle", "Broom"]),
  mc("hard", "Which NFL team won Super Bowl LIV in 2020?", "Kansas City Chiefs", ["San Francisco 49ers", "New England Patriots", "Tampa Bay Buccaneers"]),
  mc("hard", "In professional boxing, how many weight classes are recognized by the major sanctioning bodies?", "17", ["12", "15", "20"]),
  mc("expert", "Which cyclist won the Tour de France a record seven times before his records were vacated?", "Lance Armstrong", ["Eddy Merckx", "Bernard Hinault", "Miguel Indurain"]),
  mc("expert", "In sumo wrestling, what is the term for the elevated ring where matches take place?", "Dohyo", ["Dojo", "Honbasho", "Rikishi"]),
  mc("easy", "Which sport is played on a court with a net and a ball?", "Volleyball", ["American Football", "Golf", "Cricket"]),
  mc("easy", "In basketball, how many points is a three-pointer worth?", "3 points", ["2 points", "4 points", "5 points"]),
  mc("easy", "What is the maximum number of players on a soccer field per team?", "11", ["9", "10", "12"]),
  mc("easy", "Which country hosts the Tour de France cycling race?", "France", ["Italy", "Spain", "Belgium"]),
  mc("easy", "In tennis, what term describes a score of zero points?", "Love", ["Zero", "Nil", "Blank"]),
  mc("medium", "How many Grand Slam tennis tournaments are held annually?", "4", ["2", "3", "6"]),
  mc("medium", "Which Olympic sport features a pommel horse and parallel bars?", "Artistic Gymnastics", ["Rhythmic Gymnastics", "Trampoline", "Parkour"]),
  mc("medium", "In American football, how many yards must a team advance to earn a new set of downs?", "10", ["5", "15", "20"]),
  mc("medium", "What is the standard length of a cricket pitch between wickets?", "22 yards", ["20 yards", "25 yards", "30 yards"]),
  mc("medium", "Which martial art uses a gi uniform and emphasizes throwing techniques?", "Judo", ["Karate", "Taekwondo", "Kickboxing"]),
  mc("hard", "In Formula 1 racing, how many points does the race winner typically receive under current rules?", "25", ["20", "30", "15"]),
  mc("hard", "Which player won the most Grand Slam singles titles in tennis history as of 2023?", "Novak Djokovic", ["Roger Federer", "Rafael Nadal", "Margaret Court"]),
  mc("hard", "In rugby union, what is the value of a try?", "5 points", ["3 points", "4 points", "6 points"]),
  mc("expert", "Which team holds the record for most Stanley Cup championships in NHL history?", "Montreal Canadiens", ["Toronto Maple Leafs", "New York Rangers", "Detroit Red Wings"]),
  mc("expert", "In badminton, what is the maximum score needed to win a game under current international rules?", "21", ["15", "25", "20"]),
  mc("easy", "How many players are on a basketball team court at one time?", "5", ["4", "6", "7"]),
  mc("easy", "In tennis, what is the score called when both players are tied at 40-40?", "Deuce", ["Love", "Advantage", "Break point"]),
  mc("easy", "What is the maximum break in snooker worth in points?", "147", ["180", "100", "99"]),
  mc("medium", "Which country has won the most FIFA World Cup titles?", "Brazil", ["Germany", "France", "Argentina"]),
  mc("medium", "In boxing, what is the name of the area outside the ring where managers stand?", "Corner", ["Pocket", "Neutral zone", "Pit"]),
  mc("medium", "What is the diameter of a standard ice hockey puck in inches?", "3", ["2", "4", "2.5"]),
  mc("medium", "How many grand slam tournaments are there in professional tennis per year?", "4", ["5", "3", "6"]),
  mc("medium", "What is the only NFL team that plays its home games in two different cities?", "New York Giants and Jets", ["Los Angeles Rams and Chargers", "San Francisco 49ers", "Dallas Cowboys"]),
  mc("hard", "In cricket, what is the term for a batsman being out without scoring a run?", "Duck", ["Goose", "Bird", "Wicket"]),
  mc("hard", "Which Formula 1 driver holds the record for most career victories as of 2024?", "Lewis Hamilton", ["Max Verstappen", "Sebastian Vettel", "Michael Schumacher"]),
  mc("hard", "In sumo wrestling, what is the term for the tournament held six times per year?", "Honbasho", ["Dohyo", "Rikishi", "Basho"]),
  mc("expert", "What is the Queensberry Rules named after in boxing?", "John Sholto Douglas, 9th Marquess of Queensberry", ["A boxing arena called Queensberry Hall", "Queen Victoria's favorite sport", "A Scottish town named Queensberry"]),
  mc("expert", "In Olympic badminton, what is the minimum height of the net at its center?", "17 inches", ["18 inches", "16 inches", "20 inches"]),
  mc("easy", "Which country won the FIFA World Cup in 2018?", "France", ["Germany", "Brazil", "Belgium"]),
  mc("medium", "What is the maximum break in professional snooker?", "147", ["180", "140", "150"]),
  mc("medium", "How many strings does a standard tennis racket typically have?", "16-20", ["12-15", "21-24", "25-28"]),
];
