import { mc } from "./seed";
import type { QuestionSeed } from "./seed";

export const SPORTS_SEEDS: QuestionSeed[] = [
  mc("easy", "How many players are on a basketball court for one team at a time?", "5", ["6", "7", "4"]),
  mc("easy", "How many players are on a soccer team on the field at once?", "11", ["10", "9", "12"]),
  mc("easy", "In bowling, what is a perfect game's score?", "300", ["250", "200", "350"]),
  mc("easy", "What sport is played at Wimbledon?", "Tennis", ["Cricket", "Golf", "Badminton"]),
  mc("easy", "How many holes are on a standard golf course?", "18", ["16", "20", "12"]),
  mc("easy", "What shape is a soccer ball traditionally made of?", "Hexagons and pentagons", ["Squares", "Triangles", "Circles only"]),
  mc("easy", "How many points is a touchdown worth in American football?", "6", ["7", "3", "10"]),
  mc("easy", "Which sport uses a shuttlecock?", "Badminton", ["Tennis", "Squash", "Table tennis"]),
  mc("easy", "How many periods are in a standard ice hockey game?", "3", ["2", "4", "5"]),
  mc("easy", "What is the maximum score for a single dart throw?", "60", ["50", "40", "100"]),
  mc("medium", "How many Grand Slam tennis tournaments are there per year?", "4", ["3", "5", "6"]),
  mc("medium", "In what year were the first modern Olympic Games held?", "1896", ["1900", "1888", "1920"]),
  mc("medium", "Which country has won the most FIFA World Cups?", "Brazil", ["Germany", "Argentina", "Italy"]),
  mc("medium", "How many players are on a volleyball team on each side?", "6", ["5", "7", "4"]),
  mc("medium", "What is the term for scoring three goals in one soccer match?", "Hat trick", ["Triple play", "Grand slam", "Treble"]),
  mc("medium", "Which boxing weight class is heaviest?", "Heavyweight", ["Middleweight", "Welterweight", "Cruiserweight"]),
  mc("medium", "How long is a marathon, in miles (approximately)?", "26.2", ["20", "30", "24"]),
  mc("medium", "In baseball, how many strikes make an out?", "3", ["2", "4", "5"]),
  mc("medium", "Which country invented table tennis?", "England", ["China", "Japan", "Germany"]),
  mc("medium", "How many rings are on the Olympic flag?", "5", ["4", "6", "7"]),
  mc("hard", "Who holds the record for most career home runs in MLB history?", "Barry Bonds", ["Babe Ruth", "Hank Aaron", "Alex Rodriguez"]),
  mc("hard", "Which tennis player has won the most Grand Slam singles titles (men's, as of recent years)?", "Novak Djokovic", ["Roger Federer", "Rafael Nadal", "Pete Sampras"]),
  mc("hard", "What is the diameter of a basketball hoop, in inches?", "18", ["16", "20", "15"]),
  mc("hard", "Which NFL team won the very first Super Bowl?", "Green Bay Packers", ["Dallas Cowboys", "Kansas City Chiefs", "Oakland Raiders"]),
  mc("hard", "In cricket, how many runs is a 'six' worth?", "6", ["4", "5", "8"]),
  mc("hard", "Which country hosted the first FIFA World Cup in 1930?", "Uruguay", ["Brazil", "Italy", "France"]),
  mc("expert", "Who was the first gymnast to score a perfect 10 in Olympic competition?", "Nadia Comăneci", ["Olga Korbut", "Simone Biles", "Mary Lou Retton"]),
  mc("expert", "Roughly how much longer is a marathon than 26 miles, in yards?", "385 yards", ["100 yards", "880 yards", "1 mile"]),
  mc("expert", "Which of these jockeys won the Kentucky Derby five times, a feat first achieved in 1952?", "Eddie Arcaro", ["Willie Shoemaker", "Calvin Borel", "Victor Espinoza"]),
  mc("expert", "In what year did the first Super Bowl take place?", "1967", ["1965", "1970", "1960"]),
];
