import { mc } from "./seed";
import type { QuestionSeed } from "./seed";

export const TECHNOLOGY_SEEDS: QuestionSeed[] = [
  mc("easy", "What does 'www' stand for in a website address?", "World Wide Web", ["World Wide Window", "Web Wide World", "Worldwide Website"]),
  mc("easy", "What company makes the iPhone?", "Apple", ["Samsung", "Google", "Microsoft"]),
  mc("easy", "What does CPU stand for?", "Central Processing Unit", ["Computer Processing Unit", "Central Power Unit", "Core Processing Utility"]),
  mc("easy", "What is the most popular search engine?", "Google", ["Bing", "Yahoo", "DuckDuckGo"]),
  mc("easy", "What does USB stand for?", "Universal Serial Bus", ["Universal System Bus", "United Serial Base", "Universal Storage Bus"]),
  mc("easy", "What social media platform is known for short videos and dances?", "TikTok", ["Instagram", "Snapchat", "YouTube"]),
  mc("easy", "Which company created the Windows operating system?", "Microsoft", ["Apple", "IBM", "Google"]),
  mc("easy", "What does 'Wi-Fi' allow devices to do?", "Connect to the internet wirelessly", ["Charge wirelessly", "Share files via Bluetooth", "Make phone calls"]),
  mc("easy", "What does RAM stand for?", "Random Access Memory", ["Read Access Memory", "Rapid Access Module", "Random Array Memory"]),
  mc("easy", "What is the name of Apple's voice assistant?", "Siri", ["Cortana", "Alexa", "Google Assistant"]),
  mc("easy", "Which company owns YouTube?", "Google", ["Meta", "Microsoft", "Amazon"]),
  mc("easy", "What does 'PDF' stand for?", "Portable Document Format", ["Printed Digital File", "Public Domain Format", "Print Display File"]),
  mc("easy", "Which company makes the Android operating system?", "Google", ["Samsung", "Apple", "Microsoft"]),
  mc("easy", "As of 2024, which social media platform has the highest number of monthly active users worldwide?", "Facebook", ["YouTube", "Instagram", "TikTok"]),
  mc("easy", "What does 'AI' stand for?", "Artificial Intelligence", ["Automated Internet", "Advanced Integration", "Automated Information"]),
  mc("easy", "What is the name of Amazon's voice assistant?", "Alexa", ["Siri", "Cortana", "Google"]),
  mc("easy", "Which key is used to undo an action on a computer?", "Ctrl+Z", ["Ctrl+X", "Ctrl+Y", "Ctrl+U"]),
  mc("easy", "In web development, what is the standard filename typically used as the default entry point when accessing a directory on a web server?", "index.html", ["home.html", "default.html", "start.html"]),
  mc("easy", "What device reads barcodes at stores?", "Barcode scanner", ["QR reader", "Laser printer", "RFID reader"]),
  mc("easy", "What does 'GPS' stand for?", "Global Positioning System", ["General Placement System", "Geographic Positioning Service", "Global Proximity System"]),
  mc("medium", "Who co-founded Apple with Steve Jobs?", "Steve Wozniak", ["Bill Gates", "Paul Allen", "Tim Cook"]),
  mc("medium", "What programming language is primarily used for web styling?", "CSS", ["HTML", "JavaScript", "Python"]),
  mc("medium", "What does 'HTTP' stand for?", "HyperText Transfer Protocol", ["HyperText Transport Process", "High Transfer Text Protocol", "HyperText Terminal Procedure"]),
  mc("medium", "Which company originally created the Java programming language in 1995?", "Sun Microsystems", ["Microsoft", "IBM", "Apple"]),
  mc("medium", "What is the name of the world's first computer bug (literally)?", "A moth found in a relay", ["A virus in code", "A corrupted punch card", "A short circuit"]),
  mc("medium", "What year was the iPhone first released?", "2007", ["2005", "2009", "2010"]),
  mc("medium", "What is the binary representation of the number 8?", "1000", ["1001", "0111", "1100"]),
  mc("medium", "What does 'SSD' stand for in computer storage?", "Solid State Drive", ["Super Speed Disk", "Static Storage Device", "Solid System Disk"]),
  mc("medium", "Which company developed the PlayStation?", "Sony", ["Nintendo", "Microsoft", "Sega"]),
  mc("medium", "What is the name of the coding language used for the web's structure?", "HTML", ["CSS", "JavaScript", "PHP"]),
  mc("medium", "What year was Facebook launched?", "2004", ["2002", "2006", "2008"]),
  mc("medium", "What is the term for malicious software that encrypts your files for ransom?", "Ransomware", ["Spyware", "Adware", "Trojan"]),
  mc("medium", "What company created the first commercial smartphone?", "IBM (Simon, 1994)", ["Apple", "Nokia", "BlackBerry"]),
  mc("medium", "What is the name of Elon Musk's AI company?", "xAI", ["OpenAI", "DeepMind", "Anthropic"]),
  mc("medium", "What does 'VPN' stand for?", "Virtual Private Network", ["Verified Protected Network", "Virtual Protected Node", "Verified Private Network"]),
  mc("medium", "Which programming language is named after a Monty Python sketch?", "Python", ["Perl", "Ruby", "Cobra"]),
  mc("hard", "What was the name of the world's first general-purpose electronic computer?", "ENIAC", ["UNIVAC", "Colossus", "Turing Machine"]),
  mc("hard", "What does 'SQL' stand for?", "Structured Query Language", ["Sequential Query Language", "System Query Language", "Structured Question Logic"]),
  mc("hard", "In what year did Tim Berners-Lee first propose the concept of the World Wide Web at CERN?", "1989", ["1985", "1991", "1993"]),
  mc("hard", "In computer architecture, what term refers to the number of bits a CPU's data bus can transfer simultaneously?", "Bus width", ["Word size", "Clock speed", "Cache line size"]),
  mc("hard", "What protocol assigns IP addresses to devices on a network?", "DHCP", ["DNS", "FTP", "TCP"]),
  mc("hard", "Which company developed the first widely-used graphical user interface?", "Xerox", ["Apple", "Microsoft", "IBM"]),
  mc("hard", "Which operating system served as the primary inspiration and design model for Linux when Linus Torvalds created it in 1991?", "Unix", ["MINIX", "GNU", "BSD"]),
  mc("hard", "What is Moore's Law?", "The number of transistors on a chip doubles roughly every 2 years", ["Processing speed doubles every year", "Storage cost halves every 18 months", "Internet speed doubles every 3 years"]),
  mc("hard", "What is the name of the vulnerability that exploits buffer overflow attacks?", "Stack smashing", ["SQL injection", "XSS", "CSRF"]),
  mc("hard", "Which country is home to the company that makes the most semiconductors?", "Taiwan (TSMC)", ["South Korea", "USA", "Japan"]),
  mc("expert", "What is the theoretical maximum speed of USB 4?", "40 Gbps", ["10 Gbps", "20 Gbps", "80 Gbps"]),
  mc("expert", "What does 'RISC' stand for in computer architecture?", "Reduced Instruction Set Computer", ["Rapid Instruction Set Compiler", "Reduced Integration System Core", "Real-time Instruction Set Computer"]),
  mc("expert", "Which cryptographic hash function produces a 256-bit output?", "SHA-256", ["MD5", "SHA-1", "SHA-512"]),
  mc("expert", "What is the name of the algorithm used by Google's original PageRank?", "PageRank algorithm (named after Larry Page)", ["Breadth-first search", "Dijkstra's algorithm", "MapReduce"]),
  mc("expert", "In networking, what does 'BGP' stand for?", "Border Gateway Protocol", ["Basic Gateway Protocol", "Bandwidth Gateway Process", "Bridge Gateway Protocol"]),
  mc("expert", "What is the name of the major unsolved problem in computer science that asks whether every problem whose solution can be verified quickly can also be solved quickly?", "P vs NP problem", ["Halting problem", "Busy beaver problem", "Rice's theorem"]),
  mc("expert", "What year was the first version of Python released?", "1991", ["1989", "1995", "1993"]),
  mc("expert", "Which company released the first commercially available relational database management system, System/R, in the 1970s?", "IBM", ["Oracle", "Microsoft", "Digital Equipment Corporation"]),
  mc("expert", "What does 'CUDA' stand for?", "Compute Unified Device Architecture", ["Central Unified Data Array", "Compute Universal Device Adapter", "Core Unified Digital Architecture"]),
  mc("expert", "What is the name of the famous open-source license used by the Linux kernel?", "GPL (GNU General Public License)", ["MIT License", "Apache License", "BSD License"]),
  mc("easy", "What does 'CPU' stand for?", "Central Processing Unit", ["Computer Processing Utility", "Central Program Utilizer", "Computer Processor Unit"]),
  mc("easy", "Which company created the Android operating system?", "Google", ["Apple", "Microsoft", "Samsung"]),
  mc("easy", "What does 'WiFi' stand for?", "Wireless Fidelity", ["Wireless Internet Frequency", "Wired Internet Format", "Wireless Internet Foundation"]),
  mc("medium", "In what year was the first iPhone released?", "2007", ["2005", "2008", "2006"]),
  mc("medium", "What is the primary function of a GPU?", "Process graphics and render images", ["Manage system memory allocation", "Handle all network communication", "Store permanent data files"]),
  mc("medium", "Which programming language was created by Guido van Rossum?", "Python", ["Java", "Ruby", "Go"]),
  mc("medium", "What does 'HTML' stand for?", "HyperText Markup Language", ["High-Tech Modern Language", "Home Tool Markup Language", "Hyperlink and Text Markup Language"]),
  mc("medium", "Which company developed the Windows operating system?", "Microsoft", ["Intel", "Apple", "IBM"]),
  mc("hard", "What is the name of the open-source kernel used in Linux systems?", "Linux kernel", ["GNU kernel", "Unix core", "Linus kernel"]),
  mc("hard", "In cybersecurity, what does 'RSA' stand for?", "Rivest-Shamir-Adleman", ["Restricted Security Algorithm", "Rapid Secure Authentication", "Remote Server Architecture"]),
  mc("hard", "Which company acquired WhatsApp for approximately $19 billion in 2014?", "Facebook", ["Google", "Microsoft", "Apple"]),
  mc("hard", "What is the maximum theoretical bandwidth of USB 3.1?", "10 Gbps", ["5 Gbps", "20 Gbps", "15 Gbps"]),
  mc("expert", "What does 'ASIC' refer to in cryptocurrency mining?", "Application-Specific Integrated Circuit", ["Advanced Security Integration Code", "Automated System for Integrated Computing", "Application Software Interface Component"]),
  mc("expert", "Which algorithm is primarily used by Bitcoin for proof-of-work consensus?", "SHA-256", ["MD5", "Scrypt", "Blake2b"]),
  mc("expert", "What is the maximum latency target specified by 3GPP for 5G URLLC (Ultra-Reliable Low-Latency Communications) services?", "1 millisecond", ["10 milliseconds", "0.1 milliseconds", "100 milliseconds"]),
  mc("easy", "Which company created the iPhone?", "Apple", ["Samsung", "Microsoft", "Google"]),
  mc("medium", "Which graphical web browser was the first to achieve widespread commercial adoption in the early 1990s?", "Mosaic", ["Netscape Navigator", "Internet Explorer", "Opera"]),
  mc("medium", "What programming language is known as the 'language of the web'?", "JavaScript", ["Python", "Java", "C++"]),
  mc("medium", "Which cloud storage service is owned by Amazon?", "Amazon S3", ["Google Drive", "Dropbox", "OneDrive"]),
  mc("medium", "What does 'GPU' stand for?", "Graphics Processing Unit", ["General Purpose Unit", "Global Processing Utility", "Graphical Program Utility"]),
  mc("hard", "Who is credited with inventing the World Wide Web?", "Tim Berners-Lee", ["Bill Gates", "Steve Jobs", "Larry Page"]),
  mc("hard", "What is the primary function of a blockchain's 'nonce'?", "To satisfy the proof-of-work requirement", ["To encrypt transaction data", "To verify user identity", "To store wallet addresses"]),
  mc("hard", "What is the primary protocol layer that HTTPS relies upon to encrypt and authenticate data transmission?", "TLS (Transport Layer Security)", ["IP (Internet Protocol)", "DNS (Domain Name System)", "TCP (Transmission Control Protocol)"]),
  mc("hard", "Which architecture pattern separates application logic into three interconnected components?", "Model-View-Controller (MVC)", ["Repository Pattern", "Singleton Pattern", "Observer Pattern"]),
  mc("expert", "What is the maximum theoretical bandwidth of USB 3.1 Gen 2?", "10 Gbps", ["5 Gbps", "20 Gbps", "2.5 Gbps"]),
  mc("expert", "In machine learning, what is the process of adjusting model weights to minimize loss called?", "Backpropagation", ["Overfitting", "Regularization", "Hyperparameter tuning"]),
  mc("expert", "What quantum computing concept allows a qubit to exist in multiple states simultaneously?", "Superposition", ["Entanglement", "Quantum tunneling", "Decoherence"]),
  mc("expert", "Which open-source container orchestration platform was originally developed by Google?", "Kubernetes", ["Docker Swarm", "OpenStack", "Mesos"]),
  mc("easy", "What does 'USB' stand for?", "Universal Serial Bus", ["Universal Standard Binary", "Unified Serial Bridge", "Universal System Buffer"]),
  mc("medium", "What is the primary programming language used to build most websites?", "JavaScript", ["Python", "C++", "Java"]),
  mc("medium", "What does 'GPU' primarily accelerate in modern computers?", "Graphics rendering", ["Network connections", "RAM speed", "Hard drive access"]),
  mc("medium", "Which programming language is known for its use in artificial intelligence and machine learning?", "Python", ["Swift", "Ruby", "Go"]),
  mc("hard", "What is the name of the open-source machine learning library developed by Google?", "TensorFlow", ["PyTorch", "Keras", "Theano"]),
  mc("hard", "In cybersecurity, what does 'zero-day' refer to?", "An unpatched software vulnerability unknown to the vendor", ["A firewall with zero protection", "A network with no active users", "An encryption key with zero entropy"]),
  mc("hard", "What does 'RAID' stand for in data storage?", "Redundant Array of Independent Disks", ["Rapid Array Interface Design", "Redundant Automated Input Device", "Remote Array Integration Disk"]),
  mc("hard", "In 2021, IBM acquired which quantum computing hardware company?", "Qiskit (as part of its quantum ecosystem)", ["D-Wave Systems", "IonQ", "Rigetti Computing"]),
  mc("expert", "What is the theoretical maximum throughput of USB 3.2 Gen 2x2?", "20 Gbps", ["10 Gbps", "30 Gbps", "15 Gbps"]),
  mc("expert", "In blockchain technology, what is the consensus mechanism used by Ethereum as of 2024?", "Proof of Stake", ["Proof of Work", "Proof of History", "Practical Byzantine Fault Tolerance"]),
  mc("expert", "Which key exchange mechanism is mandatory in TLS 1.3?", "ECDHE (Elliptic Curve Diffie-Hellman Ephemeral)", ["RSA key transport", "Static Diffie-Hellman", "AES-256-GCM"]),
  mc("medium", "What is the name of the open-source operating system kernel created by Linus Torvalds?", "Linux", ["Unix", "GNU", "POSIX"]),
  mc("medium", "Which technology company acquired WhatsApp in 2014?", "Facebook", ["Google", "Microsoft", "Apple"]),
  mc("medium", "What does 'GPU' stand for in computing?", "Graphics Processing Unit", ["General Purpose Utility", "Global Processing Unit", "Graphics Programming Utility"]),
  mc("hard", "Which encryption algorithm is the successor to DES and was adopted as the AES standard in 2001?", "Rijndael", ["Blowfish", "RSA", "Serpent"]),
  mc("hard", "What is the name of the first web browser, created by Tim Berners-Lee?", "WorldWideWeb", ["Mosaic", "Netscape Navigator", "Internet Explorer"]),
  mc("hard", "In quantum computing, what is the quantum equivalent of a classical bit called?", "Qubit", ["Quantbit", "Qbit", "Quantum bit register"]),
  mc("expert", "What is the total number of unique addresses that can be represented in the IPv4 address space?", "2^32 (approximately 4.3 billion)", ["2^48 (approximately 281 trillion)", "2^16 (approximately 65 thousand)", "2^24 (approximately 16.7 million)"]),
];
