import { mc } from "./seed";
import type { QuestionSeed } from "./seed";

export const TECHNOLOGY_SEEDS: QuestionSeed[] = [
  mc("easy", "What does 'www' stand for in a website address?", "World Wide Web", ["World Wide Window", "Web Wide World", "Worldwide Website"]),
  mc("easy", "What company makes the iPhone?", "Apple", ["Samsung", "Google", "Microsoft"]),
  mc("easy", "What does CPU stand for?", "Central Processing Unit", ["Computer Processing Unit", "Central Power Unit", "Core Processing Utility"]),
  mc("easy", "What is the most popular search engine?", "Google", ["Bing", "Yahoo", "DuckDuckGo"]),
  mc("easy", "What does USB stand for?", "Universal Serial Bus", ["Universal System Bus", "United Serial Base", "Universal Storage Bus"]),
  mc("easy", "What social media platform is known for short videos and dances?", "TikTok", ["Instagram", "Snapchat", "YouTube"]),
  mc("easy", "Which company created the Windows operating system?", "Microsoft", ["Apple", "IBM", "Google"]),
  mc("easy", "What does 'Wi-Fi' allow devices to do?", "Connect to the internet wirelessly", ["Charge wirelessly", "Share files via Bluetooth", "Make phone calls"]),
  mc("easy", "What does RAM stand for?", "Random Access Memory", ["Read Access Memory", "Rapid Access Module", "Random Array Memory"]),
  mc("easy", "What is the name of Apple's voice assistant?", "Siri", ["Cortana", "Alexa", "Google Assistant"]),
  mc("easy", "Which company owns YouTube?", "Google", ["Meta", "Microsoft", "Amazon"]),
  mc("easy", "What does 'PDF' stand for?", "Portable Document Format", ["Printed Digital File", "Public Domain Format", "Print Display File"]),
  mc("easy", "Which company makes the Android operating system?", "Google", ["Samsung", "Apple", "Microsoft"]),
  mc("easy", "What is the most used social media platform in the world?", "Facebook", ["YouTube", "Instagram", "TikTok"]),
  mc("easy", "What does 'AI' stand for?", "Artificial Intelligence", ["Automated Internet", "Advanced Integration", "Automated Information"]),
  mc("easy", "What is the name of Amazon's voice assistant?", "Alexa", ["Siri", "Cortana", "Google"]),
  mc("easy", "Which key is used to undo an action on a computer?", "Ctrl+Z", ["Ctrl+X", "Ctrl+Y", "Ctrl+U"]),
  mc("easy", "What do you call the main page of a website?", "Homepage", ["Index page", "Start page", "Default page"]),
  mc("easy", "What device reads barcodes at stores?", "Barcode scanner", ["QR reader", "Laser printer", "RFID reader"]),
  mc("easy", "What does 'GPS' stand for?", "Global Positioning System", ["General Placement System", "Geographic Positioning Service", "Global Proximity System"]),
  mc("medium", "Who co-founded Apple with Steve Jobs?", "Steve Wozniak", ["Bill Gates", "Paul Allen", "Tim Cook"]),
  mc("medium", "What programming language is primarily used for web styling?", "CSS", ["HTML", "JavaScript", "Python"]),
  mc("medium", "What does 'HTTP' stand for?", "HyperText Transfer Protocol", ["HyperText Transport Process", "High Transfer Text Protocol", "HyperText Terminal Procedure"]),
  mc("medium", "Which company created the Java programming language?", "Sun Microsystems", ["Microsoft", "IBM", "Oracle"]),
  mc("medium", "What is the name of the world's first computer bug (literally)?", "A moth found in a relay", ["A virus in code", "A corrupted punch card", "A short circuit"]),
  mc("medium", "What year was the iPhone first released?", "2007", ["2005", "2009", "2010"]),
  mc("medium", "What is the binary representation of the number 8?", "1000", ["1001", "0111", "1100"]),
  mc("medium", "What does 'SSD' stand for in computer storage?", "Solid State Drive", ["Super Speed Disk", "Static Storage Device", "Solid System Disk"]),
  mc("medium", "Which company developed the PlayStation?", "Sony", ["Nintendo", "Microsoft", "Sega"]),
  mc("medium", "What is the name of the coding language used for the web's structure?", "HTML", ["CSS", "JavaScript", "PHP"]),
  mc("medium", "What year was Facebook launched?", "2004", ["2002", "2006", "2008"]),
  mc("medium", "What is the term for malicious software that encrypts your files for ransom?", "Ransomware", ["Spyware", "Adware", "Trojan"]),
  mc("medium", "What company created the first commercial smartphone?", "IBM (Simon, 1994)", ["Apple", "Nokia", "BlackBerry"]),
  mc("medium", "What is the name of Elon Musk's AI company?", "xAI", ["OpenAI", "DeepMind", "Anthropic"]),
  mc("medium", "What does 'VPN' stand for?", "Virtual Private Network", ["Verified Protected Network", "Virtual Protected Node", "Verified Private Network"]),
  mc("medium", "Which programming language is named after a Monty Python sketch?", "Python", ["Perl", "Ruby", "Cobra"]),
  mc("hard", "What was the name of the world's first general-purpose electronic computer?", "ENIAC", ["UNIVAC", "Colossus", "Turing Machine"]),
  mc("hard", "What does 'SQL' stand for?", "Structured Query Language", ["Sequential Query Language", "System Query Language", "Structured Question Logic"]),
  mc("hard", "In what year was the World Wide Web invented by Tim Berners-Lee?", "1989", ["1983", "1995", "1991"]),
  mc("hard", "What is the term for the number of bits a computer's CPU can process at once?", "Word size", ["Bit depth", "Clock speed", "Bus width"]),
  mc("hard", "What protocol assigns IP addresses to devices on a network?", "DHCP", ["DNS", "FTP", "TCP"]),
  mc("hard", "Which company developed the first widely-used graphical user interface?", "Xerox", ["Apple", "Microsoft", "IBM"]),
  mc("hard", "What is the name of the open-source kernel that Linux is based on?", "Linux kernel", ["GNU", "Unix", "BSD"]),
  mc("hard", "What is Moore's Law?", "The number of transistors on a chip doubles roughly every 2 years", ["Processing speed doubles every year", "Storage cost halves every 18 months", "Internet speed doubles every 3 years"]),
  mc("hard", "What is the name of the vulnerability that exploits buffer overflow attacks?", "Stack smashing", ["SQL injection", "XSS", "CSRF"]),
  mc("hard", "Which country is home to the company that makes the most semiconductors?", "Taiwan (TSMC)", ["South Korea", "USA", "Japan"]),
  mc("expert", "What is the theoretical maximum speed of USB 4?", "40 Gbps", ["10 Gbps", "20 Gbps", "80 Gbps"]),
  mc("expert", "What does 'RISC' stand for in computer architecture?", "Reduced Instruction Set Computer", ["Rapid Instruction Set Compiler", "Reduced Integration System Core", "Real-time Instruction Set Computer"]),
  mc("expert", "Which cryptographic hash function produces a 256-bit output?", "SHA-256", ["MD5", "SHA-1", "SHA-512"]),
  mc("expert", "What is the name of the algorithm used by Google's original PageRank?", "PageRank algorithm (named after Larry Page)", ["Breadth-first search", "Dijkstra's algorithm", "MapReduce"]),
  mc("expert", "In networking, what does 'BGP' stand for?", "Border Gateway Protocol", ["Basic Gateway Protocol", "Bandwidth Gateway Process", "Bridge Gateway Protocol"]),
  mc("expert", "What is the name of the problem in computer science where P equals NP?", "P vs NP problem", ["Halting problem", "Four color theorem", "Travelling salesman"]),
  mc("expert", "What year was the first version of Python released?", "1991", ["1989", "1995", "1993"]),
  mc("expert", "Which company created the first commercially successful relational database?", "Oracle", ["IBM", "Microsoft", "Ingres"]),
  mc("expert", "What does 'CUDA' stand for?", "Compute Unified Device Architecture", ["Central Unified Data Array", "Compute Universal Device Adapter", "Core Unified Digital Architecture"]),
  mc("expert", "What is the name of the famous open-source license used by the Linux kernel?", "GPL (GNU General Public License)", ["MIT License", "Apache License", "BSD License"]),
];
