import { mc } from "./seed";
import type { QuestionSeed } from "./seed";

export const TECHNOLOGY_SEEDS: QuestionSeed[] = [
  mc("easy", "What does CPU stand for?", "Central Processing Unit", ["Computer Power Unit", "Central Program Utility", "Core Processing Unit"]),
  mc("easy", "Who founded Microsoft?", "Bill Gates", ["Steve Jobs", "Mark Zuckerberg", "Elon Musk"]),
  mc("easy", "What does 'www' stand for?", "World Wide Web", ["World Wide Wire", "Web World Wide", "Wide World Web"]),
  mc("easy", "What company makes the iPhone?", "Apple", ["Samsung", "Google", "Sony"]),
  mc("easy", "What does GPS stand for?", "Global Positioning System", ["General Positioning Service", "Global Pathing Software", "Geo Position Sensor"]),
  mc("easy", "What is the most popular operating system for smartphones worldwide?", "Android", ["iOS", "Windows", "Linux"]),
  mc("easy", "What does 'PDF' stand for?", "Portable Document Format", ["Personal Data File", "Print Document Format", "Public Data Format"]),
  mc("easy", "Who co-founded Google in 1998?", "Larry Page and Sergey Brin", ["Bill Gates and Paul Allen", "Steve Jobs and Steve Wozniak", "Jeff Bezos and Mark Zuckerberg"]),
  mc("easy", "What is the name of Amazon's voice assistant?", "Alexa", ["Siri", "Cortana", "Bixby"]),
  mc("easy", "What does 'HTML' stand for?", "HyperText Markup Language", ["HyperText Modern Language", "Home Tool Markup Language", "Hyperlink Text Markup Language"]),
  mc("medium", "Who is credited as the co-founder of Apple alongside Steve Jobs?", "Steve Wozniak", ["Steve Ballmer", "Tim Cook", "Jonathan Ive"]),
  mc("medium", "What does 'RAM' stand for?", "Random Access Memory", ["Read Access Memory", "Rapid Access Module", "Run Access Memory"]),
  mc("medium", "Which company developed the Android operating system before Google?", "Android Inc.", ["Motorola", "Samsung", "Nokia"]),
  mc("medium", "What year was the first iPhone released?", "2007", ["2005", "2009", "2010"]),
  mc("medium", "What does 'AI' stand for in technology?", "Artificial Intelligence", ["Automated Information", "Advanced Interface", "Algorithmic Input"]),
  mc("medium", "Which programming language is known for being used to style web pages?", "CSS", ["HTML", "Python", "Java"]),
  mc("medium", "What is the name of the social media platform founded by Mark Zuckerberg?", "Facebook", ["Twitter", "LinkedIn", "Snapchat"]),
  mc("medium", "What does 'USB' stand for?", "Universal Serial Bus", ["United System Bus", "Universal System Board", "Unified Serial Board"]),
  mc("medium", "Which company developed the Java programming language?", "Sun Microsystems", ["Microsoft", "IBM", "Oracle"]),
  mc("medium", "What is the term for unwanted software that disrupts computer operation?", "Malware", ["Firmware", "Shareware", "Freeware"]),
  mc("hard", "Who is considered the 'father of the computer' for designing the Analytical Engine?", "Charles Babbage", ["Alan Turing", "John von Neumann", "Ada Lovelace"]),
  mc("hard", "What does 'HTTP' stand for?", "HyperText Transfer Protocol", ["HyperText Transmission Process", "Hyperlink Text Transfer Protocol", "Home Text Transfer Protocol"]),
  mc("hard", "Which company originally created the Unix operating system?", "Bell Labs", ["IBM", "Microsoft", "Apple"]),
  mc("hard", "What is the name of the first widely-used web browser, released in 1993?", "Mosaic", ["Netscape Navigator", "Internet Explorer", "Lynx"]),
  mc("hard", "Who is widely credited as a founder of the World Wide Web?", "Tim Berners-Lee", ["Vint Cerf", "Marc Andreessen", "Larry Page"]),
  mc("hard", "What does 'SSD' stand for?", "Solid State Drive", ["Static Storage Device", "Secure System Drive", "Single Storage Disk"]),
  mc("expert", "What was the name of the first computer virus to spread widely via floppy disks in the 1980s?", "Elk Cloner", ["Brain Boot Sector Virus", "Stoned Virus", "Creeper Virus"]),
  mc("expert", "Which company developed the first commercially successful graphical user interface computer, the Lisa?", "Apple", ["Xerox", "IBM", "Commodore"]),
  mc("expert", "What does 'TCP/IP' primarily govern?", "How data is transmitted across networks", ["How files are compressed", "How websites are styled", "How passwords are encrypted"]),
  mc("expert", "Who wrote the first computer algorithm, intended for Babbage's Analytical Engine?", "Ada Lovelace", ["Grace Hopper", "Alan Turing", "Charles Babbage"]),
];
